<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Stories_b1-b5-AvatarImage_Url</name>
   <tag></tag>
   <elementGuidId>1e8807ba-d3c6-435d-b283-206fe8b80475</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b1-b5-AvatarImage_Url</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@ktl-id='imgAvatar']/div/div/div/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#b1-b4-Dropdownmenu >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>704beca9-b120-4b63-be04-ce9f9b945f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/res/getGiverImage/db15a20a-45a0-412a-a61d-7ce128c52685.jpg</value>
      <webElementGuid>df28d5c1-19a6-4e87-af14-1e96625c1a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b1-b5-AvatarImage_Url</value>
      <webElementGuid>d33955d7-a3fb-4fbb-bf61-e12d8b472112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-b5-AvatarImage_Url&quot;)</value>
      <webElementGuid>d261c5d9-f684-40d4-b930-eeb5965ee7a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='b1-b5-AvatarImage_Url']</value>
      <webElementGuid>7bbb1866-de80-41eb-b506-b8f598cbcb57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-$b5']/div/img</value>
      <webElementGuid>65e8a01f-066a-495f-8419-5477cc136eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/img</value>
      <webElementGuid>e37a02fc-8765-4017-ae25-f1dd288f5d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/res/getGiverImage/db15a20a-45a0-412a-a61d-7ce128c52685.jpg' and @id = 'b1-b5-AvatarImage_Url']</value>
      <webElementGuid>37a21333-c575-4454-ba19-7b690bdbd313</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
