<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Suitable for_b2-b8-b24-l1-315_4-Checkbox</name>
   <tag></tag>
   <elementGuidId>3ec3fb18-16ce-4b7f-8237-d146e704021c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b8-b24-l1-315_4-Checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b8-b24-l1-315_4-Checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;First timers&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b7ca85a-8995-47c2-8d52-3323d540baea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>411a2429-ff11-44fe-a952-0bedf0eecf25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>460a39cf-befb-4da7-9b7f-0c37f90f4f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b8-b24-l1-315_4-Checkbox</value>
      <webElementGuid>4c9e7206-c073-4b1f-9e30-524f245db89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>aae555eb-1af2-42b1-84b5-40e89672c2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b8-b24-l1-315_4-Checkbox&quot;)</value>
      <webElementGuid>f986ad44-ebd9-4dea-bb57-5dec76eb5fcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b8-b24-l1-315_4-Checkbox']</value>
      <webElementGuid>88150440-fb95-4ad2-b19f-97cfd94a1455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b8-b24-l1-315_4-b1-Control']/span/input</value>
      <webElementGuid>e98e4a48-577c-41cd-a396-8698f5f469b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/span/input</value>
      <webElementGuid>95dcb780-3b96-485b-bf6a-96212d7ba010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b8-b24-l1-315_4-Checkbox']</value>
      <webElementGuid>adefcebe-a8b3-4401-8ba0-718429e7c8da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
