<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Suitable for_b2-b8-b24-l1-315_0-Checkbox</name>
   <tag></tag>
   <elementGuidId>6df55b7a-d759-4e50-84d8-a61859a52bdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b8-b24-l1-315_0-Checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@ktl-id='divSuitableFor']/div[1]/div/div[3]/div[1]/div/div[1]/div/div[1]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;First timers&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8aed4d1f-87f0-4e0a-a6e8-54c6ed97c048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e9b974f3-d6fd-4890-8295-0239a4191e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>62c88653-b582-4c8e-a885-55e46aa4acb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b8-b24-l1-315_0-Checkbox</value>
      <webElementGuid>6f5aef98-c584-4550-b6b8-6f0189b06f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c1bb63b8-505c-4bbe-8182-e93e879b44e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b8-b24-l1-315_0-Checkbox&quot;)</value>
      <webElementGuid>36f0e734-d5ca-4650-a91e-b046a277cff5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b8-b24-l1-315_0-Checkbox']</value>
      <webElementGuid>7193df47-21d6-435f-ac36-b00c79c7dcbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b8-b24-l1-315_0-b1-Control']/span/input</value>
      <webElementGuid>1a5e23d7-0c4c-4c89-8e27-eefabaf877fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/span/input</value>
      <webElementGuid>a10eab18-5b01-49ef-abfe-d1b7b2337f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b8-b24-l1-315_0-Checkbox']</value>
      <webElementGuid>3ae0b0ee-b60b-45ac-80f5-630ee3f3f8ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
