<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Dedication message_b2-b4-TextArea__e92e06</name>
   <tag></tag>
   <elementGuidId>a0b8f889-19da-4efd-951d-8325430e8fd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='b2-b4-TextArea_DedicateMessage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b4-TextArea_DedicateMessage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#b2-b4-TextArea_DedicateMessage</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>27a34b47-193f-4bc4-8d61-675fa429496f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>51c95500-48b1-4100-ae24-1847453cc8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>278df4ef-c0ab-45b6-bc8d-69df02c2ba31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>63db5c6f-1627-4367-9893-4c3ae1378625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b4-TextArea_DedicateMessage</value>
      <webElementGuid>3b6456b2-d518-45e5-aa86-b8e7fcfd4cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b4-TextArea_DedicateMessage&quot;)</value>
      <webElementGuid>8db67a52-af2e-45f7-98fe-9a756f32c989</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b2-b4-TextArea_DedicateMessage']</value>
      <webElementGuid>50feba1e-e8a5-44a8-ac6d-1b646f01669c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b4-b4-FieldContent']/span/textarea</value>
      <webElementGuid>9b312bd8-f4bb-4563-837b-484f423d9fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4d78a471-51de-4ec2-9b27-4b2f97a8787d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b2-b4-TextArea_DedicateMessage']</value>
      <webElementGuid>c0b4d0db-13ae-48ea-9ccb-8088eee32360</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
