<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_0 raised of  4,000_fa-solid fa-ellipsis-vertical</name>
   <tag></tag>
   <elementGuidId>3b6cac6b-47f2-49c5-8f16-4bfe49f5c412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@ktl-id=&quot;btnMoreOptions&quot;]/div/div/div[1]/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa-solid.fa-ellipsis-vertical</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'fa-solid fa-ellipsis-vertical']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>764185fc-f815-42fc-8bcc-f9d937c6cbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-solid fa-ellipsis-vertical</value>
      <webElementGuid>5b69d6d7-8adf-4fb8-8b78-a4b3caa44cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b44-l2-340_0-b10-b1-Content&quot;)/div[@class=&quot;icon-box&quot;]/i[@class=&quot;fa-solid fa-ellipsis-vertical&quot;]</value>
      <webElementGuid>d9f2ce21-f44d-41ef-8bbe-dfb156303cec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b44-l2-340_0-b10-b1-Content']/div/i</value>
      <webElementGuid>5bed347a-dd9f-4072-ae80-eb819077c94c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/i</value>
      <webElementGuid>f733d743-552d-47b1-b0c2-2ec5ea1d177f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
