<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pledge</name>
   <tag></tag>
   <elementGuidId>1c2f1ca2-d07f-4632-a741-85b174f7b316</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b15-Desktop2']//button[text()='Pledge']&#xd;
&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='b2-b15-Desktop2']//button[text()='Pledge']&#xd;
[count(. | //*[@type = 'button' and @ktl-id = 'btnPledge']) = count(//*[@type = 'button' and @ktl-id = 'btnPledge'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd28bc31-ce11-4f8d-942e-0da9d15408cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn OSFillParent</value>
      <webElementGuid>9c385817-3591-4392-bda5-4ccf6c760846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>63dfa1ed-9360-460d-8df2-87db8ebc0c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>btnPledge</value>
      <webElementGuid>731023fd-c6c4-4995-b4d7-b90bfe9353d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pledge</value>
      <webElementGuid>854e20b9-8c99-450f-9cb6-f84fc106cad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='b2-b15-Desktop2']//button[text()='Pledge']&#xd;
</value>
      <webElementGuid>9e061437-a277-472c-ae73-ae427e481cdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[16]</value>
      <webElementGuid>0598c191-8dab-47fc-b2e1-73d829c9f149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b15-l3-129_0-Desktop']/button[3]</value>
      <webElementGuid>9b570840-90b6-43c4-bd9b-afdb467c92b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[1]/following::button[1]</value>
      <webElementGuid>07a34dcf-c4db-4606-a430-4192fd6cf717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donate now'])[1]/following::button[2]</value>
      <webElementGuid>278ac538-bd60-4dcb-8dc7-8f131e9a60c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[2]/preceding::button[1]</value>
      <webElementGuid>d155c174-8310-438f-b073-0b8d0d6c749f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other amount'])[1]/preceding::button[1]</value>
      <webElementGuid>edf755d3-35a7-4ba9-90c7-6ef82b4b3d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pledge']/parent::*</value>
      <webElementGuid>9dd09a08-1373-48c6-ada1-e26a11a6b52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[3]</value>
      <webElementGuid>68c39af6-a525-4544-a784-0805101fa0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Pledge' or . = 'Pledge')]</value>
      <webElementGuid>d4be0d8c-a7f3-43c8-a506-ff3a8f225eba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
