<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Other amountDonateDonate nowAdd to cartPledge</name>
   <tag></tag>
   <elementGuidId>224fa7dc-555a-44f0-bf65-65d9fa3c1808</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b15-$b13']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>800c3832-c01a-40ff-8f20-9436fa337b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading-section scheme-color-sunshine</value>
      <webElementGuid>2cbc610b-e178-45c8-815a-1842804c9574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$Other amount$DonateDonate nowAdd to cartPledge</value>
      <webElementGuid>66b3bc6e-6d5f-4c0a-86b4-ab53e7a99b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b15-$b13&quot;)/div[@class=&quot;color-heading-card&quot;]/div[@class=&quot;heading-section scheme-color-sunshine&quot;]</value>
      <webElementGuid>cc750de0-3303-48d1-98bf-dbd244c3bf56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b15-$b13']/div/div</value>
      <webElementGuid>9871f759-f354-488e-8944-2c15c8c7632b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pledge'])[1]/following::div[6]</value>
      <webElementGuid>6ff897c1-8f9a-439e-9e70-6f8d0d7dd4be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to cart'])[1]/following::div[6]</value>
      <webElementGuid>e757725e-bed6-44e6-b517-7e414e1c0e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div</value>
      <webElementGuid>2567eead-b550-47e7-9ca8-c5de6fc95924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '$Other amount$DonateDonate nowAdd to cartPledge' or . = '$Other amount$DonateDonate nowAdd to cartPledge')]</value>
      <webElementGuid>c2ba1c13-93ba-410c-9cb9-fbaaa7b5d6b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
