<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_I want to donate to (DS) NPO 0001Donati_3ceecc</name>
   <tag></tag>
   <elementGuidId>c9b29330-4b32-4461-a127-d299fec1d351</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b15-b20-$b1']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.layout-modal.medium</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1dc41530-8cf0-4643-ac76-5af85741ceea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>layout-modal medium</value>
      <webElementGuid>b3e38394-7401-4b31-9026-6b26899e8652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I want to donate to (DS) NPO 0001Donations above $10 are eligible for claiming tax deduction.To enjoy this benefit, please sign up and/or login to make the donation. Guest donations are capped at $10,000.Donation amount$Make this a recurring donationRecurring donationYour recurring donation will begin upon successful checkout.Add dedication messageTest question to askCancelAdd to cart</value>
      <webElementGuid>8baf1205-e11b-4f72-8747-232972b43f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b15-b20-$b1&quot;)/div[@class=&quot;layout-modal medium&quot;]</value>
      <webElementGuid>f725d69c-09c5-4827-94e1-91027a92010f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b15-b20-$b1']/div</value>
      <webElementGuid>aeff2d7b-d206-4120-92f9-9db8b2ca8868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>b5b8a4d8-84b2-41d5-a784-36e9a113d632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'I want to donate to (DS) NPO 0001Donations above $10 are eligible for claiming tax deduction.To enjoy this benefit, please sign up and/or login to make the donation. Guest donations are capped at $10,000.Donation amount$Make this a recurring donationRecurring donationYour recurring donation will begin upon successful checkout.Add dedication messageTest question to askCancelAdd to cart' or . = 'I want to donate to (DS) NPO 0001Donations above $10 are eligible for claiming tax deduction.To enjoy this benefit, please sign up and/or login to make the donation. Guest donations are capped at $10,000.Donation amount$Make this a recurring donationRecurring donationYour recurring donation will begin upon successful checkout.Add dedication messageTest question to askCancelAdd to cart')]</value>
      <webElementGuid>31c5d90a-c1bc-47a9-88f6-6520be5fe323</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
