<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Donation amount should not exceed 10,_269761</name>
   <tag></tag>
   <elementGuidId>e76ccb62-7263-4dca-bfcd-ef3b30d29b17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b15-b20-Checkbox1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b15-b20-Checkbox1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0df7b05e-9f10-41b5-a637-0ef990cb2dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>af05b7f9-3368-4e36-96fe-37dd686bb525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d2e67cc2-cf40-4379-88d3-36e79e1f6a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>chkMakeRecurring</value>
      <webElementGuid>db7b60a5-b28e-4756-97ab-04ca941162aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b15-b20-Checkbox1</value>
      <webElementGuid>1f441a97-4b13-46d8-be0d-e0e417c06fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b15-b20-Checkbox1&quot;)</value>
      <webElementGuid>7b2a3eab-b0e9-4f28-9209-3ea010e4bd54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b15-b20-Checkbox1']</value>
      <webElementGuid>673d00c1-9970-49fc-bd8e-acaacabd8069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b15-b20-Recurring']/div/span/input</value>
      <webElementGuid>a39edffc-98fd-4831-8c89-cba660e2ca83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/input</value>
      <webElementGuid>47be1db5-12c6-431f-892a-e7d1d4357998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b15-b20-Checkbox1']</value>
      <webElementGuid>b5695bc5-184a-4797-b9fd-1094483cff35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
