<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Test question to ask_b2-b15-b21-l1-14_8d5a34</name>
   <tag></tag>
   <elementGuidId>1faefc8e-9b11-4bfa-8826-501749aed67b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b15-b21-l1-142_0-Input_Answer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b15-b21-l1-142_0-Input_Answer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b047e453-b93e-47f0-ba0e-955a746bcc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>e671db8f-f6f0-4d0c-93a4-5ad7fbe77062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e79973e3-def3-4ad2-8da3-6f7e941390c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1b8d8998-e0e5-450f-8b8a-826364ddd5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>458e8664-9151-4609-9692-53a9c278e9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inpAnswerQuestion</value>
      <webElementGuid>a82aa68c-2f82-4143-8c33-da97fffeb1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b15-b21-l1-142_0-Input_Answer</value>
      <webElementGuid>2bd3f9e2-cacb-4fb8-a980-be5bd05f470c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b15-b21-l1-142_0-Input_Answer&quot;)</value>
      <webElementGuid>088eb285-634f-4641-a5cb-0beccf04bfa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b15-b21-l1-142_0-Input_Answer']</value>
      <webElementGuid>a7aaf458-8a57-4b05-9773-c9bd987648b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b15-b21-l1-142_0-b10-FieldContent']/span/input</value>
      <webElementGuid>a5710ac0-4be4-4d9c-a005-b3132b49bc34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/input</value>
      <webElementGuid>8a44ff49-e90c-4fec-afe3-9db41ef26d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b2-b15-b21-l1-142_0-Input_Answer']</value>
      <webElementGuid>4a9621b4-1dff-48b3-be3d-fa4141439348</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
