<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Test question to ask_b2-b15-b21-l1-46_e94ed7</name>
   <tag></tag>
   <elementGuidId>8fd8ccf0-267b-44ef-ab33-cf521285c954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b15-b21-l1-463_0-Input_Answer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b15-b21-l1-463_0-Input_Answer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c18d909a-c78b-4b36-b53f-1af02bba5c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>ce0e36c9-a10d-48f5-87c7-c81cdaea83c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a3f83c0-3af9-4e59-9ae6-42c5c83d2b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5fbd65cd-e978-4200-a90a-ec82e1262c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>aa0fef6f-3054-4115-bdab-e5b35317ec6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inpAnswerQuestion</value>
      <webElementGuid>5beec199-5a1d-492c-b457-395f68fa1b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b15-b21-l1-463_0-Input_Answer</value>
      <webElementGuid>e26df8f7-23aa-4467-b056-0e18a1bc4506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b15-b21-l1-463_0-Input_Answer&quot;)</value>
      <webElementGuid>563df4ab-6dae-4f70-ba85-12b9a7187a7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b15-b21-l1-463_0-Input_Answer']</value>
      <webElementGuid>1439c533-a19e-4289-8953-d9368ce3ae26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b15-b21-l1-463_0-b10-FieldContent']/span/input</value>
      <webElementGuid>4da88b53-5fec-48dd-9a25-27846c4b7d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/input</value>
      <webElementGuid>3c9d9645-9aea-43e7-8561-d10a2963888b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b2-b15-b21-l1-463_0-Input_Answer']</value>
      <webElementGuid>54a84402-92c9-46d2-b50b-46c8d64d0ab5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
