<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_31_1</name>
   <tag></tag>
   <elementGuidId>1a301101-845c-4871-8620-d8d0f6c1e130</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='flatpickr-days']//span[contains(@class, 'flatpickr-day') and not(contains(@class, 'flatpickr-disabled')) and @aria-label]&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='flatpickr-calendar-0']//span[@class='flatpickr-day' and text()='[day]']&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7d01b7c5-81a4-4d85-beb4-7be257a944f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flatpickr-day</value>
      <webElementGuid>d97bc78c-9c4b-46aa-8d4c-8cb395b7c2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>December 31, 2024</value>
      <webElementGuid>bafa68ab-6da7-4b1e-8528-7b16af6a5913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fc5b8dda-b2a7-46f9-8e81-6d1f6baaeb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>23355ecb-3c94-48fd-8e0d-f9958e7d0435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='flatpickr-days']//span[contains(@class, 'flatpickr-day') and not(contains(@class, 'flatpickr-disabled')) and @aria-label]&#xd;
</value>
      <webElementGuid>3df01abd-57b1-4ded-bd5a-551f8bad2b01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flatpickr-calendar-0.vndczyz09wn']/div[2]/div/div[2]/div/span[31]</value>
      <webElementGuid>101ff7f9-3488-4bb4-b2f5-e312751908c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::span[31]</value>
      <webElementGuid>8547eb15-a191-49f6-9495-7a879b4e5156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::span[32]</value>
      <webElementGuid>86d33035-d3a2-4982-b151-ad7884e0fd53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test question to ask'])[1]/preceding::span[13]</value>
      <webElementGuid>f1b8f852-89da-4d78-a326-4869579f0b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::span[15]</value>
      <webElementGuid>48dc9cfb-73a9-463e-8fa5-61469aa02263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='31']/parent::*</value>
      <webElementGuid>15676c9f-3f4c-4322-a009-0ee1db67a399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[31]</value>
      <webElementGuid>0c2485d6-193d-49f6-a4ff-8a8e6544f109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '31' or . = '31')]</value>
      <webElementGuid>75ea23cb-6cf3-4ad1-ad2b-bc15f9c1abff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
