<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_31_1_2_3</name>
   <tag></tag>
   <elementGuidId>8b2328d9-dcb5-4166-9c37-e6d83c6abb51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='flatpickr-days']//span[contains(@class, 'flatpickr-day') and not(contains(@class, 'flatpickr-disabled')) and @aria-label]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='flatpickr-days']//span[contains(@class, 'flatpickr-day') and not(contains(@class, 'flatpickr-disabled')) and @aria-label]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9f24b284-c85f-490f-a67f-b50e1a0e2a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flatpickr-day</value>
      <webElementGuid>b6e516b1-6f91-407f-aacf-718ddbe5aa0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>December 31, 2024</value>
      <webElementGuid>022274ad-e68d-44f9-8a40-6b9387097c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>de197daa-b856-4413-9194-8850f89ebcbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>89f5d21c-c683-4cfa-b348-0011aac3f0f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='flatpickr-days']//span[contains(@class, 'flatpickr-day') and not(contains(@class, 'flatpickr-disabled')) and @aria-label]</value>
      <webElementGuid>56a5f5c2-52fd-4136-8b36-a9ddfbd6a057</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flatpickr-calendar-0.4yxc51uq2l']/div[2]/div/div[2]/div/span[31]</value>
      <webElementGuid>2d611e3a-d344-4b4f-b964-be2d14418b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::span[31]</value>
      <webElementGuid>7a5d141c-f255-44cd-b6b5-63e881f70310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fri'])[1]/following::span[32]</value>
      <webElementGuid>152068c6-0840-44d3-b887-b5a8cb18e394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test question to ask'])[1]/preceding::span[13]</value>
      <webElementGuid>8747f816-18ba-4fdc-8d66-ec5de112d769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::span[15]</value>
      <webElementGuid>ff347a86-6200-4cdc-839f-b7a2bcb123ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='31']/parent::*</value>
      <webElementGuid>290ceba0-4f01-43c7-be6b-93e787742b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[31]</value>
      <webElementGuid>c2f785b1-b357-42a6-8e76-9b4f72408dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '31' or . = '31')]</value>
      <webElementGuid>9a3b3613-4d5c-494b-8b75-8f3222870679</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
