<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Results per page_b2-l3-625_0-b42-b1-Con_8a9158</name>
   <tag></tag>
   <elementGuidId>58bce938-ec7a-4dd0-9e43-00da82834469</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='b2-l3-625_0-b42-b1-ContentImage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-l3-625_0-b42-b1-ContentImage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#b2-l3-625_0-b42-b1-ContentImage</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e0b1ef0a-6a81-44a7-aa66-e1df4a9f2b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>giving-image</value>
      <webElementGuid>193a4ea0-70b0-4b44-a458-bf6364995c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/res/GetOpportunityImage/800bcf0f-4ecf-42d9-8bf3-d1b75bb8e334.jpg</value>
      <webElementGuid>ef6891d3-18f6-4587-835c-fe0e70e84753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l3-625_0-b42-b1-ContentImage</value>
      <webElementGuid>873ddd11-a583-4e57-90ba-486dc4a7f5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l3-625_0-b42-b1-ContentImage&quot;)</value>
      <webElementGuid>37d7c479-b6eb-4cd7-b5f8-ffcc7925e24b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='b2-l3-625_0-b42-b1-ContentImage']</value>
      <webElementGuid>d354a7cd-d637-4e94-a563-1672caee514e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-l3-625_0-b42-$b1']/img</value>
      <webElementGuid>cc873ccf-ccf6-406a-a423-c071675fdc5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>a47211d8-cef1-47f1-b7ee-d19e29437f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/res/GetOpportunityImage/800bcf0f-4ecf-42d9-8bf3-d1b75bb8e334.jpg' and @id = 'b2-l3-625_0-b42-b1-ContentImage']</value>
      <webElementGuid>a88a0acf-751a-44ea-bbf6-9d4cfc7ed664</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/res/GetOpportunityImage/5e29a880-cfa7-4a67-929c-25ef5d362424.jpg' and @id = 'b2-l3-625_0-b42-b1-ContentImage']</value>
      <webElementGuid>156db936-ebcf-4f3c-98d5-b8000eec6e1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
