<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rejected_b2-b23-l1-159_14-Checkbox</name>
   <tag></tag>
   <elementGuidId>a666adc4-6a62-4f70-b86b-aa1eafc0a7fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b23-l1-159_14-Checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b23-l1-159_14-Checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7585be1-baff-4509-a060-4219f4accb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1c9d9f77-1e39-4c8e-9afa-947ac063ba53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d57d4c9e-62de-48cd-89e0-e6da639643b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b23-l1-159_14-Checkbox</value>
      <webElementGuid>bb9c3511-d6c6-4c82-864b-e6f4c9ee8433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cf6e6410-9c53-43ec-914e-2672315a7484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b23-l1-159_14-Checkbox&quot;)</value>
      <webElementGuid>1dde7978-055e-4dcd-bcc9-3ef569a22511</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b23-l1-159_14-Checkbox']</value>
      <webElementGuid>ec14ca83-ebf5-474d-ab50-7eebdb036dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b23-l1-159_14-b1-Control']/span/input</value>
      <webElementGuid>d6c109be-41d3-42af-b26e-bdeb340d33f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/span/input</value>
      <webElementGuid>a4f390c3-dab1-42bc-9d00-0c36a6eb6398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b23-l1-159_14-Checkbox']</value>
      <webElementGuid>ee7dec13-85af-48d8-8bd6-35a70d48462b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
