<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_campaign title</name>
   <tag></tag>
   <elementGuidId>158d485e-0c66-4907-9c6c-a61f076a1d9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.text-link > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@ktl-id='divCampaignTable']/table/tbody/tr[1]/td[1]/div/div/div[1]/a&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'lblCampaignTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>039c1df9-bac5-4dcd-8c93-f9fefa56d7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>testing approved campaign name with longer name to test</value>
      <webElementGuid>e3c4d1b7-c712-4b45-90cb-26537df674df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b29-l1_0-468_1-b1-PrimaryText&quot;)/a[@class=&quot;text-link&quot;]/span[1]</value>
      <webElementGuid>4af9a05f-2bd1-46a5-b167-8e9c58c037c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>lblCampaignTitle</value>
      <webElementGuid>795c1e61-c1e4-4924-a10d-012d54fb673c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@ktl-id='divCampaignTable']/table/tbody/tr[1]/td[1]/div/div/div[1]/a&#xd;
</value>
      <webElementGuid>8915bdeb-8639-4b09-8a4f-96c2e1b194e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::span[1]</value>
      <webElementGuid>beb7d918-2899-47c2-a1c4-b9a0e8170fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::span[1]</value>
      <webElementGuid>151f8d75-229a-44ea-9c18-cc557731659f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#97447'])[1]/preceding::span[1]</value>
      <webElementGuid>5bb03692-c9f7-493a-aa20-8b61283676a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/preceding::span[3]</value>
      <webElementGuid>75f26ee1-8fb8-416b-993e-58338943eb1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='testing approved campaign name with longer name to test']/parent::*</value>
      <webElementGuid>496250e6-a58a-4750-9451-f67c92f68572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>579fdb37-a0f0-461f-8a7f-7a33c907d94f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'testing approved campaign name with longer name to test' or . = 'testing approved campaign name with longer name to test')]</value>
      <webElementGuid>f22a7537-ecec-4484-8083-831546135280</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
