<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BackTest ModeTestSG60 SHARESGD60.00</name>
   <tag></tag>
   <elementGuidId>e1cc5d15-0e98-4889-9fcc-0e0991b3dc7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.App-Overview</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3a3f1205-1464-4ccf-8f6a-53a3973ba321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>App-Overview</value>
      <webElementGuid>b973c8da-a54e-4ce4-93ba-c4175ef9691e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BackTest ModeTestSG60 SHARESGD 60.00</value>
      <webElementGuid>238ad290-7439-4187-915e-fa1b4a6bb39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App-Container is-noBackground flex-container justify-content-center&quot;]/div[@class=&quot;App App--singleItem&quot;]/div[@class=&quot;App-Overview&quot;]</value>
      <webElementGuid>aab92f01-967d-4188-b1b8-49a46c70bbc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div</value>
      <webElementGuid>f7733f77-a822-42d8-8a40-7b43ffe857da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div</value>
      <webElementGuid>cb8ae5d0-6c32-4e0e-ad98-6cc0945790b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'BackTest ModeTestSG60 SHARESGD 60.00' or . = 'BackTest ModeTestSG60 SHARESGD 60.00')]</value>
      <webElementGuid>b8682e62-4c8b-4095-9bea-8850cfd38f91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
