<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SGD10.00_SubmitButton-IconContainer</name>
   <tag></tag>
   <elementGuidId>d3855003-5dc5-4540-89f6-9a1c55fde7c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/main/div/form/div/div/div/div[3]/div/div[3]/button/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.SubmitButton-IconContainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2dcb8bff-b941-443a-b3dd-94f3efdc767f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>SubmitButton-IconContainer</value>
      <webElementGuid>a4c4c8c5-1f3d-49c3-a88f-c72b2d5bd589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App-Container is-noBackground App-Container--noAnimation flex-container justify-content-center&quot;]/div[@class=&quot;App App--singleItem&quot;]/div[@class=&quot;App-Payment is-noBackground&quot;]/main[1]/div[@class=&quot;CheckoutPaymentForm&quot;]/form[@class=&quot;PaymentForm-form&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;PaymentForm-confirmPaymentContainer mt4 flex-item width-grow&quot;]/div[@class=&quot;ConfirmPayment&quot;]/div[@class=&quot;flex-item width-12&quot;]/button[@class=&quot;SubmitButton SubmitButton--complete&quot;]/div[@class=&quot;SubmitButton-IconContainer&quot;]</value>
      <webElementGuid>684f27de-de01-4a12-96b9-98dfaa9fb759</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/main/div/form/div/div/div/div[3]/div/div[3]/button/div[3]</value>
      <webElementGuid>d189e5d9-68d4-4fb4-8396-acb85ec3b197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGD 10.00'])[2]/following::div[1]</value>
      <webElementGuid>df25972c-f852-4053-8db7-4b4498cbd5e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms'])[1]/preceding::div[43]</value>
      <webElementGuid>e3171a84-e59d-4613-80e5-99a25b5a3f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div[3]</value>
      <webElementGuid>a721464d-3588-4b19-9163-2a0a89a0ae4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
