<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_system_guest_donornvpc.com</name>
   <tag></tag>
   <elementGuidId>82d337cc-91ed-43d7-807f-efce457e19a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ReadOnlyFormField-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/main/div/form/div/div/div/div/div/div/div/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8f7044c7-81c7-4e1e-bee3-49d455ce571a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ReadOnlyFormField-title</value>
      <webElementGuid>b186dbe6-ab37-49c0-9a05-55f96724c819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>system_guest_donor@nvpc.com</value>
      <webElementGuid>747818bf-0744-4e79-ba61-7df95776c463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App-Container is-noBackground App-Container--noAnimation flex-container justify-content-center&quot;]/div[@class=&quot;App App--singleItem&quot;]/div[@class=&quot;App-Payment is-noBackground&quot;]/main[1]/div[@class=&quot;CheckoutPaymentForm&quot;]/form[@class=&quot;PaymentForm-form&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;App-Global-Fields flex-container spacing-16 direction-column wrap-wrap&quot;]/div[@class=&quot;flex-item width-12&quot;]/div[@class=&quot;ReadOnlyForm ReadOnlyForm--withShadow&quot;]/div[@class=&quot;ReadOnlyFormField-email ReadOnlyFormField&quot;]/div[@class=&quot;ReadOnlyFormField-container&quot;]/div[@class=&quot;ReadOnlyFormField-contentContainer&quot;]/div[@class=&quot;ReadOnlyFormField-content&quot;]/div[@class=&quot;ReadOnlyFormField-titleContainer&quot;]/div[@class=&quot;ReadOnlyFormField-title&quot;]</value>
      <webElementGuid>71378c1d-c654-4f1d-b0a6-a7bec6757a3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/main/div/form/div/div/div/div/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>7d76320f-196e-4dec-be79-5edbeae1ddca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::div[3]</value>
      <webElementGuid>72ed1508-f634-49ab-b7ea-23182a93d885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or'])[1]/following::div[13]</value>
      <webElementGuid>befde94c-1d18-4e18-a53d-99242fe2c019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/preceding::div[2]</value>
      <webElementGuid>8621d809-bf35-4436-ac27-ddda86a8e9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='After submission, you will be redirected to complete next steps securely.'])[1]/preceding::div[16]</value>
      <webElementGuid>21a5dce1-3508-4edc-a53e-be17fab66b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='system_guest_donor@nvpc.com']/parent::*</value>
      <webElementGuid>223bd0a4-ca4d-4a04-b694-dc5a1a298aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>9376fb61-6c0c-4747-83ce-1187954c7232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'system_guest_donor@nvpc.com' or . = 'system_guest_donor@nvpc.com')]</value>
      <webElementGuid>514a6c32-f1c5-42d5-9554-7800692748e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
