<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ronaldo assistanceTheatre of dream04072024</name>
   <tag></tag>
   <elementGuidId>6278c53d-dd45-4a98-a911-e9057005cab6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b8-l4-550_0-b36-Content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b8-l4-550_0-b36-Content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>67893fa4-b5af-46b4-951d-c2baf4f9d99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-card-content-wrapper</value>
      <webElementGuid>0dde946b-882f-46a7-a46b-d56892e15c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b8-l4-550_0-b36-Content</value>
      <webElementGuid>ac7312d3-2f5c-4133-a50b-588dc97d16d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ronaldo assistanceTheatre of dream04/07/2024</value>
      <webElementGuid>ea9752ae-ae99-4d86-be67-1292abd66ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b8-l4-550_0-b36-Content&quot;)</value>
      <webElementGuid>9ec434fd-61fa-4bac-936a-50755195ab63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b8-l4-550_0-b36-Content']</value>
      <webElementGuid>50a5968d-adf7-4be4-b5ad-d29273a0ce04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b8-l4-550_0-$b36']/div/div[4]</value>
      <webElementGuid>20a2d371-d9e4-47c4-bae3-59d880db30e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results per page'])[1]/following::div[17]</value>
      <webElementGuid>b11baa52-0068-4c8c-ad31-1b9f59f15705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[4]</value>
      <webElementGuid>932d71f5-7d2a-4109-a36e-567166c05100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b8-l4-550_0-b36-Content' and (text() = 'Ronaldo assistanceTheatre of dream04/07/2024' or . = 'Ronaldo assistanceTheatre of dream04/07/2024')]</value>
      <webElementGuid>f0c7e759-3b0d-4617-9f84-8dbcdacbfb5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
