<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>0161354f-1afb-4c25-8853-51d703aa8694</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='b1-b1-Header2']/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>317b08a7-2acf-4405-ae1d-6d70ed650ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/auth/img/NVPC_Resources.GivingSgLogoBlue.svg?JgUtt3jq0bFB56t23xbWZg</value>
      <webElementGuid>0defd0f9-11f2-4982-9fe6-faf0eef4f13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-b1-Header2&quot;)/div[@class=&quot;header-top&quot;]/div[@class=&quot;header-content ThemeGrid_Container&quot;]/div[@class=&quot;header-form-logo&quot;]/img[1]</value>
      <webElementGuid>752f10fa-36fb-465f-9483-36f13b2f74c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='b1-b1-Header2']/div/div/div[2]/img</value>
      <webElementGuid>c8ce157c-2071-4f34-a3aa-876098fba65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>5fed08a9-dba2-4ddc-8d13-9201449b4711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/auth/img/NVPC_Resources.GivingSgLogoBlue.svg?JgUtt3jq0bFB56t23xbWZg']</value>
      <webElementGuid>4f2dedcf-fbae-4ecf-9fdf-d9a837e827fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
