<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Preview_1_2</name>
   <tag></tag>
   <elementGuidId>ca24a589-6dff-4f52-b702-69099277ceba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='b2-b10-l1_0-100_0-PreviewGroundUpDetail']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'btnPreview-ReviewTab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b10-l1_0-100_0-PreviewGroundUpDetail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b4c5c570-719a-4e3f-89c2-9a86d0672f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>922cd059-12eb-4d03-b643-c4a3114438ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>btnPreview-ReviewTab</value>
      <webElementGuid>d71c78c8-dff5-4850-8c54-a8db4ddef623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b10-l1_0-100_0-PreviewGroundUpDetail</value>
      <webElementGuid>bebc8340-728d-4d23-897e-89b7643cd9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preview</value>
      <webElementGuid>9c45f5ea-0b03-46a7-861b-3a89f282d5bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b10-l1_0-100_0-PreviewGroundUpDetail&quot;)</value>
      <webElementGuid>b2e36552-01a7-46e0-8299-868d227a4968</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='b2-b10-l1_0-100_0-PreviewGroundUpDetail']</value>
      <webElementGuid>89abdd34-9694-44f2-8c08-7ab1d23539c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b10-l1_0-100_0-b1-Items']/a</value>
      <webElementGuid>8b6b77a1-067f-4d71-ae38-117e63d84f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ethan Org 1'])[2]/following::a[1]</value>
      <webElementGuid>bff4474a-2682-4c2c-b8e5-fb9b77cd16b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ethan GU 2'])[1]/following::a[1]</value>
      <webElementGuid>dcdad90e-dc25-4f0c-ae86-887dccd2ee2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approve'])[1]/preceding::a[1]</value>
      <webElementGuid>d220cf2b-b5f2-4496-a12a-f82583dfdfaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>05e9581e-f313-4ac4-88e9-a187d9ff7d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>06ef0c3a-b7b0-4b2d-aa5b-1bc43c091a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @ktl-id = 'btnPreview-ReviewTab' and @id = 'b2-b10-l1_0-100_0-PreviewGroundUpDetail' and (text() = 'Preview' or . = 'Preview')]</value>
      <webElementGuid>672e517f-f4a2-4cc3-9824-1ddd94303b04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
