<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Reject registration</name>
   <tag></tag>
   <elementGuidId>8bf5bc80-f6e3-4a31-a5a0-0862f4a157fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b10-b8-Title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b10-b8-Title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>713dd321-e1f6-4f19-994f-f22b9500485e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading2</value>
      <webElementGuid>7791683a-0869-4ced-8bd6-350115857e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b10-b8-Title</value>
      <webElementGuid>7f77d329-3d95-4c9e-9efc-72d7c17d1a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reject registration</value>
      <webElementGuid>03d9c0a1-c300-4b8c-a815-c3ea12b384ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b10-b8-Title&quot;)</value>
      <webElementGuid>87406a85-ceab-4193-b460-00fae25d8e50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b10-b8-Title']</value>
      <webElementGuid>6e9b4e82-9cc9-41a5-9f5b-00653a024fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b10-$b8']/div/div</value>
      <webElementGuid>ce6e2b32-3706-4400-842f-0aae9faa9723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='items'])[2]/following::div[12]</value>
      <webElementGuid>0bd78b7c-df55-4710-80bf-36312065abcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Groundup admin will receive a notification on the rejection reason.'])[1]/preceding::div[1]</value>
      <webElementGuid>80633fcc-2fe7-4e69-8d51-3e34b9d6acb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rejection reason'])[1]/preceding::div[2]</value>
      <webElementGuid>f4e8cf00-eec2-4c46-9556-63af51d0f7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reject registration']/parent::*</value>
      <webElementGuid>63eda5c3-0be7-4291-8769-5f209b30a198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>e6d9575e-6336-4b52-8a81-5395902553bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b10-b8-Title' and (text() = 'Reject registration' or . = 'Reject registration')]</value>
      <webElementGuid>7e444dc9-3017-4685-a691-7aec67eef430</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
