<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Ethan Org 1_fa-solid fa-ellipsis-vertical_1_2_3</name>
   <tag></tag>
   <elementGuidId>60cd3489-1b7d-4422-a8f5-d2823d1cb774</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b10-l1_0-85_0-b1-b1-Content']/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa-solid.fa-ellipsis-vertical</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5ab848f6-da19-4ac3-a28d-c82ab8d0fc6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-solid fa-ellipsis-vertical</value>
      <webElementGuid>37d50e41-8f1a-47fa-8847-96e9f356330c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b10-l1_0-85_0-b1-b1-Content&quot;)/div[@class=&quot;icon-box&quot;]/i[@class=&quot;fa-solid fa-ellipsis-vertical&quot;]</value>
      <webElementGuid>40e1f391-daba-4c0d-9fd8-2ab0fbaaff6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b10-l1_0-85_0-b1-b1-Content']/div/i</value>
      <webElementGuid>6ff96c2a-62e3-4c61-b22c-d554e352bfbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/div/div/div/div/i</value>
      <webElementGuid>7b83b71c-6de1-4420-bad0-789b65c72256</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
