<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View your campaign</name>
   <tag></tag>
   <elementGuidId>4b3c7e42-4d48-4035-b7c7-5d15fa525810</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.display-flex.padding-top-xs.text-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b1-PageDescription']/div/div[2]/a/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'lnkViewCampaign']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>58d683a1-daa2-44d7-956d-0e79bdebf533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>display-flex padding-top-xs text-link</value>
      <webElementGuid>9c7c6d6a-fbfe-486d-ad32-71aa1eb05513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View your campaign</value>
      <webElementGuid>a3c1e9cb-ddda-428d-94dd-fd877aecac1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-PageDescription&quot;)/div[@class=&quot;display-flex&quot;]/div[@class=&quot;margin-left-base&quot;]/a[1]/div[@class=&quot;display-flex padding-top-xs text-link&quot;]</value>
      <webElementGuid>c6b45d65-d5d2-4ff1-88af-2603888969bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>lnkViewCampaign</value>
      <webElementGuid>bdb8c1c0-bf4b-4e3c-9d27-0d4cda6a208a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-PageDescription']/div/div[2]/a/div</value>
      <webElementGuid>d215ae89-5d2c-48f0-9cbb-cf02ff3351fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::div[2]</value>
      <webElementGuid>61ee85b0-ffb0-4f50-81f8-e84a4ef408d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testing approved campaign name with longer name to test'])[2]/following::div[9]</value>
      <webElementGuid>f90bc543-fad4-4a6d-8631-2499c7a5298e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. of donations'])[1]/preceding::div[5]</value>
      <webElementGuid>0c98bbd9-a6b0-4620-abb8-08748c8d0b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View your campaign']/parent::*</value>
      <webElementGuid>e8691c35-e9bf-403c-adc6-abf8feeb7cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/a/div</value>
      <webElementGuid>ce5e5560-4f7a-4dc6-85d4-8f5c441033ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'View your campaign' or . = 'View your campaign')]</value>
      <webElementGuid>a70d0fea-9d64-49c2-a984-043594a62d8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
