<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Search charities or campaigns_icon fa fa-_62f74a</name>
   <tag></tag>
   <elementGuidId>a918994d-c69a-411c-8cc4-b37dc5bf2a61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@ktl-id='btnSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-search.fa-1x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>129a1858-7b04-4f2f-bb14-e34da1a64c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-search fa-1x</value>
      <webElementGuid>0d7b849b-db0d-46a3-986a-20375759ab17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b3-Button&quot;)/button[@class=&quot;btn btn-primary&quot;]/i[@class=&quot;icon fa fa-search fa-1x&quot;]</value>
      <webElementGuid>d01f299f-1f2d-4f28-81cf-1aa91b09068f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>a011f061-3c50-4b46-afa8-eb709c8abd84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
