<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Friday</name>
   <tag></tag>
   <elementGuidId>d1517f59-a5f0-4142-8b0c-3a3c56afe22f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b6-b12-b16-l1-504_4-Checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@ktl-id='divSelectDays']/div/div/div[5]/div/div[1]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>154a43f8-da40-4f32-8a06-0dde246db0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7dab6b04-99a0-45d9-be5d-8c588db2e629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ccc99aa0-9a8a-4ac7-9b90-9784a559df56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b6-b12-b16-l1-504_4-Checkbox</value>
      <webElementGuid>b47e96c4-b09d-47b3-9389-c63934ff6c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b6-b12-b16-l1-504_4-Checkbox&quot;)</value>
      <webElementGuid>47a55d81-e0bf-4855-9962-35486de4c51b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b6-b12-b16-l1-504_4-Checkbox']</value>
      <webElementGuid>99d128a9-8771-4d23-94b4-879b521e2c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b6-b12-b16-l1-504_4-b1-Control']/span/input</value>
      <webElementGuid>2e662f0c-69f5-46e8-8f32-ad67c668b012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/span/input</value>
      <webElementGuid>d310790d-1e15-4c0e-aec6-a86ee18a27d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b6-b12-b16-l1-504_4-Checkbox']</value>
      <webElementGuid>b0f0eb2a-5602-444c-b87c-0f425455a2ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
