<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Monday</name>
   <tag></tag>
   <elementGuidId>2503bfa1-3d48-4fde-b7d8-563508b7cd20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b6-b12-b16-l1-504_0-Checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@ktl-id='divSelectDays']/div/div/div[1]/div/div[1]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>654695b0-ff88-43c3-9cfd-9d8374e210dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>82c1e872-eb8e-49a9-affd-518b89def1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8fda2ca5-9d55-48aa-bc43-7fbb5db42cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b6-b12-b16-l1-504_0-Checkbox</value>
      <webElementGuid>681e0fd4-d544-47f3-a8f5-5439217020e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b6-b12-b16-l1-504_0-Checkbox&quot;)</value>
      <webElementGuid>fbb94bbb-e6d4-49d6-b538-3efdf840d72b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b6-b12-b16-l1-504_0-Checkbox']</value>
      <webElementGuid>39b87c72-0ada-49bf-9df7-a5229f1bb275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b6-b12-b16-l1-504_0-b1-Control']/span/input</value>
      <webElementGuid>ea1e7104-c140-4b12-8070-c59bd5adbf4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/span/input</value>
      <webElementGuid>be339b5f-db04-4f8a-b8fe-d31b47e97ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b6-b12-b16-l1-504_0-Checkbox']</value>
      <webElementGuid>bbb301bc-2359-43e3-b12d-5af9555fa007</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
