<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Dedication message_b2-b15-b20-Text_bf4ba3</name>
   <tag></tag>
   <elementGuidId>709a2209-08b9-4e62-954b-0f04071e3de1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b15-b20-TextArea_DedicationMessage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='b2-b15-b20-TextArea_DedicationMessage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>31f21b4f-ec2a-4134-99ac-73d8a6392613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>eeb95bb1-99b1-49e2-8943-7a47c1af537d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>7a9e9f3b-2289-4058-8ad9-95d90054565c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>2a3aaf65-1966-41f5-aca2-d337c608397b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b15-b20-TextArea_DedicationMessage</value>
      <webElementGuid>7a059c62-f21a-4677-8291-a3dcaa7cdd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b15-b20-TextArea_DedicationMessage&quot;)</value>
      <webElementGuid>e834e676-5941-4807-94d4-2b94cad2a57a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b2-b15-b20-TextArea_DedicationMessage']</value>
      <webElementGuid>7cdc1917-a7c7-4d6c-a553-fb95b1672317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b15-b20-b10-FieldContent']/span/textarea</value>
      <webElementGuid>b3e78c31-bfc4-4aa3-a387-9c968e4079c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>df54b3af-77d0-4932-a6c0-dfa082ad9d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b2-b15-b20-TextArea_DedicationMessage']</value>
      <webElementGuid>cd66493e-80c3-4cb5-a3cc-ec6284dbc827</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
