<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown</name>
   <tag></tag>
   <elementGuidId>972af8e8-e339-4d28-b601-5ea7f826aeba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b4-b2-Dropdown_Type']/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'divSelectType-Dropdown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dropdown-display</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>471f2f8a-e243-485c-9803-105f516181f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display</value>
      <webElementGuid>40ab090e-e50f-427e-8520-2e3725fe0e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-</value>
      <webElementGuid>b3b0e7ec-9925-48bf-9c68-82e203d2ced4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b2-Dropdown_Type&quot;)/div[@class=&quot;dropdown-display&quot;]</value>
      <webElementGuid>6facecfe-6d28-4bad-acc3-b94ceeba2f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>divSelectType-Dropdown</value>
      <webElementGuid>0e03b237-22ca-4f01-a250-319c4c43ecd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b2-Dropdown_Type']/div</value>
      <webElementGuid>2ca87048-5766-4cde-9e01-03515b07d6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select type'])[1]/following::div[5]</value>
      <webElementGuid>fc443d1f-9f57-4ca4-ad8f-e35f0f46583c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organisation name'])[1]/following::div[13]</value>
      <webElementGuid>912326d9-7102-4b50-a241-dad53b19dce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact number'])[1]/preceding::div[2]</value>
      <webElementGuid>0f6f55a1-d466-4d13-a00d-34eeba51d89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div</value>
      <webElementGuid>a3ab24f3-d078-493d-a0e2-eeb7cf14201a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '-' or . = '-')]</value>
      <webElementGuid>ba94aa3c-7ec5-44ae-b487-1d3d2406ae45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
