<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Password_icon fa fa-eye fa-1x</name>
   <tag></tag>
   <elementGuidId>357d26aa-3371-4e7a-9966-041cc55b9898</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b4-b4-b17-b1-Icon']/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-eye.fa-1x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ff600f1c-9e2d-4f3e-a0ca-c8a1d6b0dec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-eye fa-1x</value>
      <webElementGuid>681d6ea4-f010-4f4f-bb9c-dbdf289d9903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b4-b17-b1-Icon&quot;)/a[1]/i[@class=&quot;icon fa fa-eye fa-1x&quot;]</value>
      <webElementGuid>39c4f2d7-67a1-43df-917f-f5322747412e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b4-b17-b1-Icon']/a/i</value>
      <webElementGuid>d9a293ba-4be6-41a9-9c1d-178ef96a7d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>b7c60fa4-f103-4eba-a7d3-a227fba1e1cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
