<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Work email_b4-b3-Input_Email</name>
   <tag></tag>
   <elementGuidId>0b406bac-3984-4df7-a07f-b8f18507e63e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b4-b3-Input_Email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b4-b3-Input_Email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Work email&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce9222a2-0616-4000-89a3-22add7ae24da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>6d6107ba-bab2-41c8-b2bd-a0b645d83b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>135aae8e-e9db-4b08-9d00-417353bbf707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0ffd70e5-2b9d-42ef-80dd-0c5539b92a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>b4-b3-Input_Email_DescribedBy</value>
      <webElementGuid>a3711ec0-9e84-4b11-a2d3-bc92e4dcc227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>7a7fa26a-0e2c-4f64-b34d-06eb1206f1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-b3-Input_Email</value>
      <webElementGuid>0f9a7ca3-6377-4801-a6d5-bb59c7ed2c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b3-Input_Email&quot;)</value>
      <webElementGuid>a34af09c-821f-4c7e-9851-94a74d5cb02a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b4-b3-Input_Email']</value>
      <webElementGuid>93b631ef-28d6-41f0-bef5-3413ba0e0766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b3-b15-FieldContent']/span/input</value>
      <webElementGuid>8575190b-6812-424f-9ee3-27eaa4f42f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/span/input</value>
      <webElementGuid>400c6f70-524b-471f-9879-0879e95201ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'b4-b3-Input_Email']</value>
      <webElementGuid>11f2dadc-1411-4bd2-9f21-f9962fa7c9cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
