<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unit_b4-b2-Input_Unit</name>
   <tag></tag>
   <elementGuidId>eabd8d1f-fa6d-4ac4-8cd9-0930b1a7fc8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b4-b2-Input_Unit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b4-b2-Input_Unit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Floor#-Unit$/ >> internal:role=textbox >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd877764-25a7-43e9-b047-cc74a8aa5462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>fc68c309-7abc-4541-9fc9-901580b20fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a10debc7-8955-430c-ba60-4bbafa2a190b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4a861644-1e1c-406e-a3d2-3392962369b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>b4-b2-Input_Unit_DescribedBy</value>
      <webElementGuid>4eb18909-318d-44fc-9430-b7106fc632a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-b2-Input_Unit</value>
      <webElementGuid>542f2d44-0872-4c32-b3ad-f442333c9a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b2-Input_Unit&quot;)</value>
      <webElementGuid>d8e8935b-1696-4ef5-b4f5-5da35d96355c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b4-b2-Input_Unit']</value>
      <webElementGuid>c589961f-4264-4416-ad0c-0c69a5dd5543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b2-b12-UnitInput']/span/input</value>
      <webElementGuid>27a48db0-99eb-4ec6-a26f-f752608e79c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/div[3]/div/span/input</value>
      <webElementGuid>efc9b29d-c1bb-4bc1-9c3f-4e4139759548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b4-b2-Input_Unit']</value>
      <webElementGuid>af4e83e9-1f85-4645-b0ad-8579f661aeb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
