<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unit_b4-b2-Input_Unit</name>
   <tag></tag>
   <elementGuidId>8fda6ba0-039e-446a-9c79-84ae2832e096</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b4-b2-Input_Unit']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'inpUnitNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b4-b2-Input_Unit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e97ef0b5-5951-435b-b114-e5b328c522ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>54ed11d9-0d56-4495-b97b-1965f2dfe178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>688cdd8e-e4d9-45da-b704-6680b4b3e7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ec0fa2d2-033b-4c07-9a80-daff1cba16d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inpUnitNumber</value>
      <webElementGuid>e0651d2f-0155-42f4-8549-562c3c568b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-b2-Input_Unit</value>
      <webElementGuid>0e6f51f9-2c68-4b03-90dd-fa217354f392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b2-Input_Unit&quot;)</value>
      <webElementGuid>37d28f6b-2ca0-4f1b-8005-d6f618ed0abe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b4-b2-Input_Unit']</value>
      <webElementGuid>31447801-a394-494b-94a1-061e0ae1cfb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b2-b12-UnitInput']/span/input</value>
      <webElementGuid>056d2cac-fd9e-42d5-b2df-bb48adc70ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/div[3]/div/span/input</value>
      <webElementGuid>5b7bfbcb-aa54-48bf-a5e8-7976f7acfd20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b4-b2-Input_Unit']</value>
      <webElementGuid>68d7b9b8-72bb-4b10-986c-e15479550cb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
