<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Upload file</name>
   <tag></tag>
   <elementGuidId>d22eb261-5f89-4be6-986e-0bac300db5dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b4-b3-b7-UploadWidget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='b4-b3-b7-UploadWidget']/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label >> internal:has-text=&quot;Upload file&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f0ac1eae-a121-4972-81db-763b7b79a873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-small btn-primary</value>
      <webElementGuid>b85187d4-7e9c-41f4-8cf1-1d712effec5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.pdf</value>
      <webElementGuid>707000d3-45fd-4ba5-a3de-7f0494527303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-b3-b7-UploadWidget</value>
      <webElementGuid>41c11904-17f8-4bd2-b3b3-f1988d2d166c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload file</value>
      <webElementGuid>23870927-a0d7-4ef8-b318-6391bca8e69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b3-b7-UploadWidget&quot;)</value>
      <webElementGuid>b7be8f5e-522f-4213-8d6d-fa53ccecfeff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='b4-b3-b7-UploadWidget']/input</value>
      <webElementGuid>94b7632a-154d-4239-bd1b-d15e272a353e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b3-Upload_LOA_File']/div/div[3]/span/label</value>
      <webElementGuid>cfcedbac-8bf8-4adf-878d-f351cbbd753b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The form is valid for 3 months from the date signed off by the bank.Maximum file size 5MB'])[1]/following::label[1]</value>
      <webElementGuid>ca89bcca-5c5b-4682-b3a5-1dafce6be5b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Letter of Authorisation (LOA)'])[1]/following::label[1]</value>
      <webElementGuid>fa831694-6015-44ed-a7eb-4741cff4f0eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/preceding::label[1]</value>
      <webElementGuid>4fbf1947-3508-45a5-881b-6f97a55b4e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/label</value>
      <webElementGuid>f67a1d99-2edf-48fd-b83b-0364d4303347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'b4-b3-b7-UploadWidget' and (text() = 'Upload file' or . = 'Upload file')]</value>
      <webElementGuid>99849464-d87e-4389-95d7-b8f99da8ee39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
