<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_HomeCampaignsOpportunitiesPartnershipsM_926ffd</name>
   <tag></tag>
   <elementGuidId>f45b504a-1016-45b6-b478-fdea342a3c61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-b1-MainMenu']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.list.list-group.OSFillParent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b54505e1-c9f9-40a5-b6fe-0b4d458ccdfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list list-group OSFillParent</value>
      <webElementGuid>def322a3-278c-4560-8af7-c8b6cde3b47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disable-virtualization</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>95d9d144-8d89-4332-9d83-44d6f3bb6d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>btnMenuItems</value>
      <webElementGuid>ef21f80c-3484-45f8-b850-328b650d5e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HomeCampaignsOpportunitiesPartnershipsMembersEmployeesAPIsReportsAudit log</value>
      <webElementGuid>fc643775-185e-45a9-a4cc-db50b70524d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-b1-MainMenu&quot;)/div[@class=&quot;list list-group OSFillParent&quot;]</value>
      <webElementGuid>3c06ebe2-e6f3-4e6e-9072-02bcd1dd7ad5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-b1-MainMenu']/div</value>
      <webElementGuid>22ee373f-9d50-444f-996d-9cb4957eeb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact us'])[1]/following::div[4]</value>
      <webElementGuid>6f8b20bb-dfeb-46bd-9243-bf55bc76c145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[1]/following::div[4]</value>
      <webElementGuid>fd75dcea-d849-4ccd-969f-161123fc7ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>4e394d65-cfb5-4244-8c0a-7987e84ee70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'HomeCampaignsOpportunitiesPartnershipsMembersEmployeesAPIsReportsAudit log' or . = 'HomeCampaignsOpportunitiesPartnershipsMembersEmployeesAPIsReportsAudit log')]</value>
      <webElementGuid>ae91b9bb-5112-4b42-a32d-9fa6301d3341</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
