<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Fundraisers campaigns</name>
   <tag></tag>
   <elementGuidId>f2621036-cd62-4053-885d-75ad58dc25e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'btnFundraisersCampaign']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.hide-if-phone.ThemeGrid_MarginGutter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>52046a61-3028-4f63-a766-cac09820d0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn hide-if-phone ThemeGrid_MarginGutter</value>
      <webElementGuid>9f0ad494-a11c-4bab-9f5d-a40ddd5f4aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e71ca552-64d8-4cd5-b7bb-334fcb775189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>btnFundraisersCampaign</value>
      <webElementGuid>65d38867-d311-4579-8ea4-f243a43c5fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fundraiser’s campaigns</value>
      <webElementGuid>f1577216-d23c-4fc5-994a-b59031242400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-Actions&quot;)/div[@class=&quot;display-flex column-gap-s&quot;]/button[@class=&quot;btn hide-if-phone ThemeGrid_MarginGutter&quot;]</value>
      <webElementGuid>a5c5e79e-c5d7-4f4b-9045-dbf60e524a92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>fea8d3a0-821d-4c0d-8fd6-02bcf1e215cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-Actions']/div/button[2]</value>
      <webElementGuid>68b25b3f-a088-4fb1-aa04-ac3edfc9e032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaigns'])[3]/following::button[2]</value>
      <webElementGuid>1ad1b6f1-eb97-4b22-b0a5-5b835e1c200a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaigns'])[2]/following::button[2]</value>
      <webElementGuid>0dacf9a4-3783-450d-9d58-fa9dcf7ee648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create campaign'])[1]/preceding::button[1]</value>
      <webElementGuid>a10acec7-fed6-4a21-a928-36ff46eabc43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View and manage your campaigns from this page'])[1]/preceding::button[2]</value>
      <webElementGuid>3199586b-926c-49b5-a2d4-9f646fbf83ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fundraiser’s campaigns']/parent::*</value>
      <webElementGuid>e7d38552-8dfc-44af-b92e-fbbc4334cb2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>f556e344-e20b-481a-934d-6c2e8b62564b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Fundraiser’s campaigns' or . = 'Fundraiser’s campaigns')]</value>
      <webElementGuid>d8be3c6b-b1b4-447d-96a9-21040fb484f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
