<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_rajeevmarriott.dk.dev_icon-box</name>
   <tag></tag>
   <elementGuidId>4bd228f8-809c-40f5-b1c7-0d3dd8c9a61d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b6-b6-l1_0-347_0-b5-b1-Content']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b6-b6-l1_0-347_0-b5-b1-Content > div.icon-box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7ca36fd6-1c1a-40df-b212-c58edf556994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-box</value>
      <webElementGuid>f0855d45-8b1f-4b02-b27c-0f3b0f967066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b6-b6-l1_0-347_0-b5-b1-Content&quot;)/div[@class=&quot;icon-box&quot;]</value>
      <webElementGuid>e725d259-7e68-45b8-b943-dd53f5d3e265</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b6-b6-l1_0-347_0-b5-b1-Content']/div</value>
      <webElementGuid>cc6ea512-a103-4c8a-b6e7-b451cb408e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rajeev@marriott.dk.dev'])[1]/following::div[6]</value>
      <webElementGuid>135594ae-0bd9-491f-bc25-6d3f0d52c18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rajeev Menon'])[1]/following::div[7]</value>
      <webElementGuid>c80714ce-9a05-47d5-b58f-7dd1c26772d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review'])[1]/preceding::div[2]</value>
      <webElementGuid>0aec8b9e-d7b3-4587-afa9-e73788d57e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approve'])[1]/preceding::div[12]</value>
      <webElementGuid>bde4857e-1da8-418a-a716-6a85def9c7c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div/div/div/div/div</value>
      <webElementGuid>d9d05ff0-e332-4879-917d-1cd37ec40925</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
