<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1st campaign request</name>
   <tag></tag>
   <elementGuidId>f2de5d2d-f079-4f05-913b-b7afef95572e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@ktl-id='divFundraiserCampaignTable']/tbody/tr[1]/td[5]/div/div/div/div/div[1]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;b6-b6-l1_0-807_0-b5-b1-Content&quot;)/div[@class=&quot;icon-box&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b6-b6-l1_0-807_0-b5-b1-Content > div.icon-box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f667d8c4-531f-4665-8733-e5c74d9b63bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-box</value>
      <webElementGuid>75431292-f278-49e7-baae-f7b4f678f849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b6-b6-l1_0-807_0-b5-b1-Content&quot;)/div[@class=&quot;icon-box&quot;]</value>
      <webElementGuid>e066fa6a-680f-4ed0-b4a6-9ec8a8ec30db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b6-b6-l1_0-807_0-b5-b1-Content']/div</value>
      <webElementGuid>4b511f6c-768a-407e-b183-fa12a0a043bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rajeev@marriott.dk.dev'])[1]/following::div[6]</value>
      <webElementGuid>c40a9d5d-90ef-4aaf-a277-6338d61fa444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rajeev Menon'])[1]/following::div[7]</value>
      <webElementGuid>fd9bc972-74de-4b1e-b64a-8feba1b335d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review'])[1]/preceding::div[2]</value>
      <webElementGuid>d722737d-5b4c-466f-8f15-dadbee75df54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approve'])[1]/preceding::div[12]</value>
      <webElementGuid>afa696eb-305e-4c91-9545-a419ca6067a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div/div/div/div/div</value>
      <webElementGuid>fc0bc915-5f00-4bb3-a064-76bc82144db7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
