<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ORGANISATIONS</name>
   <tag></tag>
   <elementGuidId>f390f2b2-d099-4869-8725-8b83ece28a53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;0.68b5auwybf&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='0.68b5auwybf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca8c08de-cfed-4136-97e2-02815a25e40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-tabs__header-item</value>
      <webElementGuid>790ad5a5-d95a-40fd-b094-dbc43e7eca89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>0.68b5auwybf</value>
      <webElementGuid>2c8f7cc4-a8aa-4969-955c-27f23083338a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>80ac23aa-aea3-4967-8383-065a98939cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>c0908dea-b84a-40d1-9fdf-fed89faff8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5f144770-50da-41fd-942a-acbbab714c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3239a311-390a-4f87-8ceb-9ddfeef33866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>b2-$b9</value>
      <webElementGuid>cc9d458d-14d4-4ab2-a435-ab14e0632050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ORGANISATIONS</value>
      <webElementGuid>d0fdbb1b-1948-4c36-862e-ad3ef713b24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-$b5&quot;)/button[@class=&quot;osui-tabs__header-item&quot;]</value>
      <webElementGuid>bed110d7-e0f1-40ee-8520-69ca8b6b6960</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='0.68b5auwybf']</value>
      <webElementGuid>18d31832-c5b2-445f-abd8-dbf156a241af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-$b5']/button</value>
      <webElementGuid>0a979a7c-0051-467e-a41b-5fce1dba0da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHARITIES'])[1]/following::button[1]</value>
      <webElementGuid>8a92df4e-8c35-47b9-b4be-1dade9b34e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search organisations'])[1]/following::button[3]</value>
      <webElementGuid>39e35d4d-7965-4cd6-8ccb-6b6ab8b74c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GROUNDUPS'])[1]/preceding::button[1]</value>
      <webElementGuid>4f850a21-8c24-45ed-9df1-858d993f843f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/div[2]/button</value>
      <webElementGuid>4252bdbf-ef9e-420a-a2e5-f89ee4637b25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = '0.68b5auwybf' and (text() = 'ORGANISATIONS' or . = 'ORGANISATIONS')]</value>
      <webElementGuid>acd0ad46-9157-4369-b5f2-8492ffbe3a20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
