<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_GROUNDUPS</name>
   <tag></tag>
   <elementGuidId>05567f6c-5761-45cd-8778-f81612177f6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;0.pdinszfqqf8&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='0.pdinszfqqf8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d22873ed-74be-4f5d-a2aa-57d3337bc388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-tabs__header-item</value>
      <webElementGuid>f80988e9-6282-4668-948d-c02f4be78a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>0.pdinszfqqf8</value>
      <webElementGuid>3bee40d3-5e7b-4bbe-a9e9-ab05c2168487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a20b53a2-16ee-483b-9597-64bc2319dcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>90672d54-723e-474a-8332-a3d9d6ceb63e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>886629df-0964-45d2-8ec2-2c4c521d5f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6dda95a9-045a-4820-b009-13f258d60aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>b2-$b11</value>
      <webElementGuid>68ec47b8-ddff-4da1-b78b-8abb5fd09ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GROUNDUPS</value>
      <webElementGuid>cfc5a732-722c-4eef-bc3c-8fbcb546c2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-$b6&quot;)/button[@class=&quot;osui-tabs__header-item&quot;]</value>
      <webElementGuid>bddbe983-a7e0-43a0-9267-01ae918b0e7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='0.pdinszfqqf8']</value>
      <webElementGuid>2964ba98-9b31-4475-a947-28cebe20f4ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-$b6']/button</value>
      <webElementGuid>eefcfa59-ca9b-46c9-a756-8edfd49b6178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORGANISATIONS'])[1]/following::button[1]</value>
      <webElementGuid>6c6868f6-791d-44a9-ac0f-e0b40bbd3f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHARITIES'])[1]/following::button[2]</value>
      <webElementGuid>3392695c-487f-4daf-9c4d-2e4d6ca81df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Causes'])[1]/preceding::button[1]</value>
      <webElementGuid>80b08485-9edd-40ee-89ee-444b5ff62d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>d42315c8-12c2-4ffd-a936-36976e08fc67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = '0.pdinszfqqf8' and (text() = 'GROUNDUPS' or . = 'GROUNDUPS')]</value>
      <webElementGuid>5f2dc4a4-c1ac-450e-8b67-6c817a63fda7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
