<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Fawwazs NPO 11Lorem ipsum dolor sit ame_586fc7</name>
   <tag></tag>
   <elementGuidId>9a13744f-1804-4f9e-84eb-24879f279cff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b8-l5-416_0-b15-Content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b8-l5-416_0-b15-Content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7898dfe9-2c23-4a4b-a0ac-e15bf8db1591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-card-content-wrapper</value>
      <webElementGuid>ffbc4751-e372-444e-a556-5ad64b89f8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b8-l5-416_0-b15-Content</value>
      <webElementGuid>2ae9a3ae-92c3-43ec-bb84-3d9fef74b26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fawwaz's NPO 11Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec...AnimalsCommunity developmentHealthcareSports</value>
      <webElementGuid>e9a4c761-db4a-4837-8507-f2bcecf5c928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b8-l5-416_0-b15-Content&quot;)</value>
      <webElementGuid>0da9e1f8-bd8a-446f-9f4b-0268bf131d83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b8-l5-416_0-b15-Content']</value>
      <webElementGuid>438652b2-550b-4d78-9488-0c5bb33ce42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b8-l5-416_0-$b15']/div/div[4]</value>
      <webElementGuid>e79173d3-426d-4c9e-9a67-b8cc76b79042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results per page'])[1]/following::div[14]</value>
      <webElementGuid>863e0d55-ea52-42a9-b043-142714edf464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[4]</value>
      <webElementGuid>9a64f7ba-42cc-4850-8182-b0eb320c9156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b8-l5-416_0-b15-Content' and (text() = concat(&quot;Fawwaz&quot; , &quot;'&quot; , &quot;s NPO 11Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec...AnimalsCommunity developmentHealthcareSports&quot;) or . = concat(&quot;Fawwaz&quot; , &quot;'&quot; , &quot;s NPO 11Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec...AnimalsCommunity developmentHealthcareSports&quot;))]</value>
      <webElementGuid>c56a2990-0b08-4632-807c-8637b3d24af2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
