<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Youth Guidance Outreach Services</name>
   <tag></tag>
   <elementGuidId>4dfc6f10-7e0b-4218-a352-408c4be50a73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b7-l5-321_0-b16-Title']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b7-l5-321_0-b16-Title > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1b180432-348a-49a1-ae1b-e44450e36665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>spanCharityName</value>
      <webElementGuid>8ae54946-f26b-455c-a870-5c37dc3f0e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Youth Guidance Outreach Services</value>
      <webElementGuid>a8801577-81dd-4707-9d9d-5c897b19bf96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b7-l5-321_0-b16-Title&quot;)/span[1]</value>
      <webElementGuid>9329ba79-c807-4e04-a4d9-3de2a051381f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b7-l5-321_0-b16-Title']/span</value>
      <webElementGuid>2ea0624d-9bba-4653-bc2e-fba5b9e652fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results per page'])[1]/following::span[3]</value>
      <webElementGuid>504556fd-a4a6-47b9-9a83-8146cbe4656a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Social service and welfare'])[1]/preceding::span[2]</value>
      <webElementGuid>359253e3-fdf0-4e7f-86f5-60855c3b1654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malay Youth Literary Association'])[1]/preceding::span[5]</value>
      <webElementGuid>0f75175a-6155-4787-bfcc-4c5221388c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Youth Guidance Outreach Services']/parent::*</value>
      <webElementGuid>ab0dbac3-5061-416e-b6bc-a23fd6d48294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div[2]/span</value>
      <webElementGuid>120319eb-5597-446f-a700-bc2d3d84bf7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Youth Guidance Outreach Services' or . = 'Youth Guidance Outreach Services')]</value>
      <webElementGuid>7c58b918-3e85-4284-8794-935e5666599f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
