<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Fundraise</name>
   <tag></tag>
   <elementGuidId>5470f216-3df5-4b17-b62c-ddcc0ca4eeef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-l1-392_9-$b2']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>171839e8-eb8e-4fce-b350-5ee66ac4f915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-menu-item</value>
      <webElementGuid>8fb8b84a-c8fd-4cc6-b02e-a0080a2d6c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/auth/login?RedirectUrl=https%3A%2F%2Fdk.deloitte-sea.com%2Ffundraise%2Fcreate</value>
      <webElementGuid>62b1e69e-ce63-4a82-8346-3d1cd229849d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fundraise</value>
      <webElementGuid>98fd7cd4-886b-47d6-93ef-386b1cdeb781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-l1-392_9-$b2&quot;)/a[@class=&quot;nav-menu-item&quot;]</value>
      <webElementGuid>888a4312-eba5-45fc-9b31-7bdbb5fde842</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-l1-392_9-$b2']/a</value>
      <webElementGuid>1d3f9881-9f10-4650-86de-d71f9f13abf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collaborate'])[1]/following::a[1]</value>
      <webElementGuid>11d07a75-4d1a-4db8-bd33-91493498f069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volunteer'])[1]/following::a[2]</value>
      <webElementGuid>250c7e4b-4249-4fb8-b821-ca44fb0d0b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our organisations'])[1]/preceding::a[1]</value>
      <webElementGuid>399a2431-3ba0-471c-ad7c-e9acb690cae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/auth/login?RedirectUrl=https%3A%2F%2Fdk.deloitte-sea.com%2Ffundraise%2Fcreate')]</value>
      <webElementGuid>8e573cf9-0682-43e9-a297-5a0f11ee4a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>a673e445-17af-49eb-baef-ec65042cf446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/auth/login?RedirectUrl=https%3A%2F%2Fdk.deloitte-sea.com%2Ffundraise%2Fcreate' and (text() = 'Fundraise' or . = 'Fundraise')]</value>
      <webElementGuid>86aa9fa0-62f8-49d7-b5a1-a4d1468e8d3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
