<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sort Name A to Z</name>
   <tag></tag>
   <elementGuidId>4ea07f3a-7f1b-4d32-8cad-be1fa133ac27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@ktl-id='btnSort']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dropdown-display</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fdf519cd-4210-41a2-b5dd-d46fdb9d08ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display</value>
      <webElementGuid>aa827b02-da8c-4015-a92b-ed0da0a88a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sort: Name: A to Z</value>
      <webElementGuid>404b5c53-b6a0-401f-b263-5ce52c6ab97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b7-DropdownSortType&quot;)/div[@class=&quot;dropdown-display&quot;]</value>
      <webElementGuid>0b8e695c-9c34-4c39-8328-fd89c1cd935c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b7-DropdownSortType']/div</value>
      <webElementGuid>6734cb75-36c8-4fa0-a196-7e08a2500b90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear all'])[1]/following::div[3]</value>
      <webElementGuid>4f358aa7-b01b-487a-966b-e0296cdae52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tax-deductible'])[1]/following::div[4]</value>
      <webElementGuid>e35d9478-a797-47dd-bc94-633077ca8aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>15c01b3e-e5b5-4ee7-9edc-742eb4c5885e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sort: Name: A to Z' or . = 'Sort: Name: A to Z')]</value>
      <webElementGuid>2ede37c3-1e1c-47f9-88ba-230fb170ac7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
