<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2 campaigns</name>
   <tag></tag>
   <elementGuidId>08078baa-87c2-43d7-970d-52e18230d561</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b7-l5-266_0-b16-CampaignCount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b7-l5-266_0-b16-CampaignCount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ebf4b1fb-cc08-486f-bdbb-2fb79000ad6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>charity-card-content-count ph</value>
      <webElementGuid>26abac4e-61a8-453f-b5f8-0fee763002b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b7-l5-266_0-b16-CampaignCount</value>
      <webElementGuid>13441312-01e9-4080-a81b-466560e9ca68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2 campaigns</value>
      <webElementGuid>f372848f-3cc1-4bf3-a373-bbf54169f23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b7-l5-266_0-b16-CampaignCount&quot;)</value>
      <webElementGuid>716eadcb-d060-4bdb-a6d3-89621bc5c402</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b7-l5-266_0-b16-CampaignCount']</value>
      <webElementGuid>cc19df0b-f2ed-47c7-9a75-b962c0e28d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b7-l5-266_0-$b16']/div/div[2]</value>
      <webElementGuid>4559d8ac-f711-43ae-b160-4dffe625e331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local community'])[1]/following::div[1]</value>
      <webElementGuid>079556bf-fece-416d-8b36-8f516825d508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Education'])[2]/following::div[3]</value>
      <webElementGuid>31a36bf8-603d-4db7-9427-d809eaa950d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(DS) NPO 0002'])[1]/preceding::div[12]</value>
      <webElementGuid>443092ab-5d3d-4f68-b0ea-09c21f359e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[DS] Test About EG'])[2]/preceding::div[14]</value>
      <webElementGuid>dec32cf4-b3e1-4667-8c60-85b562c0f2cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[4]/div/div/div[2]</value>
      <webElementGuid>e402cdc3-a1bf-4e78-94b0-ebdf2fe60159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b7-l5-266_0-b16-CampaignCount' and (text() = '2 campaigns' or . = '2 campaigns')]</value>
      <webElementGuid>acc3af13-9b78-4aac-b794-c2e304875374</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
