<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Local community_b2-b7-l5-457_1-b14-b1-C_b1455d</name>
   <tag></tag>
   <elementGuidId>8480874e-d379-491f-b986-f7110aaf3883</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b7-l5-457_1-b14-b1-ContentImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='b2-b7-l5-457_1-b14-b1-ContentImage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a3bb04a8-5464-4d25-85d9-564852e8a26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>giving-image</value>
      <webElementGuid>f0f83a83-467a-4e79-89d0-4855796780c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/res/GetEntityGroupImage/eccb038d-763c-4d48-9a1b-45b96cf8ba41.jpg</value>
      <webElementGuid>b3bbcff7-e3ad-4524-ae7e-58d93fce4381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b7-l5-457_1-b14-b1-ContentImage</value>
      <webElementGuid>e0ad55b5-a181-49f7-a94f-6cac83e0f362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b7-l5-457_1-b14-b1-ContentImage&quot;)</value>
      <webElementGuid>e1a50453-e956-4d94-8a78-bc800cceebef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='b2-b7-l5-457_1-b14-b1-ContentImage']</value>
      <webElementGuid>0c80498d-9dbf-4b26-9925-7eda0a6e435e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b7-l5-457_1-b14-$b1']/img</value>
      <webElementGuid>6768baa5-be6c-46fb-92be-7c5ecdd512c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/img</value>
      <webElementGuid>c299791d-bf5a-486b-81d5-b9cebe641d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/res/GetEntityGroupImage/eccb038d-763c-4d48-9a1b-45b96cf8ba41.jpg' and @id = 'b2-b7-l5-457_1-b14-b1-ContentImage']</value>
      <webElementGuid>5d69d8cd-636a-4b22-a8fa-e1aff965cdbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
