<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__checkbox-icon</name>
   <tag></tag>
   <elementGuidId>39468cce-481f-4a00-9bbc-f66e5ee7f48d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vscomp-option-5076-0']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vscomp-option-5076-0 > span.checkbox-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>294314ff-4c15-46c2-9b0e-0a31a767ce0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-icon</value>
      <webElementGuid>3a21f711-d1dd-4b1b-8a18-17c4e57737ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vscomp-option-5076-0&quot;)/span[@class=&quot;checkbox-icon&quot;]</value>
      <webElementGuid>e04c244c-bc77-4fa9-83b3-4f26551d19c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vscomp-option-5076-0']/span</value>
      <webElementGuid>361df5b5-6e14-4696-953a-564fb9fa9b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div[2]/div/div/span</value>
      <webElementGuid>38354e8d-c3ad-4945-b9d9-887a0fac4bc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
