<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Animal welfare_checkbox-icon</name>
   <tag></tag>
   <elementGuidId>4ab3c8c4-7a48-4b47-a7a4-43e1027ffa8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vscomp-option-5076-2']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vscomp-option-5076-2 > span.checkbox-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>29cb802f-b4a9-43f2-8ea1-c0b90a4db586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-icon</value>
      <webElementGuid>13550cf3-c9c4-4a82-99b0-28583d4241c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vscomp-option-5076-2&quot;)/span[@class=&quot;checkbox-icon&quot;]</value>
      <webElementGuid>28a379ab-7713-4e89-882d-cb6c7a306b57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vscomp-option-5076-2']/span</value>
      <webElementGuid>65ab25f6-3fa2-445b-a4cd-54922b0cbefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div[2]/div/div[3]/span</value>
      <webElementGuid>1338fd66-c8e6-4573-b523-621648ec5ab7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
