<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__b2-RadioButton7</name>
   <tag></tag>
   <elementGuidId>bdc7d1dd-bc82-4715-b7f7-0583063e9c24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-RadioButton7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-RadioButton7</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;b2-RadioButton7&quot;)[count(. | //*[@id = 'b2-RadioButton7']) = count(//*[@id = 'b2-RadioButton7'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d2822649-094c-4226-99ac-2783220ec135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>OSFillParent</value>
      <webElementGuid>069fe52e-bdba-454c-b04b-f687b0c261bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-RadioButton7</value>
      <webElementGuid>e8774a04-87bb-4f9a-9369-65da904da397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-RadioButton7&quot;)</value>
      <webElementGuid>fbda1748-4175-47c9-b220-28e9a23237d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-RadioButton7']</value>
      <webElementGuid>6c62b36e-7962-4096-92ee-7fea2281e8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-RadioGroup4']/div/div</value>
      <webElementGuid>6578d280-a6ab-4ab1-94f1-59dbdf69037b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[3]/following::div[4]</value>
      <webElementGuid>06e8ff65-c5f9-48f4-a525-5aba93284696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Give other amounts'])[1]/following::div[10]</value>
      <webElementGuid>82385656-44ef-4318-bba0-bdab1887be0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[4]/preceding::div[3]</value>
      <webElementGuid>2909273b-bb24-4ada-b6c7-157c627b89b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[5]/preceding::div[15]</value>
      <webElementGuid>7a2451d2-ba35-409e-8700-a7e623780296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>6a2bf3b4-832c-461e-abeb-82921eb973ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-RadioButton7']</value>
      <webElementGuid>d611c13a-71be-4f19-a394-e488712d0333</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
