<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Give 60 for SG60 in the form of a 5 don_c1aa88</name>
   <tag></tag>
   <elementGuidId>e482b678-52a8-46c6-bb9d-687e2204cd26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b8-Detail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b8-Detail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0528c2e6-1556-4a2b-b3ce-9153142a5cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>detail-section ph</value>
      <webElementGuid>ab11ec2d-3389-446a-b8ff-465104009c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b8-Detail</value>
      <webElementGuid>f9054f6e-4704-44f2-ae54-119b60524721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Give $60 for SG60 in the form of a $5 donation once every month for the next 12 months. Log in or sign up with Singpass for this option.</value>
      <webElementGuid>4390b51e-5745-478a-9bbb-c45bfdf5bcbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b8-Detail&quot;)</value>
      <webElementGuid>eadd9ff4-b0c1-4718-85e7-5ad80af4949a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b8-Detail']</value>
      <webElementGuid>bb7002a2-03d8-497a-a1ba-31ae161ceccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b8-MainBlock']/div[2]/div</value>
      <webElementGuid>cc2c52da-d8ce-4a16-a8da-b709aac0a3a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$5x12 months'])[1]/following::div[6]</value>
      <webElementGuid>ca8debe4-759d-4132-b291-6461b7f5da0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[2]/following::div[6]</value>
      <webElementGuid>03e621a4-92a6-4faa-bd1d-6efaefdbe13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Give other amounts'])[1]/preceding::div[2]</value>
      <webElementGuid>a9fb5147-dbe4-4cf3-8684-2b21ab9b7c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='in the form of a $5 donation once every month for the next 12 months.']/parent::*</value>
      <webElementGuid>e3b3fd9a-15a8-4f13-85df-9e7cf08b7ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/div[2]/div</value>
      <webElementGuid>fe4b6329-6951-4868-a2af-9360d649e9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b8-Detail' and (text() = 'Give $60 for SG60 in the form of a $5 donation once every month for the next 12 months. Log in or sign up with Singpass for this option.' or . = 'Give $60 for SG60 in the form of a $5 donation once every month for the next 12 months. Log in or sign up with Singpass for this option.')]</value>
      <webElementGuid>5c1e9b80-2003-415e-8d4b-1d50efdc70fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
