<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_605x12 months</name>
   <tag></tag>
   <elementGuidId>1e195b46-4889-4d52-be18-bed93325cb0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
<<<<<<< HEAD
         <value>id(&quot;b2-b8-MainBlock&quot;)/div[@class=&quot;heading-section&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;b2-b8-MainBlock&quot;)/div[@class=&quot;heading-section&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b8-MainBlock > div.heading-section</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>18971b0a-1fc7-49c2-adfc-498afabefd5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading-section</value>
      <webElementGuid>fbe13b65-119f-4621-ab81-aa6bd2621d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 60$5x12 months</value>
      <webElementGuid>31e191f4-be85-41a1-99a4-9518ebca663e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b8-MainBlock&quot;)/div[@class=&quot;heading-section&quot;]</value>
      <webElementGuid>8b468364-6309-4237-98e5-82ed5ee73d51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b8-MainBlock']/div</value>
      <webElementGuid>1330da8c-5fc8-47ba-a976-e8d0529f2be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Give $60 for SG60'])[2]/following::div[4]</value>
      <webElementGuid>e4467009-66fb-4e83-9710-f92ac5561378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/div</value>
      <webElementGuid>3854123b-cfa1-423f-b50d-f2513ba7fa30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '$ 60$5x12 months' or . = '$ 60$5x12 months')]</value>
      <webElementGuid>e4fca4eb-2c4c-4dc8-b076-6392ecb0cb81</webElementGuid>
=======
         <value>//div[@id='b2-b8-MainBlock']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b8-MainBlock > div.heading-section</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c2eaf38b-bff3-4470-89e3-d01a4305f0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading-section</value>
      <webElementGuid>51d79772-6bcc-4b19-8f44-297e49c3f6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 60$5x12 months</value>
      <webElementGuid>f2bea4b6-f30f-479c-b26b-2fd8c8f32700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b8-MainBlock&quot;)/div[@class=&quot;heading-section&quot;]</value>
      <webElementGuid>b1b89236-f148-4ca3-b28b-f7d89b496ccf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b8-MainBlock']/div</value>
      <webElementGuid>5f8081be-4c0e-46bd-860b-8a1edf7d6e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Give $60 for SG60'])[2]/following::div[4]</value>
      <webElementGuid>f6e07a40-ea7d-412a-a171-54438e0bfa2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/div</value>
      <webElementGuid>62250de9-7761-4238-8b47-9ba2ed66cb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '$ 60$5x12 months' or . = '$ 60$5x12 months')]</value>
      <webElementGuid>cc0225e0-9da5-4cdd-8dd3-4fa711abcbff</webElementGuid>
>>>>>>> branch 'UATSG60' of https://github.com/madhooDeloitte/NVPCKatalon
   </webElementXpaths>
</WebElementEntity>
