<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_50</name>
   <tag></tag>
   <elementGuidId>3c6e3630-a755-4276-9c27-87709c4fbf43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b19-MainBlock']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b19-MainBlock > div.heading-section > div.header-portion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2f34ba3a-6c49-4359-b6a2-101c0aba6650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-portion</value>
      <webElementGuid>61c739d3-fcde-49a4-ab81-cbe9678014d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$ 50</value>
      <webElementGuid>21529640-119a-41e7-a217-fd14be298aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b19-MainBlock&quot;)/div[@class=&quot;heading-section&quot;]/div[@class=&quot;header-portion&quot;]</value>
      <webElementGuid>ee6b03eb-5110-4898-b2c5-ee2bf6fccda2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b19-MainBlock']/div/div</value>
      <webElementGuid>dbaa3fb2-0d4a-4b22-b52e-6ce439ffa991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[4]/following::div[11]</value>
      <webElementGuid>505476a5-5a74-4572-b75f-7e9fb9f8e673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[3]/following::div[23]</value>
      <webElementGuid>437d625d-2ba3-49c8-a84d-9a09fa779016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other amount'])[1]/preceding::div[8]</value>
      <webElementGuid>52ad1e55-83f1-4de1-85bc-2c9fee5b54e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/div/div/div/div</value>
      <webElementGuid>637276a7-42a8-452e-b99b-0500043054a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '$ 50' or . = '$ 50')]</value>
      <webElementGuid>f5c442b0-8621-4971-8651-5b373454b9ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
