<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Remove</name>
   <tag></tag>
   <elementGuidId>b9806046-d32d-4f59-ad48-d16aa2ad1d3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b2-b31-l1-447_7-b5-Items']/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b2-b31-l1-447_7-b5-Items > a.negative.ThemeGrid_MarginGutter</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'lnkRemoveDonationTier']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Remove&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b57876bd-aac2-4278-a583-d8e82dbfab81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>negative ThemeGrid_MarginGutter</value>
      <webElementGuid>ac573c01-04f3-4509-8836-76667c985bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>fd6ff426-de48-48c7-a854-fcb13d8cba9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove </value>
      <webElementGuid>456268a3-b687-4812-ac59-6c1768a0ff72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b2-b31-l1-447_7-b5-Items&quot;)/a[@class=&quot;negative ThemeGrid_MarginGutter&quot;]</value>
      <webElementGuid>b2fc4d15-7a7f-42f7-9b22-f24fcb1053fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>lnkRemoveDonationTier</value>
      <webElementGuid>ce54ccba-d06d-4b0c-bd4a-056d398117b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b2-b31-l1-447_7-b5-Items']/a[2]</value>
      <webElementGuid>30e02202-2930-4883-a72b-fb5b1ede9d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[4]/following::a[1]</value>
      <webElementGuid>b174b497-4d5b-4b5e-9d9f-8e6077dfabd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[4]/following::a[2]</value>
      <webElementGuid>c1717ac6-28ba-409b-a6a7-74d6908ef62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attack'])[1]/preceding::a[1]</value>
      <webElementGuid>b3f06efa-7668-44af-85d8-deab9f5fa199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[9]</value>
      <webElementGuid>1282e1cd-dab9-431e-aee8-abfee366c7f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/div/div/div/div/div[2]/div/div/a[2]</value>
      <webElementGuid>bdeb9ba6-8e38-43bb-9259-2784300a49d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Remove ' or . = 'Remove ')]</value>
      <webElementGuid>b124c38c-e85b-4cdb-a483-ed6938f3454b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
