<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_You are previewing this page. This camp_5cef1d</name>
   <tag></tag>
   <elementGuidId>eb4fe0f0-1a64-4041-8d9e-805c0e07ea42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b36-b3-Desktop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b36-b3-Desktop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0d06dfa6-d901-4475-8714-4b186e339e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hide-if-phone icon-wrapper active</value>
      <webElementGuid>bba77404-2746-48d1-80b9-437e31e6931a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b36-b3-Desktop</value>
      <webElementGuid>73dd71dc-68e5-4e4c-8020-f4cf80e41223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b36-b3-Desktop&quot;)</value>
      <webElementGuid>27e3a435-611a-47f7-9e2f-788789211d3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b36-b3-Desktop']</value>
      <webElementGuid>a9b743f7-a923-4f0a-aa8d-91f9467b0e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b36-$b3']/div/div</value>
      <webElementGuid>7036e0dc-5347-4d75-bb90-4d80ebee0cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You are previewing this page. This campaign has not yet been published.'])[1]/following::div[5]</value>
      <webElementGuid>e6da6619-7044-4b90-9241-89b864cd3fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview'])[2]/following::div[6]</value>
      <webElementGuid>16a0ff99-622c-41ea-8780-bd5030d0ce9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return to creation'])[1]/preceding::div[3]</value>
      <webElementGuid>deedf2a1-5e3e-4fdd-8b85-87f0fb4f1a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit for approval'])[1]/preceding::div[7]</value>
      <webElementGuid>9c1bf0f3-155e-4c95-9115-f78591f15c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>08243d2e-8870-4461-a111-475cd3ec1a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b36-b3-Desktop']</value>
      <webElementGuid>9f5eefbd-6579-4375-9b08-9fede9fc4634</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
