<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Donation amount_b2-b2-b31-b14-Input_T_7bdb71</name>
   <tag></tag>
   <elementGuidId>efa15dc3-f8b7-4708-b5f9-d3c504fa761d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'inpTierAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b2-b31-b14-Input_TierAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b2-b31-b14-Input_TierAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=spinbutton</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37c730da-a5e9-483e-88f3-9aa5c1eea0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>792f4cc8-9520-48f9-856c-25b10a93224f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>cc7d2a7e-0d2e-4218-936f-dfc5787ca047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d4ffa2c2-688c-478c-ab7c-68eb545cf4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>5af34d6e-85ad-4726-85d7-d1ef8c09f0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2147483647</value>
      <webElementGuid>7935cf62-2f85-431d-8a30-5b38c28990f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inpTierAmount</value>
      <webElementGuid>bd2e9ce3-accc-4529-afcc-f32c02564808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b2-b31-b14-Input_TierAmount</value>
      <webElementGuid>0d356848-ab48-4f62-9147-8d36a18dea5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b2-b31-b14-Input_TierAmount&quot;)</value>
      <webElementGuid>8e895ff6-fbb7-414f-916d-6e7ce3035df6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b2-b31-b14-Input_TierAmount']</value>
      <webElementGuid>67b703d0-7fdb-4677-8d6b-d3c8ea841303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b2-b31-b14-b3-Input']/span/input</value>
      <webElementGuid>f84c701b-be8f-44ea-b49c-13798125fe67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>54c88c52-b765-4936-8655-61ef36e7fdca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'b2-b2-b31-b14-Input_TierAmount']</value>
      <webElementGuid>780ed4cb-a801-4ff7-863f-8a5d81f76ebb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
