<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1Describe your opportunity2Tag your opp_457aea</name>
   <tag></tag>
   <elementGuidId>c59d3fe3-db6f-4e0e-bfc1-c1af5a39779b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-b4-b1-Wizard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b1-b4-b1-Wizard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f51d515d-3586-4af6-9491-8657d2fba7d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columns-item content-layout-form-wizard-section</value>
      <webElementGuid>725dd957-c150-4371-9bc6-5a10c67be044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b1-b4-b1-Wizard</value>
      <webElementGuid>4d353a1f-cc4f-4083-a7c9-3b6a028c2bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1Describe your opportunity2Tag your opportunity3Set schedule and location4Define volunteer position5Set vacancies6Settings</value>
      <webElementGuid>4032d63f-b856-486e-886f-85cc99e49791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-b4-b1-Wizard&quot;)</value>
      <webElementGuid>540414ed-971c-436e-9b0b-863657049684</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b4-b1-Wizard']</value>
      <webElementGuid>a7045fab-558a-4c36-a133-120812138d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b4-b1-MainContentWrapper']/div/div</value>
      <webElementGuid>a55cdbe0-d47b-4ae6-be63-dc0dce301ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exit'])[1]/following::div[17]</value>
      <webElementGuid>2f4e1809-5918-433f-9eee-6a1864d88433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>9d77b9a3-591a-4698-97cd-ebb5d50b286f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b1-b4-b1-Wizard' and (text() = '1Describe your opportunity2Tag your opportunity3Set schedule and location4Define volunteer position5Set vacancies6Settings' or . = '1Describe your opportunity2Tag your opportunity3Set schedule and location4Define volunteer position5Set vacancies6Settings')]</value>
      <webElementGuid>d99a207b-3ec4-4e83-8b34-37bec617bfdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
