<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(optional)_b2-b1-b7-Input_OtherResponses</name>
   <tag></tag>
   <elementGuidId>8996960e-6b08-424b-b1d2-0df6622810a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'inpOtherResponses']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-b7-Input_OtherResponses</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b1-b7-Input_OtherResponses']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebb459a1-61d0-455a-80dd-9b2fd7040c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>5f626d6b-647e-4c97-9660-7367451917a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>52b1b3be-a9a3-4e71-bf68-47b77d6ada35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1bbd84cf-b182-4ebf-952e-ca475228363d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inpOtherResponses</value>
      <webElementGuid>eb5f0cb7-4d82-4bfb-b4b8-68c99f6e1741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b1-b7-Input_OtherResponses</value>
      <webElementGuid>65113aea-2815-4680-9711-0db4d2eaab2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-b7-Input_OtherResponses&quot;)</value>
      <webElementGuid>bab82820-68b4-401c-96b3-dbb781043d4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b1-b7-Input_OtherResponses']</value>
      <webElementGuid>b1f40285-e381-44cb-8aa9-0bc6429d3b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b7-b15-FieldContent']/span/input</value>
      <webElementGuid>4850af22-23d6-45a5-b87e-95a0b6831322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/span/input</value>
      <webElementGuid>b5eac1bb-32ad-41ac-8a43-050a521e3974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b2-b1-b7-Input_OtherResponses']</value>
      <webElementGuid>c71f3fee-8b95-47d4-af65-6d59127026db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
