<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact number_b2-b1-b9-Gender_Checkbox</name>
   <tag></tag>
   <elementGuidId>77a0044a-356a-449b-9240-7cfdea2996a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'chkGender']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-b9-Gender_Checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b1-b9-Gender_Checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac941350-5325-4a95-ae09-cc3b66c5470d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ade059fa-950b-4287-a508-dfdbab9291e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>38502ade-28d4-437d-a5af-598a8148cf39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>chkGender</value>
      <webElementGuid>91059b02-fc43-404d-bcf4-58fa62e4fa67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b1-b9-Gender_Checkbox</value>
      <webElementGuid>3a2d1e74-3d65-42b1-9997-8057862e46ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-b9-Gender_Checkbox&quot;)</value>
      <webElementGuid>1d7478c9-348c-4e69-97a8-d58d18935653</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b1-b9-Gender_Checkbox']</value>
      <webElementGuid>67505663-016c-44af-9c2b-60121876e288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b9-b5-Control']/span/input</value>
      <webElementGuid>4f0f3a45-1e6f-4b67-817c-ec4993ae6841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/span/input</value>
      <webElementGuid>c3817a99-61a8-400a-9ea3-944792448b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b1-b9-Gender_Checkbox']</value>
      <webElementGuid>f63ff7f2-cbc3-4712-92bb-7492fd7e8078</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
