<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Auto-approve a volunteer when they me_334b32</name>
   <tag></tag>
   <elementGuidId>412083ca-3567-4e4c-9577-e26e5cebb5d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'checkbox' and @id = 'b2-b1-b7-b20-l1-421_0-Checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-b7-b20-l1-421_0-Checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@ktl-id='divConditions']/div/div/div[3]/div/div/div[1]/div/div[1]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70c92d37-fb5d-4635-a00b-dcf3571b68ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8b6df753-4c3a-4ba5-ba01-6d675ab1291b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c4c0c343-a2e9-4f23-b0c7-4c6313ecf782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b1-b7-b20-l1-421_0-Checkbox</value>
      <webElementGuid>c353091b-0928-4651-ba88-4f677d242d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-b7-b20-l1-421_0-Checkbox&quot;)</value>
      <webElementGuid>dcff38dd-26f6-4787-ad91-b7185d8ddb53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b1-b7-b20-l1-421_0-Checkbox']</value>
      <webElementGuid>ccf54f8b-eb62-4484-bf60-1b3eebe7d63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b7-b20-l1-421_0-b1-Control']/span/input</value>
      <webElementGuid>d2229aec-8d7a-4957-a3cd-23e4e15c7d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div/div/div/div/div/span/input</value>
      <webElementGuid>da17e0dc-a8a4-4d1c-be3f-99849220c5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b1-b7-b20-l1-421_0-Checkbox']</value>
      <webElementGuid>cd9da1a3-89a8-47cc-9461-0e6852008382</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
