<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_ca</name>
   <tag></tag>
   <elementGuidId>ff9763db-724c-4540-bca0-023545080c13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'inpKeyResponsibilitiesImpact']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-b7-TextArea_KeyResponsibilitiesImpact</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='b2-b1-b7-TextArea_KeyResponsibilitiesImpact']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>84dfc917-8f55-4928-a86c-6dd8969ac2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>1df853e3-5369-45a1-a0b3-34bff451b4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>0cf1fa14-8763-463b-986e-d177f5ac6b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>b403a1f7-5930-41d6-b6c7-0743c766df53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inpKeyResponsibilitiesImpact</value>
      <webElementGuid>0f103049-e36a-472f-beb9-82e65488e65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b1-b7-TextArea_KeyResponsibilitiesImpact</value>
      <webElementGuid>9b17b9ef-2a38-4bc0-b1df-a3393e28cf32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ca</value>
      <webElementGuid>f1f212ff-d56e-4523-909d-2a3fe7f03baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-b7-TextArea_KeyResponsibilitiesImpact&quot;)</value>
      <webElementGuid>8bfff308-18a3-46bc-8188-0a4a9e3ed038</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b2-b1-b7-TextArea_KeyResponsibilitiesImpact']</value>
      <webElementGuid>37b30784-f236-4829-8c1b-1792d68819e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b7-b12-TextArea']/span/textarea</value>
      <webElementGuid>89aa1c00-d3c1-407a-a998-4751fe8f245f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Let potential volunteers know what they will be doing and the impact they are making.'])[1]/following::textarea[1]</value>
      <webElementGuid>e91250fa-002a-4cd6-8e48-af4b5d4b9b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Key responsibilities and impact'])[1]/following::textarea[1]</value>
      <webElementGuid>a069c8f1-26c8-4091-b73c-15f72f4c6a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show more information'])[1]/preceding::textarea[1]</value>
      <webElementGuid>a81dc25a-dacb-4cda-963f-cc47c7bc07d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::textarea[1]</value>
      <webElementGuid>614b7c8e-df4f-480a-81fd-35f1d98cdada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ca']/parent::*</value>
      <webElementGuid>ab3a06fc-1f05-45fa-8b0b-125f1c4e2bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>2c667190-e60c-4a47-ae90-7a8843dde73c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b2-b1-b7-TextArea_KeyResponsibilitiesImpact' and (text() = 'ca' or . = 'ca')]</value>
      <webElementGuid>112aeb79-8b88-4068-bac6-2cac77c2fcbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
