<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_c</name>
   <tag></tag>
   <elementGuidId>e0b39c30-fde2-4e52-9845-561f4c481ba9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'inpKeyResponsibilitiesImpact']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-b7-TextArea_KeyResponsibilitiesImpact</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='b2-b1-b7-TextArea_KeyResponsibilitiesImpact']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>27a104eb-681f-494b-b892-67a070c3e727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>b5bcc25e-e5e8-448e-b60c-540a1c20b723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8c929e87-c0e1-49fa-b481-347378c26c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>381d8652-14be-41b5-bb6e-d8c151ef31ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inpKeyResponsibilitiesImpact</value>
      <webElementGuid>8a05f35c-c2f6-4d32-8dd1-58a2e0682edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b1-b7-TextArea_KeyResponsibilitiesImpact</value>
      <webElementGuid>e28478b1-c020-439d-a808-e93ca1740d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>c</value>
      <webElementGuid>b13f3fb3-f5c1-4bbe-9b1d-7186602b5d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-b7-TextArea_KeyResponsibilitiesImpact&quot;)</value>
      <webElementGuid>be6edd51-93ef-46b8-ba1b-6792e0394902</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b2-b1-b7-TextArea_KeyResponsibilitiesImpact']</value>
      <webElementGuid>7ee4dba6-3a31-4f92-9fcb-780450a773cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b7-b12-TextArea']/span/textarea</value>
      <webElementGuid>cb25ed91-2ec0-40a9-a1ad-97ff88fa72c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Let potential volunteers know what they will be doing and the impact they are making.'])[1]/following::textarea[1]</value>
      <webElementGuid>7f03bae6-4fef-4049-8c9e-c46e7bf88d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Key responsibilities and impact'])[1]/following::textarea[1]</value>
      <webElementGuid>6d00de23-d567-4940-a609-8042ca1958a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show more information'])[1]/preceding::textarea[1]</value>
      <webElementGuid>b5dcaa94-7409-4bc2-8a9a-5ffa1f73b8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::textarea[1]</value>
      <webElementGuid>0088d8a3-28de-4859-a179-3b24015cb089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='c']/parent::*</value>
      <webElementGuid>29a4cf76-daa2-4757-9d2e-0658e2a424b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6a0f6f62-1d57-4355-8442-763d534a7b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b2-b1-b7-TextArea_KeyResponsibilitiesImpact' and (text() = 'c' or . = 'c')]</value>
      <webElementGuid>8313f58f-aa84-4da4-ad8c-aeac200f3e8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
