<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Stories_icon-box</name>
   <tag></tag>
   <elementGuidId>dc4fdc59-f9ed-4954-b7da-4e9cafee6dc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'btnAdminView-GraphIcon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b1-b1-PortalSwitch > div > a.icon-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-b1-PortalSwitch']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db2bdbd7-6444-4140-ac22-b8dc329d3ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-box</value>
      <webElementGuid>a40c995c-23b7-4601-861f-cc4a33200a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5279e8e6-feba-4527-aad6-477cae8a262a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>btnAdminView-GraphIcon</value>
      <webElementGuid>2449e6ed-4232-4bf9-a2cc-ee3ac9fef443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-b1-PortalSwitch&quot;)/div[1]/a[@class=&quot;icon-box&quot;]</value>
      <webElementGuid>f2ed419a-58a9-4e3e-82e5-539cb5a5d6ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-b1-PortalSwitch']/div/a</value>
      <webElementGuid>76250574-e3cc-48e1-9a4e-4af34d5617fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stories'])[1]/following::a[1]</value>
      <webElementGuid>e4283cf6-7509-4f8f-a0d2-6046de7e5760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our organisations'])[1]/following::a[2]</value>
      <webElementGuid>99d6a8bd-ee30-48b0-a428-dd8882ebdad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::a[1]</value>
      <webElementGuid>aa83bc3b-c76b-453a-8bbf-0eb831efbeb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rajeev Menon'])[1]/preceding::a[2]</value>
      <webElementGuid>f55065db-1f3b-4414-b41e-bdaa57f5928f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>15308052-b73a-48b7-a064-88184e5c9e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/a</value>
      <webElementGuid>dfc9d031-a1ff-407d-8e3c-8ed236752346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>9c43ad64-b7c0-4683-813e-515f1d6c9519</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
