<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Dedication message_b2-b15-b20-Text_bf4ba3</name>
   <tag></tag>
   <elementGuidId>98e82f15-5fc8-4d6a-bcd9-65aedd7e0b2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='b2-b15-b20-TextArea_DedicationMessage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b15-b20-TextArea_DedicationMessage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>53b2e47d-e275-4072-881c-50a9c9474b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>3c1da7d6-b718-4f48-9bc5-b028e42e65e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f0b1523c-0209-438d-b29f-67f15627b6c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>6fca3f51-18f0-4368-ab5d-2d99d9007364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b15-b20-TextArea_DedicationMessage</value>
      <webElementGuid>ec4ce896-1a56-430c-8cb3-5cbbe0eea53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b15-b20-TextArea_DedicationMessage&quot;)</value>
      <webElementGuid>37497ff0-22a1-49e7-b279-438bd6b23d79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b2-b15-b20-TextArea_DedicationMessage']</value>
      <webElementGuid>668c7c7a-8099-4a94-a0d9-610165dcb304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b15-b20-b10-FieldContent']/span/textarea</value>
      <webElementGuid>dce56218-f181-4ff1-b6fa-c19c8a67b459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>66313bf9-4e3f-483c-b5e7-c2fd4a9ed34c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b2-b15-b20-TextArea_DedicationMessage']</value>
      <webElementGuid>ac72c10a-8619-415e-a685-8f4cf55298b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
