<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>6c90c34a-4939-4ac7-b523-23851a2359a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-$b5']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.nvpc-avatar > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b0ec8c85-93a2-45e2-8544-d1379fc09e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/dk/img/NVPC_Resources.FallBackAvatar.svg?DLsZttr+v9X6smbJiSw9hg</value>
      <webElementGuid>511a2f03-11f0-4416-83cb-19644ea8743f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-$b5&quot;)/div[@class=&quot;nvpc-avatar&quot;]/img[1]</value>
      <webElementGuid>13b4900e-587f-44c2-9093-cee4d4ac47c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-$b5']/div/img</value>
      <webElementGuid>66633fb7-df0a-42b2-a1c2-17184c621d7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/img</value>
      <webElementGuid>a5c730f8-da71-4b4f-90a3-cf6c6dbfed69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/dk/img/NVPC_Resources.FallBackAvatar.svg?DLsZttr+v9X6smbJiSw9hg']</value>
      <webElementGuid>61fb0c6a-536d-47d2-8499-487f6bed86f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
