<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unit_b2-b6-Input_UnitNumber</name>
   <tag></tag>
   <elementGuidId>0da8fceb-22e3-4ae5-84eb-5cdebf591fcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b6-Input_UnitNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b6-Input_UnitNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6941ca09-33b0-4b64-aa93-b323d64961f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>68bfcf1e-8b85-4631-9b12-003c1698ea00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c647685f-f32e-4f3c-b23f-078e5d26a1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>84609818-d1e0-4611-8442-5faddd452f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inpUnitNumber</value>
      <webElementGuid>6ed1d57f-b98c-4179-9b6a-003723208350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b6-Input_UnitNumber</value>
      <webElementGuid>d89d2054-4706-4a6b-9ab4-f59dc124f99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b6-Input_UnitNumber&quot;)</value>
      <webElementGuid>a271560d-da60-4a98-8a49-e057d17198b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b6-Input_UnitNumber']</value>
      <webElementGuid>469c969c-37ba-426e-9dd1-3dd8fe9b64b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b6-b27-UnitInput']/span/input</value>
      <webElementGuid>bdea39ec-1e87-4bca-80ed-762ee22ba9d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/div[3]/div/span/input</value>
      <webElementGuid>bca7cc3d-a63a-48db-bf77-d7b95597ffac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b2-b6-Input_UnitNumber']</value>
      <webElementGuid>d9062074-fca2-436f-92d1-8d4e21a8d43c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
