<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Clear all</name>
   <tag></tag>
   <elementGuidId>57b58b4b-58c0-4c0b-ad72-0064952a6263</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.underline</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@ktl-id='btnClearAll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Clear all&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>026bc278-c00e-4a81-a7ce-a9978231804c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>underline</value>
      <webElementGuid>a61c3a7d-9e7f-447b-8939-fb99678cf45c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clear all</value>
      <webElementGuid>bf8590d5-74c1-430a-81af-fd3c3680309d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b9-ClearAll&quot;)/a[@class=&quot;text-link&quot;]/span[@class=&quot;underline&quot;]</value>
      <webElementGuid>aff67e85-bbc0-4eb4-ac55-a1e1323b7c0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b9-ClearAll']/a/span</value>
      <webElementGuid>4eba2e65-5287-4710-bf00-f6f604ddbe47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Under-served'])[1]/following::span[1]</value>
      <webElementGuid>bd819c49-73a8-4b3e-8d55-59ad31aee3a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private'])[1]/following::span[2]</value>
      <webElementGuid>f10d9fd9-e5bc-4c85-aab3-7bb3d19a6f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort:'])[1]/preceding::span[1]</value>
      <webElementGuid>523c35be-3efd-489a-8759-563d3a010d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popularity'])[1]/preceding::span[2]</value>
      <webElementGuid>6f3205ef-87a6-4114-9a78-4e7a43b29cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clear all']/parent::*</value>
      <webElementGuid>52366b2e-11a1-4ae6-bf50-5671665266d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a/span</value>
      <webElementGuid>7f61067e-c2ea-4d12-81dd-6c8ab2d22752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Clear all' or . = 'Clear all')]</value>
      <webElementGuid>b5240f61-dc51-4727-9bb0-e14656202807</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
