<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Report typeDonation by periodDate rang_964aac</name>
   <tag></tag>
   <elementGuidId>2c262fbc-92dd-4fbc-a18d-fe8b8e09233d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='b2-b4-Filters']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b4-Filters</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>422ec354-c6c0-420a-b98c-3865288c7e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form OSFillParent</value>
      <webElementGuid>73657626-3d7f-4c2c-958b-2485e6d0fb8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b4-Filters</value>
      <webElementGuid>391402a0-4896-4caa-a4c0-75507c6b9920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6b70a661-6c28-4e12-9421-e3bb7c19e248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Report typeDonation by periodDate rangeUse arrow down key to open the calendar; Use arrow keys to navigate through calendar days; Use cmd or ctrl + right or left arrow keys to navigate through months; Use cmd or ctrl + up or down arrow keys to navigate through years;Generate report</value>
      <webElementGuid>641e4e09-bc8f-438a-a931-f15ee14ba746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b4-Filters&quot;)</value>
      <webElementGuid>114470d4-d2f8-43fa-bcb5-8c7ad6fdd4b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='b2-b4-Filters']</value>
      <webElementGuid>745d14f4-873e-4192-8f8d-fd42df5bbf9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b4-Section_Filters']/form</value>
      <webElementGuid>0be49f74-1236-4eaa-b2da-e09023df0a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[3]/following::form[1]</value>
      <webElementGuid>fef484a8-70af-4140-905a-1b0ae676a0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[2]/following::form[1]</value>
      <webElementGuid>68ac17cb-9a1c-442d-872f-a479acefe874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>ae63061a-3402-4c64-921c-b4ea24b94dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'b2-b4-Filters' and (text() = 'Report typeDonation by periodDate rangeUse arrow down key to open the calendar; Use arrow keys to navigate through calendar days; Use cmd or ctrl + right or left arrow keys to navigate through months; Use cmd or ctrl + up or down arrow keys to navigate through years;Generate report' or . = 'Report typeDonation by periodDate rangeUse arrow down key to open the calendar; Use arrow keys to navigate through calendar days; Use cmd or ctrl + right or left arrow keys to navigate through months; Use cmd or ctrl + up or down arrow keys to navigate through years;Generate report')]</value>
      <webElementGuid>2d6aa36f-ef69-43b0-9862-717e83caa5cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
