<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Invoices_b1-b5-AvatarImage_Url</name>
   <tag></tag>
   <elementGuidId>ffd96671-7488-41cb-8aa1-1c4bc005c129</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='b1-b5-AvatarImage_Url']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b1-b5-AvatarImage_Url</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5a4f50e4-b79b-489d-b92e-385468d187eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/res/GetEntityGroupImage/e56a8b96-1297-4524-9214-4bde185350b2.jpg</value>
      <webElementGuid>4b319bc1-79bb-49b5-b2bb-733ad7b91c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b1-b5-AvatarImage_Url</value>
      <webElementGuid>9b1dd036-48c7-49ca-b867-cdda503a28e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-b5-AvatarImage_Url&quot;)</value>
      <webElementGuid>c73be044-c2b3-450b-8a78-5b8a0614e1e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='b1-b5-AvatarImage_Url']</value>
      <webElementGuid>469ec060-e361-4421-935e-e9b17ecf7d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-$b5']/div/img</value>
      <webElementGuid>97c6cb49-6eff-489c-8130-26bf915f3827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/img</value>
      <webElementGuid>710a083e-ace0-49f3-833d-333dc4a75874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/res/GetEntityGroupImage/e56a8b96-1297-4524-9214-4bde185350b2.jpg' and @id = 'b1-b5-AvatarImage_Url']</value>
      <webElementGuid>5b4a1621-f0dd-44eb-b66e-5885bfad4a7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
