<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add position 2</name>
   <tag></tag>
   <elementGuidId>07ab44d6-f067-4237-8e99-d78ae0873026</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//i[@ktl-id='btnAdd'])</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd009b7a-da8a-4cab-ae16-104b12bab9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-icon</value>
      <webElementGuid>75834dab-45d9-4894-86c0-7d8953e8ad1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>377b57f6-743f-4085-b18c-51a38817991d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-b6-b10-$b13&quot;)/div[1]/div[@class=&quot;placeholder-card&quot;]/div[@class=&quot;placeholder-card-action&quot;]/button[@class=&quot;btn btn-icon&quot;]</value>
      <webElementGuid>01f74c18-d350-44d8-899c-d3c59bcccc20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>c07c53be-efcb-46e3-91db-872c48d93414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b6-b10-$b13']/div/div/div/button</value>
      <webElementGuid>9524effc-d719-4a74-9442-ce40506f9f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You can set multiple dates and time slots. Opportunity should minimally start one day from today.'])[1]/following::button[1]</value>
      <webElementGuid>bd3f7b8e-164b-4855-b315-978f0234bbf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set up your opportunity schedule'])[1]/following::button[1]</value>
      <webElementGuid>61ef43d7-e5a2-48df-bca6-bd4103eab442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add schedule'])[1]/preceding::button[1]</value>
      <webElementGuid>993dd7df-12f3-43f7-9473-c454543402f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registration end date'])[1]/preceding::button[1]</value>
      <webElementGuid>bf522c19-6bb6-47dc-aa80-ed51cce964eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button</value>
      <webElementGuid>5fd84c24-814a-48b2-b68f-a788d7eee026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>1e3589ad-747f-42fb-8a22-d690b9472838</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
