<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1Describe your opportunity2Tag your opp_457aea</name>
   <tag></tag>
   <elementGuidId>663b0534-7182-4ef5-be14-efb0ff1214b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b1-b4-b1-Wizard']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-b4-b1-Wizard</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f5c75936-711a-498e-b588-9faa46aa638a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columns-item content-layout-form-wizard-section</value>
      <webElementGuid>1a55cecc-609c-4b1b-803b-9d464f9beabf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b1-b4-b1-Wizard</value>
      <webElementGuid>856606f0-2bf1-4e15-b92a-0dc4381f2c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1Describe your opportunity2Tag your opportunity3Set schedule and location4Define volunteer position5Set vacancies6Settings</value>
      <webElementGuid>8218d027-5489-4a42-8127-d521a09822fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-b4-b1-Wizard&quot;)</value>
      <webElementGuid>f3d89c92-f76e-40f3-b8f5-679913e74fc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b4-b1-Wizard']</value>
      <webElementGuid>1abd68f6-18da-4122-9ba5-ed4cac00dfee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b4-b1-MainContentWrapper']/div/div</value>
      <webElementGuid>d723d541-9820-4896-8e69-3b054a09404b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exit'])[1]/following::div[17]</value>
      <webElementGuid>c08907e4-e449-4d21-a29b-58988864c2e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div</value>
      <webElementGuid>abd7db44-fe69-46d7-a799-ef0c2beb646d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b1-b4-b1-Wizard' and (text() = '1Describe your opportunity2Tag your opportunity3Set schedule and location4Define volunteer position5Set vacancies6Settings' or . = '1Describe your opportunity2Tag your opportunity3Set schedule and location4Define volunteer position5Set vacancies6Settings')]</value>
      <webElementGuid>4581fc07-4372-472c-bdad-90f67ac44d96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
