<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Auto-approve a volunteer when they me_334b32</name>
   <tag></tag>
   <elementGuidId>a8fcefcc-8591-4edd-9230-1fd72ff797f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@ktl-id='divConditions']/div/div/div[3]/div/div/div[1]/div/div[1]/span/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'checkbox' and @id = 'b2-b1-b7-b20-l1-421_0-Checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-b7-b20-l1-421_0-Checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4899153-eae6-421f-9051-8d591d4118db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>11d90b22-6ffa-4048-95be-763fff8f9b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>aa66fa9d-4e90-4679-9d53-3e83b100612c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b1-b7-b20-l1-421_0-Checkbox</value>
      <webElementGuid>a0fbe618-2f49-43ea-896f-4cb8e70a1be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-b7-b20-l1-421_0-Checkbox&quot;)</value>
      <webElementGuid>0e17fb7a-c29d-448e-97c5-68644b17a41c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b1-b7-b20-l1-421_0-Checkbox']</value>
      <webElementGuid>fa2bb4f2-87f8-4aea-b138-9c946ab4d4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b7-b20-l1-421_0-b1-Control']/span/input</value>
      <webElementGuid>3cb4b0d7-b008-4263-bb42-408f712c0246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div/div/div/div/div/span/input</value>
      <webElementGuid>1c787ea9-1efe-4082-a5dc-0ec200553afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b1-b7-b20-l1-421_0-Checkbox']</value>
      <webElementGuid>2678c318-e70b-4ce3-9564-1442c6f6b249</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
