<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Not available_b2-b1-b8-l3-478_0-l3-47_610509</name>
   <tag></tag>
   <elementGuidId>9e8fc9c7-cf03-4c38-ae65-370a4af33c27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b1-b8-l3-478_0-l3-479_0-l3-480_1-Checkbox1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'chkVacancyItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-b8-l3-478_0-l3-479_0-l3-480_1-Checkbox1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85f6bdba-281e-459c-96fc-3d4d2d5b27a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b3b77457-23f1-4c1f-acdd-67e4c8dea55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e6d98025-bf38-4943-9d10-e32a60d4f9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>chkVacancyItem</value>
      <webElementGuid>6342eab5-2903-4017-aafd-bad20e87cde9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b1-b8-l3-478_0-l3-479_0-l3-480_1-Checkbox1</value>
      <webElementGuid>47e6ec88-069e-4810-a648-caeab4535f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-b8-l3-478_0-l3-479_0-l3-480_1-Checkbox1&quot;)</value>
      <webElementGuid>9f07a6d8-8d3a-4067-8286-16ce1e062ecf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b1-b8-l3-478_0-l3-479_0-l3-480_1-Checkbox1']</value>
      <webElementGuid>5d6fdc71-a90f-4e59-9d35-9cfa2aa952fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b8-l3-478_0-l3-479_0-l3-480_1-b9-Control']/span/input</value>
      <webElementGuid>1c93fa7b-6334-40dd-934e-772f1a8c6156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/span/input</value>
      <webElementGuid>3405bae0-3af8-4198-9a3e-8963b621f235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b1-b8-l3-478_0-l3-479_0-l3-480_1-Checkbox1']</value>
      <webElementGuid>b3d3b791-8750-4668-9d4d-27e9ceb54106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
