<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Accounting and finance_b2-b1-b7-b24-l_42d12b</name>
   <tag></tag>
   <elementGuidId>18683b91-247d-4ccf-8d85-64b9f13dd5d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b1-b7-b24-l1-442_1-Checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-b7-b24-l1-442_1-Checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8dbf755-e535-4423-ba4f-f5a0b6457c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d59f6c35-49d4-4ed4-820b-cb0ff7641ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>da0b8bb1-9675-46f9-b458-0772142fc146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b1-b7-b24-l1-442_1-Checkbox</value>
      <webElementGuid>3caf5310-c395-4fcb-8746-7a1014d83459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-b7-b24-l1-442_1-Checkbox&quot;)</value>
      <webElementGuid>31b23032-e05c-429a-830f-c8819b9839b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b1-b7-b24-l1-442_1-Checkbox']</value>
      <webElementGuid>f1a15e6c-1e45-45cf-9fb6-6d1d89ade505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b7-b24-l1-442_1-b1-Control']/span/input</value>
      <webElementGuid>0d0ee558-4345-4524-b015-e3c48ae86bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>b0a6a1b6-8df0-484e-8872-8f30c10ddee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b1-b7-b24-l1-442_1-Checkbox']</value>
      <webElementGuid>91a4dc84-7e69-48a1-a472-19024e4c2a4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
