<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ProjectFrequency</name>
   <tag></tag>
   <elementGuidId>8cf0933f-cd75-4fb3-a6ca-2a783be9b9eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dropdown-display</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@ktl-id='divProjectFrequencyDropdown']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>39bcbe70-88ae-4236-afbb-a1f5986ede1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display</value>
      <webElementGuid>8514922b-7209-466c-8a33-b5beff481a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select</value>
      <webElementGuid>92853436-76ab-49e6-aa16-0eed0947799f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b6-b11-Dropdown_ProjectFrequency&quot;)/div[@class=&quot;dropdown-display&quot;]</value>
      <webElementGuid>7967c262-7668-4d60-9caf-475b5edbe127</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b6-b11-Dropdown_ProjectFrequency']/div</value>
      <webElementGuid>c6e9f6c5-5fa3-4442-9854-26beebe37d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frequency'])[1]/following::div[5]</value>
      <webElementGuid>f030a555-c62e-4c10-bf63-4bfa071b4764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='hours'])[1]/following::div[11]</value>
      <webElementGuid>5c10e9a9-0312-493b-babd-f1efeb7348ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registration end date'])[1]/preceding::div[7]</value>
      <webElementGuid>6cfba2a5-3f38-447d-81f5-e7083f48de2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div</value>
      <webElementGuid>78fd7aa1-0022-4274-9086-18f72c7bc901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Please select' or . = 'Please select')]</value>
      <webElementGuid>a2962c59-bc88-44a4-aead-55087d7a5854</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
