<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Y Water Venture 2024YMCA of Singapore26042024  28 more dates</name>
   <tag></tag>
   <elementGuidId>87206479-0f0a-4dd4-a7ad-6b06cbe2a2eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-l3-658_10-b42-Content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-l3-658_10-b42-Content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3c77352d-f5d1-4c8b-ac1f-5072e3e0a6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-card-content-wrapper</value>
      <webElementGuid>1da9137b-0a39-4d85-a5f4-5df781d4aec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l3-658_10-b42-Content</value>
      <webElementGuid>f8841646-c458-47f6-8ccf-ab3975cc6447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Y Water Venture 2024YMCA of Singapore26/04/2024 + 28 more dates</value>
      <webElementGuid>9f625f6f-8c5d-4ac3-accf-1b8317c26073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l3-658_10-b42-Content&quot;)</value>
      <webElementGuid>9e3967ec-7575-4e07-9d40-3c168ff9657e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-l3-658_10-b42-Content']</value>
      <webElementGuid>acbc62e1-7b3a-417a-a60c-994a5603d971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-l3-658_10-$b42']/div/div[4]</value>
      <webElementGuid>350d25f0-c43f-4e71-9efe-d8e7feceda75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SG Cares Volunteer Centre at Jurong East'])[3]/following::div[24]</value>
      <webElementGuid>a05b1740-db91-4fa2-a813-734dbd2da698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mental Health Care - Youth Advocate (Project Cope) volunteer with Impart'])[1]/following::div[30]</value>
      <webElementGuid>0044e008-e430-4f5f-a730-c62295248b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div[4]</value>
      <webElementGuid>5a4b52fd-6629-4f19-9d3f-35c55a3b0018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-l3-658_10-b42-Content' and (text() = 'Y Water Venture 2024YMCA of Singapore26/04/2024 + 28 more dates' or . = 'Y Water Venture 2024YMCA of Singapore26/04/2024 + 28 more dates')]</value>
      <webElementGuid>bbf08df2-bc5e-4fa8-a0a7-9d2890cf5f17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
