<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_spread the love our world needsTania for Children-At-Risk Empowerment Association (CARE Singapore)368 raised of 28,0005 donors</name>
   <tag></tag>
   <elementGuidId>ab05262d-41a1-435b-b73d-1cd2192bab9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-l3-284_4-b26-Content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-l3-284_4-b26-Content']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e4e2c77a-5041-4afa-a67b-ead7c1293fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-card-content-wrapper</value>
      <webElementGuid>32276dfd-660a-476e-9927-26259a0c3a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l3-284_4-b26-Content</value>
      <webElementGuid>4f84ccfc-ea80-4a7b-a910-e9f9e5d2dda9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>感天感地感动你.. spread the love our world needsTania for Children-At-Risk Empowerment Association (CARE Singapore)$368 raised of $28,0005 donors</value>
      <webElementGuid>568c5fb7-8608-474a-9aa3-d4f14c7360f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l3-284_4-b26-Content&quot;)</value>
      <webElementGuid>67768eba-6649-44f4-b45d-2973d4482968</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-l3-284_4-b26-Content']</value>
      <webElementGuid>f0e72e12-aefa-4932-9d73-36098b0f4842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-l3-284_4-$b26']/div/div[4]</value>
      <webElementGuid>19fdab2d-647a-4d6d-a179-1737d09e010c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tax-deductible'])[7]/following::div[4]</value>
      <webElementGuid>8ce7d56c-9b92-4392-b357-54cc11310f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,605 raised of $9,000'])[1]/following::div[18]</value>
      <webElementGuid>84b6a3a4-6893-4e70-9cfe-ff851d9f736a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[4]</value>
      <webElementGuid>10d4c468-9b90-4b0d-b1ae-f758dc063bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-l3-284_4-b26-Content' and (text() = '感天感地感动你.. spread the love our world needsTania for Children-At-Risk Empowerment Association (CARE Singapore)$368 raised of $28,0005 donors' or . = '感天感地感动你.. spread the love our world needsTania for Children-At-Risk Empowerment Association (CARE Singapore)$368 raised of $28,0005 donors')]</value>
      <webElementGuid>3c87db99-3934-46a1-b0aa-4ae392134487</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
