<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Enjoy tax benefits with your donations _40356b_1</name>
   <tag></tag>
   <elementGuidId>1eb16392-5e3a-43ff-aa7c-21ac6c0fbd7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b6-Header']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b6-Header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7e16f514-ae24-4813-88e7-b2c1291fea0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart-info-box__header ph</value>
      <webElementGuid>0b6c8405-97a1-4f29-bcba-49a3ca8c63cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b6-Header</value>
      <webElementGuid>06cf4f7f-1720-44f0-9793-69fc4f871271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enjoy tax benefits with your donations when you log in</value>
      <webElementGuid>9740d90f-fb37-4c1e-8e40-6e1b1994ccad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b6-Header&quot;)</value>
      <webElementGuid>4709fae5-b70f-4f51-87a0-16342893bafe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b6-Header']</value>
      <webElementGuid>8bd2402d-2937-438a-9634-7bdcf5c2be51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b6-ContentContainer']/div</value>
      <webElementGuid>e00e2374-9a49-4df2-be1a-1c691a416ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Details'])[1]/following::div[8]</value>
      <webElementGuid>e5ba8eb1-808f-4cff-b1fa-93a446be5d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment details'])[1]/following::div[10]</value>
      <webElementGuid>5d99f9bd-9f38-4c22-893c-7db6343a55d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[3]/preceding::div[2]</value>
      <webElementGuid>77b82a65-1e04-4816-aacb-37302a15c80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enjoy tax benefits with your donations when you log in']/parent::*</value>
      <webElementGuid>90da8820-0d28-474e-b62f-8a6c064e7539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div[2]/div</value>
      <webElementGuid>1e323e60-d9c9-49c3-8ee3-36dd30fad7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b6-Header' and (text() = 'Enjoy tax benefits with your donations when you log in' or . = 'Enjoy tax benefits with your donations when you log in')]</value>
      <webElementGuid>58fa10d7-e327-42c3-af19-394aecc43e69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
