<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_test_icon-box</name>
   <tag></tag>
   <elementGuidId>2e530e73-9118-4a45-bbbc-007591c0eef2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b11-l3-281_0-l3-282_0-b9-b1-Content > div.icon-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='osui-tooltip__content' and @id='b2-b11-l3-617_0-l3-618_0-b9-b1-Content' and @role='button']&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;b2-b11-l3-281_0-l3-282_0-b9-b1-Content&quot;)/div[@class=&quot;icon-box&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>221f5ea7-901b-4bf0-93b7-3f6a92885fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-box</value>
      <webElementGuid>faac12a2-4771-4127-837c-f8f757911994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='osui-tooltip__content' and @id='b2-b11-l3-617_0-l3-618_0-b9-b1-Content' and @role='button']&#xd;
</value>
      <webElementGuid>8996bfa3-535a-4f16-a13b-c33f9af9a1b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b11-l3-281_0-l3-282_0-b9-b1-Content']/div</value>
      <webElementGuid>4b0a34e3-36d7-44f0-b2af-ee6eb9f572b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/following::div[6]</value>
      <webElementGuid>806226d7-c15f-4750-92ec-d6b23cb333ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test question to ask'])[1]/following::div[7]</value>
      <webElementGuid>1f02838e-58ba-4aa9-9557-b773893e7adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::div[2]</value>
      <webElementGuid>525a8ff2-0f29-42e3-9a1b-f56f0ebe54cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/preceding::div[7]</value>
      <webElementGuid>57f6a7cc-d9bb-4041-9bfb-4e84f2943d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/div/div/div/div/div</value>
      <webElementGuid>1ae21e31-862f-42c7-a15b-5dedf374ad47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
