<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Visa ending in 4242</name>
   <tag></tag>
   <elementGuidId>fd04bccd-5e68-4919-8ce4-e3081665e517</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b7-l1-103_1-b1-Content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b7-l1-103_1-b1-Content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>385d1d46-cd3d-4458-bf1e-f76ec85ae306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ph card card-content border-radius-none</value>
      <webElementGuid>fa2c9250-ccbb-48c0-822b-3312e5eeba3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b7-l1-103_1-b1-Content</value>
      <webElementGuid>3c96acf9-c3a3-4777-889e-67258f0e342b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visa ending in 4242</value>
      <webElementGuid>6a23d6dd-7864-4d25-9c89-db9217a301f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b7-l1-103_1-b1-Content&quot;)</value>
      <webElementGuid>994ad06f-4c9c-44b4-98e0-5be4455a26f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b7-l1-103_1-b1-Content']</value>
      <webElementGuid>31a212a2-13de-4cec-a65a-bec6bd5e91bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b7-l1-103_1-$b1']/div</value>
      <webElementGuid>fff74a55-93ef-4157-9719-0351320d50a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default'])[1]/following::div[4]</value>
      <webElementGuid>9813f7bb-334a-4441-9087-ccc87a193af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visa ending in 4242'])[1]/following::div[6]</value>
      <webElementGuid>fe1529ab-2f8b-48cd-a550-2eccc4b40707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+ Add debit or credit card'])[1]/preceding::div[7]</value>
      <webElementGuid>39654dbd-674e-4256-8416-21c8545c736f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>5a7d782f-c533-49af-a3c1-e550ff68bbb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b7-l1-103_1-b1-Content' and (text() = 'Visa ending in 4242' or . = 'Visa ending in 4242')]</value>
      <webElementGuid>55eebae9-9a4e-462f-b6d9-0aec0090e6c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
