<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EditRemove</name>
   <tag></tag>
   <elementGuidId>f6eae5cd-151f-49d6-9fc0-286c5b79dd67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b15-l3-301_0-l3-302_0-b9-b1-TooltipBallonWrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b15-l3-301_0-l3-302_0-b9-b1-TooltipBallonWrapper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b1747a97-fba0-4fb3-b21e-7c0afc892e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-tooltip__balloon-wrapper osui-balloon osui-balloon--is-open osui-tooltip__balloon-wrapper--is-open bottom-end</value>
      <webElementGuid>b661e174-819b-4805-bf6f-bac287402f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uniqueid</name>
      <type>Main</type>
      <value>0.0xbockj1qy7f</value>
      <webElementGuid>38bb1bff-eb4a-4c11-9157-7f0c5840e1cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b15-l3-301_0-l3-302_0-b9-b1-TooltipBallonWrapper</value>
      <webElementGuid>fcc85b94-3bd0-4482-8027-d305ac1e900d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>f7a133a7-973e-48bc-b0e0-f373fa4466d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>08982759-232d-470f-a5f4-0cfa71d9e760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EditRemove </value>
      <webElementGuid>0485fc7a-8668-483f-a559-5b290ca373be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b15-l3-301_0-l3-302_0-b9-b1-TooltipBallonWrapper&quot;)</value>
      <webElementGuid>4fd7af25-57a5-431b-97a3-aeeea35e1356</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b15-l3-301_0-l3-302_0-b9-b1-TooltipBallonWrapper']</value>
      <webElementGuid>cac7ad1b-19b1-4092-86f5-18fc60dfc86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b15-l3-301_0-l3-302_0-b9-b1-TooltipWrapper']/div[2]</value>
      <webElementGuid>dfff3c9b-947b-4f95-b7ab-2d0e9edc437e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[3]/following::div[7]</value>
      <webElementGuid>9d905dcd-c82e-4520-8195-44a1e537db5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test question to ask'])[3]/following::div[8]</value>
      <webElementGuid>f6886d47-84b1-450f-9d18-71d2e60b39b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/article/div/div/div[2]/div/div/div/div[2]/div/div/div/div[3]/div/div/div/div[2]</value>
      <webElementGuid>38168483-0799-4705-9814-1064c6e817f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b15-l3-301_0-l3-302_0-b9-b1-TooltipBallonWrapper' and (text() = 'EditRemove ' or . = 'EditRemove ')]</value>
      <webElementGuid>f2c0339a-8b79-4636-ae46-082a86999c45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
