<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_3DS iFrame</name>
   <tag></tag>
   <elementGuidId>3f9a05a5-891c-4e80-a65a-3b9029b15502</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@title = '3DS Challenge']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-Title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>d19585de-dfc6-41be-925a-396a8e5bf2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>05a3ce93-1c83-4d44-84a8-22d4305f8e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b1-Title</value>
      <webElementGuid>b6823743-4d7e-4b74-a16a-bb81c8f51020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Giving cart </value>
      <webElementGuid>79a97efd-8567-492d-a759-0efdf08b9606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-Title&quot;)</value>
      <webElementGuid>f4b23c0a-2005-4191-add7-3dd17141eead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>3DS Challenge</value>
      <webElementGuid>0ec0ba23-cfb2-44d1-8717-1b8c2b283920</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-Title']</value>
      <webElementGuid>78f58cb8-03c1-480c-bc17-b88b1a32040a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-$b1']/div/div/div[2]</value>
      <webElementGuid>242ee507-7eba-47d8-930d-5d65773ec2d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[2]/following::div[19]</value>
      <webElementGuid>a147825e-0489-482d-946f-a88be0d186d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[2]/following::div[19]</value>
      <webElementGuid>af81e161-9a01-4c75-8fd6-161b5abdb035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enjoy tax benefits with your donations when you log in'])[1]/preceding::div[3]</value>
      <webElementGuid>d07567fa-436f-422e-82ce-864380fb0333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Giving cart']/parent::*</value>
      <webElementGuid>7ebfa1cb-b01b-4d74-8eb6-c029de9b0a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]</value>
      <webElementGuid>022ea834-c726-4e37-aa90-e36ef2e2d1a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b1-Title' and (text() = 'Giving cart ' or . = 'Giving cart ')]</value>
      <webElementGuid>1cf8b0a2-fbc8-4f1c-80cc-e3d6b9e7a875</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
