<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Enjoy tax benefits with your donations _40356b</name>
   <tag></tag>
   <elementGuidId>0bb180f9-8388-4115-9a01-981931e56c5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b2-Header']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b2-Header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>448a9907-b9af-49e0-84ac-57f669b9b42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart-info-box__header ph</value>
      <webElementGuid>fb5318a8-dc09-4bfb-b36b-6e171e36623d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b2-Header</value>
      <webElementGuid>7472b2bd-7027-46ca-b161-956de967981d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enjoy tax benefits with your donations when you log in</value>
      <webElementGuid>42dc2f2a-9ff3-41f8-85a8-544cf3f6ce9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b2-Header&quot;)</value>
      <webElementGuid>e78b1108-34d6-4787-a81b-8d066769e56e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b2-Header']</value>
      <webElementGuid>07311634-464c-4ccd-9b4e-13f4e45700ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b2-ContentContainer']/div</value>
      <webElementGuid>3216d523-2db1-4779-bdde-4e5d62cc89e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giving cart'])[1]/following::div[8]</value>
      <webElementGuid>7ac2c578-725e-47c5-a39c-3d2a338efd98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[2]/following::div[27]</value>
      <webElementGuid>e9e63bab-9477-44bb-8883-ac052e3072f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[3]/preceding::div[2]</value>
      <webElementGuid>44051041-4f18-416a-818f-42d5e9b3a8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enjoy tax benefits with your donations when you log in']/parent::*</value>
      <webElementGuid>48881fc1-1172-4c65-a62e-87b97a7123e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div[2]/div</value>
      <webElementGuid>403b6a12-7f63-4ccf-8070-1ecbb8c08abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b2-Header' and (text() = 'Enjoy tax benefits with your donations when you log in' or . = 'Enjoy tax benefits with your donations when you log in')]</value>
      <webElementGuid>21fb4124-38f0-4a7d-b3c2-a4c9c232861f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
