<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(DS) NPO 0001_b2-b11-l3-764_0-l3-765__a61625</name>
   <tag></tag>
   <elementGuidId>ae025673-34fe-4c61-b577-4af1ad6204ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b11-l3-764_0-l3-765_0-Checkbox5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b11-l3-764_0-l3-765_0-Checkbox5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c76d949a-cb81-412e-abca-b183460a88b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>85d477ae-a756-4ecc-90f4-5bb0301f75f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>52c7ebe0-e5b6-4f07-88cb-6ce5d2c95678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b11-l3-764_0-l3-765_0-Checkbox5</value>
      <webElementGuid>6c132fd5-b570-451d-afc2-10c66cb480eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ff8c6112-2add-40e2-8f03-271f9461d6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b11-l3-764_0-l3-765_0-Checkbox5&quot;)</value>
      <webElementGuid>41e7b217-8b91-478d-a75a-7a4133c47581</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b11-l3-764_0-l3-765_0-Checkbox5']</value>
      <webElementGuid>32d4185f-e198-4b19-931a-cb162591590b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b11-l3-764_0-l3-765_0-b4-Checkbox']/span/input</value>
      <webElementGuid>285deecb-e3db-4df3-a60b-623915246ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>223d63dc-4349-4c1f-b501-e0d0ff247973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b11-l3-764_0-l3-765_0-Checkbox5']</value>
      <webElementGuid>1caf327f-10b8-4dc7-ba8a-23bd8e756fa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
