<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(DS) NPO 0001_b2-b11-l3-768_0-l3-769__f4bdee</name>
   <tag></tag>
   <elementGuidId>dadb6179-cb4c-4a75-973c-e6a1a3fd6f42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b11-l3-768_0-l3-769_0-Checkbox5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b11-l3-768_0-l3-769_0-Checkbox5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ad303aa-9d8b-4cf8-a3b0-39a2b6c14746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dc47a6a6-c3da-4df1-8ad7-7860f00a9230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ab41a18b-969a-468b-99ff-f98cfce0d2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b11-l3-768_0-l3-769_0-Checkbox5</value>
      <webElementGuid>0e451efc-83eb-444a-ad3b-1961b56e0794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>afcc2ece-ef8c-4e07-94c6-e23b06ee14ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b11-l3-768_0-l3-769_0-Checkbox5&quot;)</value>
      <webElementGuid>fa0ed05f-73b5-49de-8b48-3ed69aa6a5d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b11-l3-768_0-l3-769_0-Checkbox5']</value>
      <webElementGuid>774ab867-c5b2-48a7-b0be-a7d0ed9f7710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b11-l3-768_0-l3-769_0-b4-Checkbox']/span/input</value>
      <webElementGuid>574c4bd9-30c7-467d-bb68-3f0ee4f3d388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3abf9765-23fd-40c5-9d8c-b486be97b462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b11-l3-768_0-l3-769_0-Checkbox5']</value>
      <webElementGuid>3e409b4d-b9a2-4841-8e1b-56ef8dd01809</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
