<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pay with_b2-b8-l1-537_0-RadioGroup</name>
   <tag></tag>
   <elementGuidId>48d8e7f2-7520-457a-92a1-dd294763c9d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@ktl-id='divExistingCard']/div/div/div/div/div/div/div/div/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b8-l1-537_0-RadioButton-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2608d7f9-babd-4d65-a5d5-910f890d68cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c0301f81-619b-410d-b0a6-bcfe5ad8adcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b8-l1-537_0-RadioButton-input</value>
      <webElementGuid>af65bfd7-3285-4872-b73f-7d7dfc5b5452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>cbbb9bf2-7326-4b59-9c3f-e33cba4df899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b2-b8-l1-537_0-RadioGroup</value>
      <webElementGuid>51aa4e24-ad89-4fce-8d9f-813e857c2d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>pm_1OJY1GA2ueNEMe8GZmXBMExW</value>
      <webElementGuid>4aff8e40-7aff-4f1a-8c46-0e4db76f3cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b8-l1-537_0-RadioButton-input&quot;)</value>
      <webElementGuid>c0b4102f-c32f-4031-9f36-0f4f98d91b9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b8-l1-537_0-RadioButton-input']</value>
      <webElementGuid>5b772797-89ec-4cfd-847b-31f15334b077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b8-l1-537_0-RadioButton']/input</value>
      <webElementGuid>7c351302-3be4-4c92-9e61-6cedcb212cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d981dcad-732b-456f-9436-97483b276d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b2-b8-l1-537_0-RadioButton-input' and @name = 'b2-b8-l1-537_0-RadioGroup']</value>
      <webElementGuid>ac5e857a-7f10-41ff-b1fe-c541d014972b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
