<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_b2-Input_Email</name>
   <tag></tag>
   <elementGuidId>17f54d1f-dfa9-42e4-833a-10699672ddd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-Input_Email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@ktl-id='inpGiverEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e27f7bfe-b1fd-47ea-9d47-4ea327c23333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>67a2d55d-1b5a-40e9-9ad5-a8ede797882f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>459de971-99cc-4d75-aa68-84eb56c58f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c9cfcdfb-d021-4b1a-940d-81604bdb476e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>aa3a3801-63f6-4bc7-9893-801b32175b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>b23688c3-44f2-4ec9-b2f1-58eda5f01396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-Input_Email</value>
      <webElementGuid>f2411eb1-b2ae-4765-89b2-d77f2d7a94ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-Input_Email&quot;)</value>
      <webElementGuid>459c2ddb-dbb0-4a2a-908e-23c8f41bd1a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-Input_Email']</value>
      <webElementGuid>bca9326f-1154-4eee-a00a-31c537a31422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b13-FieldContent']/span/input</value>
      <webElementGuid>eac05ff3-b2ee-4217-9ab2-1b68026e164b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/span/input</value>
      <webElementGuid>76acd5f9-33ad-452c-8959-772956d02b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'b2-Input_Email']</value>
      <webElementGuid>96bc7826-8f52-44a7-be40-91862fd451cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
