<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pay with_b2-b8-l1-537_0-RadioGroup_1</name>
   <tag></tag>
   <elementGuidId>7d13a52b-05f1-4c83-971e-665c8d10203b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b8-l1-537_0-RadioButton-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b8-l1-537_0-RadioButton-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e80102ed-00a2-4cea-81e2-8af8083e961c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>710deb88-cb0e-4f8f-8a29-99c7439fa354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b8-l1-537_0-RadioButton-input</value>
      <webElementGuid>7ff65944-92a1-45c9-9e9a-c1c16b1cadc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>19074b8a-2df5-411c-9dce-a9ff9873b24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b2-b8-l1-537_0-RadioGroup</value>
      <webElementGuid>d8aacb6b-e6b4-4c23-be15-8de5018921ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>pm_1OJY1GA2ueNEMe8GZmXBMExW</value>
      <webElementGuid>0c90c07d-2afd-4f75-9c66-40ac24a3d0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b8-l1-537_0-RadioButton-input&quot;)</value>
      <webElementGuid>4f5bf469-789d-4b6f-abd0-564864959897</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b8-l1-537_0-RadioButton-input']</value>
      <webElementGuid>6299f9dd-f792-4c03-aecf-6650d9639e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b8-l1-537_0-RadioButton']/input</value>
      <webElementGuid>17c3de87-7e0c-43f1-a082-59fa4fc26543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b2560dff-3b47-45ec-820b-33f726bdc08b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b2-b8-l1-537_0-RadioButton-input' and @name = 'b2-b8-l1-537_0-RadioGroup']</value>
      <webElementGuid>aa4ea3d7-127e-47a2-a174-d546d9ab9af8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
