<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>2d9eb738-bc53-43c9-984e-712e19472a0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b13-l3-428_0-l3-429_0-b4-Checkbox > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b13-l3-428_0-l3-429_0-b4-Checkbox']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>88e9883d-205d-4ef1-9b00-8db68469e293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b13-l3-428_0-l3-429_0-b4-Checkbox&quot;)/span[1]</value>
      <webElementGuid>b14cbe1b-35d5-4935-9a26-b7eb9a70033e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b13-l3-428_0-l3-429_0-b4-Checkbox']/span</value>
      <webElementGuid>aa715ca7-232a-4d69-a79d-315d862f5bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(DS) NPO 0002'])[1]/following::span[1]</value>
      <webElementGuid>76cea6fe-61aa-43a3-a9e5-e025ba9d32f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[1]/following::span[2]</value>
      <webElementGuid>9677f7e7-d50a-4d44-8688-8b8bb216280a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(DS) NPO 0002'])[2]/preceding::span[1]</value>
      <webElementGuid>bdb960d7-caa2-43c1-8e46-64756e95fa33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[2]/preceding::span[2]</value>
      <webElementGuid>a3970117-8698-41e0-9968-296fe2a19892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div/div[2]/div/div/div/div[2]/div/div/div/div/span</value>
      <webElementGuid>59970831-e2d8-46dd-961f-6fdb421dc96d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
