<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Duplicate</name>
   <tag></tag>
   <elementGuidId>9b97afb4-296f-449f-9197-ec951d902cf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b40-l1_0-240_0-b13-Items']/a[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'lnkDuplicate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b40-l1_0-240_0-b13-Items > a:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fb312e9c-d9f4-4f2f-a77e-57165bbcf50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5689bbe8-9624-42fa-b274-23ff971a657b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>lnkDuplicate</value>
      <webElementGuid>cba62d2c-2b02-499f-ab07-111873fc208c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Duplicate</value>
      <webElementGuid>d030ede7-99ff-4b74-a67a-300e50f738a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b40-l1_0-240_0-b13-Items&quot;)/a[3]</value>
      <webElementGuid>1ee283ee-df2d-419e-b4c1-c8218a9e8f93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b40-l1_0-240_0-b13-Items']/a[3]</value>
      <webElementGuid>880f71bb-04a1-4647-945e-adeb14e29cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::a[1]</value>
      <webElementGuid>d3dde327-1c31-4dc0-afb4-e7feb196a040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/following::a[2]</value>
      <webElementGuid>2260204e-03cc-4340-befc-3751abd894fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[1]/preceding::a[1]</value>
      <webElementGuid>d4322a1f-3c8e-4e22-b589-1dce4eafdc64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[11]</value>
      <webElementGuid>dc72ee23-1d64-448d-a2f5-90998ccc2695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a[3]</value>
      <webElementGuid>610619f2-26d2-4016-8661-92a71f9e8bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Duplicate' or . = 'Duplicate')]</value>
      <webElementGuid>ac0a7c9b-299e-4759-a371-1fe2fec8d37b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
