<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SwitchGiverPortal</name>
   <tag></tag>
   <elementGuidId>7a9f3cf7-33be-4124-b019-d277d1affe85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@ktl-id=&quot;btnSwitchGiverPortal&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa-solid.fa-hand-holding-heart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>76470ae8-d968-4bc1-8b8f-670f896bac23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-solid fa-hand-holding-heart</value>
      <webElementGuid>6599e8ec-5a36-4f71-8a9a-3c0f1309cd53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-b1-PortalSwitch&quot;)/div[@class=&quot;hide-if-phone&quot;]/a[@class=&quot;icon-box&quot;]/i[@class=&quot;fa-solid fa-hand-holding-heart&quot;]</value>
      <webElementGuid>fbd14a91-e00c-4857-b5b9-dae4ca475c83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-b1-PortalSwitch']/div/a/i</value>
      <webElementGuid>bec98456-3446-4f3c-8e33-1a7fee679814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/a/i</value>
      <webElementGuid>a93b5cbe-d4ae-49cb-8cd1-8ffd872eba8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
