<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Your August overview</name>
   <tag></tag>
   <elementGuidId>465f29a1-039c-472e-9b00-a68fa15329e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b1-Title']/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Your August overview' or . = 'Your August overview')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-Title > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9d8bfb6a-edcf-4088-8eaa-1654a7554a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your August overview</value>
      <webElementGuid>2446975e-5240-4d73-b126-7943a9ac5275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-Title&quot;)/span[1]</value>
      <webElementGuid>b214b4bd-3fb7-46e0-8682-a85542f82e97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-Title']/span</value>
      <webElementGuid>5be9a343-4680-4e8a-950a-05e372a942a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::span[1]</value>
      <webElementGuid>f77675ca-b5c4-421d-8389-04fcc43a696e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giving.sg'])[1]/following::span[1]</value>
      <webElementGuid>4ff91dde-42e0-4473-b5a1-5ad5130a06d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaigns'])[2]/preceding::span[1]</value>
      <webElementGuid>a80453e3-d38c-4628-9703-5182218a2977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donating statistics'])[1]/preceding::span[2]</value>
      <webElementGuid>a31d6e14-9361-4396-9a8e-273f496b1445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Your August overview']/parent::*</value>
      <webElementGuid>709d4950-eacf-46b1-a41c-e9e2ccbac4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>6866baa6-3ebb-4213-8204-ee9ca64a46f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Your August overview' or . = 'Your August overview')]</value>
      <webElementGuid>3872ca48-5ae5-4858-a54f-4cf371dfe750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/span</value>
      <webElementGuid>45350733-7052-4031-a2d1-695a76385fe3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
