<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Start date_icon fa fa-calendar fa-1x</name>
   <tag></tag>
   <elementGuidId>67398a3d-e32a-4f86-9928-e727a897fc4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-calendar.fa-1x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b20-b3-Icon']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bd5f62e2-affb-4686-927e-bf3763a7c322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-calendar fa-1x</value>
      <webElementGuid>88186d2d-0cf6-419a-895c-8624f1c16af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b20-b3-Icon&quot;)/i[@class=&quot;icon fa fa-calendar fa-1x&quot;]</value>
      <webElementGuid>f5413737-e50a-444d-a117-668ee124ca65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b20-b3-Icon']/i</value>
      <webElementGuid>61a35782-accd-40cc-8bbc-6ace653d2067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/i</value>
      <webElementGuid>d1c0a5d7-c505-4d9c-a1dc-73acdc884b57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
