<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inp_CampaignURL</name>
   <tag></tag>
   <elementGuidId>0bd2ef67-f3fd-4964-90f8-6b4441253e4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b3-b4-Input_CampaignURL']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'inpCampaignURL']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b4-Input_CampaignURL</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f0f933c-28ef-4927-ae81-460af4b7c723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>6c8245eb-51e9-4c5b-aa35-a980b9f10737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f232ee5-c14b-4167-922b-8413302c7f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>58ee1c24-57e9-46ec-886d-2d806f6471e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>28a9d7a5-01a0-4955-bbef-0e1232c56447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inpCampaignURL</value>
      <webElementGuid>16635cb1-9488-493f-b88e-d4f4ab6d764c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>coco</value>
      <webElementGuid>c45ec268-6375-4209-b818-75584a1e4e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b4-Input_CampaignURL</value>
      <webElementGuid>1911ea23-cf7b-4fc1-9215-01aca36a3a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b4-Input_CampaignURL&quot;)</value>
      <webElementGuid>765cff6a-a30e-46c2-ae2c-89626cb236be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b4-Input_CampaignURL']</value>
      <webElementGuid>60301335-273d-4fee-8bf8-472ccb1ea5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b4-b8-FieldContent']/span/input</value>
      <webElementGuid>eccd05eb-cf29-4dac-8e61-bc567587ef9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[3]/span/input</value>
      <webElementGuid>3cdf1bdd-aae0-4f3d-b339-dce4ba911c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b3-b4-Input_CampaignURL']</value>
      <webElementGuid>7882b916-f702-487b-a464-96d26f53800b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
