<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Select file (1)</name>
   <tag></tag>
   <elementGuidId>fd9b3c47-d824-4231-a53f-c3f1c3f93f27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='b3-b4-b11-Upload_Image']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b4-b11-Upload_Image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a2270674-e51b-4b1e-b73d-a07f8a40ab32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>&quot;upload&quot; OSFillParent</value>
      <webElementGuid>f875a243-d6ae-45a4-a556-a171d54365d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.jpeg,.png,.jpg,.gif,.jpe,.jfi,.jfif,.jif</value>
      <webElementGuid>aa8c3169-8daf-4b50-80f3-cb9dd4ef9a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b4-b11-Upload_Image</value>
      <webElementGuid>7e549303-7779-473a-8f23-b1c1bf0cfd60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select file</value>
      <webElementGuid>d8132494-241f-4074-acfc-a0f82ac25a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b4-b11-Upload_Image&quot;)</value>
      <webElementGuid>6c78fd11-0106-45ea-a3fc-fb85e0c9363a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='b3-b4-b11-Upload_Image']</value>
      <webElementGuid>ca5c66e3-46a3-4105-aa0d-1c06744c2493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b4-Assetupload']/div/div[2]/span/label</value>
      <webElementGuid>6c6a11a8-56d1-4e9a-9c37-0bd74a07f469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[4]/following::label[1]</value>
      <webElementGuid>6961e888-ff8a-402b-9e87-65d197fffdc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recommended size: 1440 x 810 | JPG, PNG, GIF. Max size: 5MB'])[1]/preceding::label[1]</value>
      <webElementGuid>9bcf19e1-2b9a-4120-81d4-f5620c18e377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/label</value>
      <webElementGuid>76a499db-07e8-4d98-a8d0-74cc54b43344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'b3-b4-b11-Upload_Image' and (text() = 'Select file' or . = 'Select file')]</value>
      <webElementGuid>944399ad-c875-4411-8631-beb5de2dcac4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
