<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unit_b2-b6-Input_UnitNumber</name>
   <tag></tag>
   <elementGuidId>0427bbce-f5ab-4a70-b458-ca8015d20903</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b6-Input_UnitNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b6-Input_UnitNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5c7beb0-4187-443a-9a0d-c7459b965689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>96f2c427-e347-4fc3-ace6-707de27c82ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da129f69-ca08-4b2b-b97f-c1fe7a9009d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4923b080-c21e-4c9d-b28c-d73639e1d823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inpUnitNumber</value>
      <webElementGuid>8bbbb144-30d9-4ad7-a639-efaf65cb49be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b6-Input_UnitNumber</value>
      <webElementGuid>b955f3dd-8731-4972-9057-b6dd70555879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b6-Input_UnitNumber&quot;)</value>
      <webElementGuid>599db748-9192-4f5b-9eba-5a383bf548a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b6-Input_UnitNumber']</value>
      <webElementGuid>8bb30aea-0090-4d03-83fc-7337c29b8bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b6-b27-UnitInput']/span/input</value>
      <webElementGuid>1a3056c2-6266-4754-b22e-d8d983fc7b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/div[3]/div/span/input</value>
      <webElementGuid>a4c3ccce-b5ee-4134-b1d9-9f3e684e7ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b2-b6-Input_UnitNumber']</value>
      <webElementGuid>5604e468-deec-4b1f-9d14-93f78a76a2bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
