<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search point of contact</name>
   <tag></tag>
   <elementGuidId>d1116168-0555-4ecf-8e32-bbcee21a5a4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vscomp-search-input-9366']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @class = 'vscomp-search-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vscomp-search-input-9366</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24190b04-ca2c-499d-9b08-b7a057f23b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79ade6a3-cc21-49e1-baa6-1ee9ffd3ec46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vscomp-search-input</value>
      <webElementGuid>f23f8080-b303-4933-b30f-998ac75fc9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>ef7e531d-47e6-44a1-8ac4-73d3669dc7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vscomp-search-input-9366</value>
      <webElementGuid>1da5841e-9bc9-4a29-87fe-1da859f8eccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;vscomp-search-input-1026&quot;]</value>
      <webElementGuid>e86978f1-e08d-49e7-95af-7f75293cdc25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vscomp-search-input-9366']</value>
      <webElementGuid>16e67b7a-9157-430e-ada3-55e953dd9b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vscomp-dropbox-container-9366']/div[2]/div/div/input</value>
      <webElementGuid>3a52ed05-3b2c-4318-a77a-3d677d4f516a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>2867182a-7b8f-43b5-9d91-9daef67967aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search...' and @id = 'vscomp-search-input-9366']</value>
      <webElementGuid>c0ac26a4-ff1c-4ca1-8419-bd7ab0c3a74f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
