<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_No, Im not</name>
   <tag></tag>
   <elementGuidId>1643a46b-e297-4440-a2b5-475a4fbd6b6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b4-b2-Cancel_Btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@ktl-id='btnNotExistingUser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ace5305a-4f04-4d74-bc84-f1ee51f33556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>c02d3097-02cc-4431-9bc2-6fb0d3f8ada2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9be8cfc6-411c-43b9-bf42-cd309f91d60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-b2-Cancel_Btn</value>
      <webElementGuid>1546386e-fcdb-4cf4-9ca9-b51ecdc9b7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No, I'm not</value>
      <webElementGuid>ebd940d5-aa2b-4e28-9e3d-00d4401739da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b2-Cancel_Btn&quot;)</value>
      <webElementGuid>ec3c0611-a4e8-453f-b302-e72b8c8805aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b4-b2-Cancel_Btn']</value>
      <webElementGuid>99c72bbc-7b06-4807-a824-b1caa23725fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b2-b3-Left']/button</value>
      <webElementGuid>f2324a3e-599d-4fa0-9b6b-ede3b55c087b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address'])[1]/following::button[1]</value>
      <webElementGuid>c9af1505-bc7c-4e8e-8ff3-ca269cf29cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If you have an account you want to associate with this Singpass, enter your email now.'])[1]/following::button[1]</value>
      <webElementGuid>e6d86531-905e-4115-b282-d0430606512c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::button[1]</value>
      <webElementGuid>00b88ccd-d34f-44d9-a4fc-c1baae896235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>9bbf6331-c14e-4c32-9569-1ff82e5e26ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b4-b2-Cancel_Btn' and (text() = concat(&quot;No, I&quot; , &quot;'&quot; , &quot;m not&quot;) or . = concat(&quot;No, I&quot; , &quot;'&quot; , &quot;m not&quot;))]</value>
      <webElementGuid>5538901b-8e5a-4d53-9e8d-2c772b813c02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
