<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Human resource_b2-b3-ConsentGiven_Checkbox</name>
   <tag></tag>
   <elementGuidId>f17ce847-fab8-4808-bb39-b2032b3bd6e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b3-ConsentGiven_Checkbox']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'chkConsentGiven']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b3-ConsentGiven_Checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f23f40ad-128b-44b2-9ee4-cbef7fe424db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7b233dcd-61cc-485a-a777-30d08f038adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a89ebe41-a155-4ee3-8e6b-67d837b75372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>chkConsentGiven</value>
      <webElementGuid>57f29f43-3771-4c0c-adcf-deebf9b90626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b3-ConsentGiven_Checkbox</value>
      <webElementGuid>77ace034-dd77-4b07-9fa0-13758795732e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b3-ConsentGiven_Checkbox&quot;)</value>
      <webElementGuid>df2cce2c-5c8c-43c3-96b2-4d94aaf7ba1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b3-ConsentGiven_Checkbox']</value>
      <webElementGuid>bf2181a1-1083-482f-95f5-b55bfcf993b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b3-b21-Control']/span/input</value>
      <webElementGuid>5512f57c-dc99-4cd9-bf6e-7bc5d1dc5f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/span/input</value>
      <webElementGuid>672d148b-e7c8-449f-9aae-70e7f50189b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b3-ConsentGiven_Checkbox']</value>
      <webElementGuid>6f402f26-0334-451c-8c00-ac93dff18b76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
