<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Test Rejecti</name>
   <tag></tag>
   <elementGuidId>ab9c6780-63c4-45f5-82df-3219347d3c39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='b2-TextArea_RejectionReason']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-TextArea_RejectionReason</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>274916fe-509b-4df1-becc-db5dbc6b2090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>518e4e44-b24b-4c12-860c-1fcc42706eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b7c17f68-8cee-4b6d-9f49-eaa58d71f46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>f96196a0-a7c5-4059-952e-258233c9125a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>InpRejectionReason</value>
      <webElementGuid>9dfb4d85-deeb-44ee-a4f5-aa055af56805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-TextArea_RejectionReason</value>
      <webElementGuid>7ba43ca0-44ba-448c-b78f-2a84b6e2bc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test Rejecti</value>
      <webElementGuid>65fa2371-fe5c-4a7a-8c3f-29c2b8cb3e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-TextArea_RejectionReason&quot;)</value>
      <webElementGuid>81e45a54-db62-4fa5-bb67-67f6d682f961</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b2-TextArea_RejectionReason']</value>
      <webElementGuid>5e715321-56ba-40eb-8bde-d7337bb7bf26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b32-FieldContent']/span/textarea</value>
      <webElementGuid>657dca75-aec4-478e-b0ba-f062edb762d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rejection reason'])[1]/following::textarea[1]</value>
      <webElementGuid>911af460-cd9d-410e-bb13-bd4b089a2d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Groundup admin will receive a notification on the rejection reason.'])[1]/following::textarea[1]</value>
      <webElementGuid>f84b7fbf-759e-4e2a-ba12-d595321ec081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::textarea[1]</value>
      <webElementGuid>89daf24e-2ba5-4133-a6b0-845faa55c1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject'])[2]/preceding::textarea[1]</value>
      <webElementGuid>db180c7a-0818-46d2-b0dd-30880534640d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test Rejecti']/parent::*</value>
      <webElementGuid>02cdeb5c-d364-4aa1-88a0-86cc272e8123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>2e7e876c-6d1e-416c-a556-a932d2641497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@ktl-id = 'InpRejectionReason' and @id = 'b2-TextArea_RejectionReason' and (text() = 'Test Rejecti' or . = 'Test Rejecti')]</value>
      <webElementGuid>7fcb579e-d5f6-4103-9ad9-b39ffa877a7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
