<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Test Rejec</name>
   <tag></tag>
   <elementGuidId>d1832ea7-0d22-44b9-ad1d-ea457ba0f16c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='b2-TextArea_RejectionReason']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-TextArea_RejectionReason</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0e13b314-45cd-416e-beef-e19f13139805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>d24f4314-c767-41ee-a25a-5e378905c319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b9111b81-88d7-47fc-a431-f57563ba23fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>7a9bba5a-a1c5-467e-b95c-ad4e2edbdd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>InpRejectionReason</value>
      <webElementGuid>aadae141-796d-46eb-bf09-17204b1f4b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-TextArea_RejectionReason</value>
      <webElementGuid>6930a28c-ceab-4b2a-a35f-d14618da54ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test Rejec</value>
      <webElementGuid>9e8bde8c-970e-4dca-8b6f-98822d58fc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-TextArea_RejectionReason&quot;)</value>
      <webElementGuid>4a135c2a-7add-4646-bea6-5302e7ed15fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b2-TextArea_RejectionReason']</value>
      <webElementGuid>9e8d4ba0-9278-4e42-b624-3476936afa92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b32-FieldContent']/span/textarea</value>
      <webElementGuid>9e354f5d-cde5-4740-b763-12a14c3d73b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rejection reason'])[1]/following::textarea[1]</value>
      <webElementGuid>55229a5e-8ba1-4722-bc32-060ddf44071e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Groundup admin will receive a notification on the rejection reason.'])[1]/following::textarea[1]</value>
      <webElementGuid>b0a7aa88-de31-4fef-b811-19be2aee30d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::textarea[1]</value>
      <webElementGuid>8fa18ae3-d691-4563-99c8-606ae82d67e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject'])[2]/preceding::textarea[1]</value>
      <webElementGuid>cae0e540-6718-4368-882d-d8c3bd73100b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Test Rejec']/parent::*</value>
      <webElementGuid>7ccf4833-c325-4273-9e5d-17f144d3a9de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>00278043-f5b3-4c0a-9281-0f0e48f41597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@ktl-id = 'InpRejectionReason' and @id = 'b2-TextArea_RejectionReason' and (text() = 'Test Rejec' or . = 'Test Rejec')]</value>
      <webElementGuid>237920ce-e699-4031-9268-6e90d7898e67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
