<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__b3-b4-b6-Input_Value</name>
   <tag></tag>
   <elementGuidId>fbb6002d-5760-478c-819c-b8195e8f6f70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'number-picker-input OSFillParent' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b4-b6-Input_Value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b3-b4-b6-Input_Value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0855a8a-18a8-44a4-83a8-fc10e8fe3781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number-picker-input OSFillParent</value>
      <webElementGuid>22693af7-1d3e-4699-9c2d-b72a90a426d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84227760-22c1-4011-9505-c2078419bfa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>242dd05f-881a-4dc6-b295-b6d4c5ec17cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5f8686a7-0743-4ff6-9999-362984e58b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b4-b6-Input_Value</value>
      <webElementGuid>defa7d17-4a0f-4f6c-bb13-8626b35d278b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b4-b6-Input_Value&quot;)</value>
      <webElementGuid>517a3702-807c-4156-88f8-b9f93b8e9a4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b4-b6-Input_Value']</value>
      <webElementGuid>7052d1c2-955e-4043-b80c-afdaaf445dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b4-$b6']/div/span/input</value>
      <webElementGuid>e5aa2640-e2a9-493a-94f0-f4362ed7febe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span/input</value>
      <webElementGuid>e91256da-8def-41a8-ab79-118ef4596cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b3-b4-b6-Input_Value']</value>
      <webElementGuid>99f43b91-2732-47d2-9445-4bbd020b370f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
