<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Allow others to fundraise</name>
   <tag></tag>
   <elementGuidId>1afdd530-1cfb-4bef-9ca1-2fd6797cd7cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b36-Switch_IsSubCampaings']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'chkSubCampaign']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b36-Switch_IsSubCampaings</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>326e36b8-d747-435d-bd0f-43b7bc3fe4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>f3f1365f-84d7-4dd5-ab12-1b646630d009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8a672d3d-250d-4428-8779-5b6a633ef3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b36-Switch_IsSubCampaings</value>
      <webElementGuid>db116d00-25b3-4051-a6f2-1d1289ec03bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b36-Switch_IsSubCampaings&quot;)</value>
      <webElementGuid>d2beb472-8bf5-42d1-a719-6ad5327ecb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>chkSubCampaign</value>
      <webElementGuid>33d521f9-2a34-47aa-b523-5db5e5819960</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b36-Switch_IsSubCampaings']</value>
      <webElementGuid>09cacfd0-0142-47fb-83c2-3d7355947e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b36-b21-Switch']/span/input</value>
      <webElementGuid>280be63f-cfc5-48fe-aefc-f55601ceb2b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/span/input</value>
      <webElementGuid>795afc80-008d-4557-8ac2-ac0b8c00f097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b36-Switch_IsSubCampaings']</value>
      <webElementGuid>d3109c50-f34a-49ad-9861-1917faeaa3b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
