<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start date</name>
   <tag></tag>
   <elementGuidId>c4571971-ccf4-4668-863d-a2ca515c2819</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@ktl-id='inpStartDate']/following-sibling::input[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'inpStartDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.OSFillParent.input.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c48d1f48-a435-494c-9597-80005b6ed1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent input active</value>
      <webElementGuid>fc2f86a5-dd58-459f-b3c7-cd9f7105bd50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8542c3bb-7515-425b-af2c-531ce103600e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8fc2218f-a33b-48bc-895d-4a0e0f3097b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>12f9e956-1806-41d9-8ef4-28374d452cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0c450962-1157-4be4-a13f-9cbc837a77af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>58268edf-356c-4089-864b-a067efe9d009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ad992263-fa8a-40c3-8f4e-64fa8e334276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>af3e3447-5cee-4e70-ad7b-4691c6c3145d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>flatpickr-calendar-0.y58fihvrszs</value>
      <webElementGuid>23063124-e55a-4082-baba-aeb5b808d859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select a date.</value>
      <webElementGuid>66e278d2-0c37-446e-ad69-ea0d1cc125f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>b2-b20-b4-DatepickerAccessibilityInfo</value>
      <webElementGuid>f6312f1b-5d88-40e4-8730-18e2edf6d47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b20-b4-Datepicker&quot;)/span[@class=&quot;input-date&quot;]/div[@class=&quot;flatpickr-wrapper&quot;]/input[@class=&quot;form-control OSFillParent input active&quot;]</value>
      <webElementGuid>fdd59d92-d61d-4cb4-a6ec-75f3170c27a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inpStartDate</value>
      <webElementGuid>099689db-3045-405d-ac07-82070a7955bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>0e229b95-f881-4c54-a807-8c26b3cc29c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//input[@ktl-id='inpStartDate']/following-sibling::input[1]&#xd;
</value>
      <webElementGuid>354532e3-56f9-4c85-831d-9385f75bd952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>3c50e88e-3cde-4776-847b-9fdac6e96d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>926b48c9-4a60-448a-8ef9-69ef9b027220</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
