<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_vscomp-search-input-2987</name>
   <tag></tag>
   <elementGuidId>578dfe73-ce89-474b-b360-5aa115be5b69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vscomp-search-input-2987']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vscomp-search-input-2987</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>834771a5-9645-4d60-856a-8fdc696c2a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4829a22c-bc55-4215-8a1b-13cd3476fea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vscomp-search-input</value>
      <webElementGuid>dad288de-fbc9-4b3d-a231-1d127e0ae19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>1ca5246a-bbf9-490f-a750-ea9fe0ea41c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vscomp-search-input-2987</value>
      <webElementGuid>5ceeca03-a975-44e1-ba62-c056e4d5ce29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vscomp-search-input-2987&quot;)</value>
      <webElementGuid>9acbce5d-785b-4d95-b0be-305d5f23dd84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vscomp-search-input-2987']</value>
      <webElementGuid>cba5c368-c862-4cc3-8aa2-000b16e117b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vscomp-dropbox-container-2987']/div[2]/div/div/input</value>
      <webElementGuid>4dff9a2b-507c-44a0-acde-ab1c2f87679e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>e9b4d3a5-c19a-4d6c-adff-403c66af98ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search...' and @id = 'vscomp-search-input-2987']</value>
      <webElementGuid>82378a01-654b-4862-bc20-40a36c249df8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
