<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Select file (1)</name>
   <tag></tag>
   <elementGuidId>c0a9b548-b9e0-488e-a1c2-be67b7daf9d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-b4-b11-Upload_Image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='b3-b4-b11-Upload_Image']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>00ef859e-fa99-4b1d-9e5e-2e69d848544b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>&quot;upload&quot; OSFillParent</value>
      <webElementGuid>25a63cdd-1bd6-455b-8597-b0a7805bb3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.jpeg,.png,.jpg,.gif,.jpe,.jfi,.jfif,.jif</value>
      <webElementGuid>1f2ce0c5-ce30-44a2-8305-50b3ef47d225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b4-b11-Upload_Image</value>
      <webElementGuid>fdbf43f8-2f65-40a4-bbc9-8ef11428357d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select file</value>
      <webElementGuid>4907bf0b-e9ed-4939-8479-b880544c1127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b4-b11-Upload_Image&quot;)</value>
      <webElementGuid>7a201db9-35e7-4f9d-aaa8-f05c2f93f38c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='b3-b4-b11-Upload_Image']</value>
      <webElementGuid>65589f07-e95d-4fcb-a48e-2302f66c79ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b4-Assetupload']/div/div[2]/span/label</value>
      <webElementGuid>a0897f7c-1dda-4c59-afb6-90ac37046fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[4]/following::label[1]</value>
      <webElementGuid>0e0016ba-d54d-4383-9e85-d0918e10b3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recommended size: 1440 x 810 | JPG, PNG, GIF. Max size: 5MB'])[1]/preceding::label[1]</value>
      <webElementGuid>33633a58-0d36-4440-ac66-99287aad8f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/label</value>
      <webElementGuid>290a4799-1c4e-491a-a9d2-b698d9755e75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'b3-b4-b11-Upload_Image' and (text() = 'Select file' or . = 'Select file')]</value>
      <webElementGuid>c53cff0c-eade-4d5a-b59e-93385ec7ba64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
