<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Impact statement (Optional)_b2-b28_dc79b8</name>
   <tag></tag>
   <elementGuidId>3ae0c7ba-0d82-44bf-b0e1-17be08fe2b26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='b2-b28-b13-TextArea_Description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b28-b13-TextArea_Description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9ec4103d-07d6-4649-a734-de3ea1b9f273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>112bf013-ebb2-4a8d-9dba-894f61e88dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>1274c71c-f236-42c6-9f47-decd0f9dcb08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>b6aed6fe-5ff7-4ebe-9f0a-bf10ac61665b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b28-b13-TextArea_Description</value>
      <webElementGuid>4f5d3153-333b-405e-b0ce-33b3e407a5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b28-b13-TextArea_Description&quot;)</value>
      <webElementGuid>27fa5c9a-866a-4716-9b3b-8209f3439992</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b2-b28-b13-TextArea_Description']</value>
      <webElementGuid>31bd62db-7b2c-43b5-802e-8753332ca9c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b28-b13-b5-TextArea']/span/textarea</value>
      <webElementGuid>cf5cf339-fc49-4498-9a7d-663169103013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>cf0e3feb-20fa-4394-a8ef-441fe1392652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b2-b28-b13-TextArea_Description']</value>
      <webElementGuid>7418c092-9b43-48cb-87f9-e6c49adbb4ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
