<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CharityName</name>
   <tag></tag>
   <elementGuidId>37352f47-9435-4cff-a870-468815944372</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'spanCharityName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b9-l4-323_0-b23-Title > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b9-l4-323_0-b23-Title']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>769cc8b5-93ce-49da-ad70-51c543fdfae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>npo without ipc</value>
      <webElementGuid>990ec231-5640-4802-b8f6-64ed31a839fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b9-l4-323_0-b23-Title&quot;)/span[1]</value>
      <webElementGuid>c2b02ebb-9ad5-4a06-8496-040f0c985d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>spanCharityName</value>
      <webElementGuid>b5e7e693-60fb-4ea3-8e67-0473e2bfe22c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b9-l4-323_0-b23-Title']/span</value>
      <webElementGuid>53519d18-bd21-44e4-a3b3-d270e2c6cd9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results per page'])[1]/following::span[3]</value>
      <webElementGuid>6b279ee0-fcc2-41b0-868a-137d302b1e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unity Cares Association'])[1]/preceding::span[1]</value>
      <webElementGuid>d6da8650-ab85-43aa-a453-8c9476f1c76a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$10 raised of $4,000'])[1]/preceding::span[2]</value>
      <webElementGuid>7239b3cc-432a-4cf3-a5c2-2d43d30354d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='npo without ipc']/parent::*</value>
      <webElementGuid>cc50ed0c-38a8-4cdf-8cfd-2d3f900c562e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/span</value>
      <webElementGuid>0b783409-7f4b-4bff-bf83-6fc5068a3861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'npo without ipc' or . = 'npo without ipc')]</value>
      <webElementGuid>6778aa95-e08d-4c26-922c-f2bcebe437fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
