<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_IPC end date_b4-b3-b20-b1-Icon</name>
   <tag></tag>
   <elementGuidId>d4926b49-3ed9-4fd8-8c55-ceda247efccb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b4-b3-b20-b1-Icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b4-b3-b20-b1-Icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#b4-b3-b20-b1-Icon</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>996f8431-538a-46be-ab8e-81efb7d6b2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-with-icon-content-icon center ph</value>
      <webElementGuid>ff1bf10e-ea9e-4c0c-9eb9-2ff2d58d085f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-b3-b20-b1-Icon</value>
      <webElementGuid>fb4be6b7-8f22-4bf9-bbcd-544200b4e783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b3-b20-b1-Icon&quot;)</value>
      <webElementGuid>0b5d13c2-00ec-4c4f-8b3e-26fa92302c60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b4-b3-b20-b1-Icon']</value>
      <webElementGuid>429d84f2-cbd4-4f61-a79f-2371537c5b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b3-b20-b1-InputWithIconWrapper']/div</value>
      <webElementGuid>5e322087-5c91-46d3-8f89-d958b2bf08f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IPC end date'])[1]/following::div[8]</value>
      <webElementGuid>c4c10722-05cb-4c4c-a0c5-017018708b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use cmd or ctrl + up/down arrow keys to navigate through years;'])[1]/following::div[13]</value>
      <webElementGuid>f41c2748-bf37-4d5b-b862-aa63dec88104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use cmd or ctrl + down arrow key to navigate into calendar context;'])[2]/preceding::div[3]</value>
      <webElementGuid>160db05d-dd68-472d-9bb1-f537523f3fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use arrow keys to navigate through calendar days;'])[2]/preceding::div[3]</value>
      <webElementGuid>e9497331-551b-4644-970a-ef86baf34712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div[3]/div/div/div/div/div</value>
      <webElementGuid>0907e9a7-dba3-4556-ac9e-8b624a148a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b4-b3-b20-b1-Icon']</value>
      <webElementGuid>f7945c37-d507-48f5-bae3-cb6574204af7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
