<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Password_b4-b5-b17-b1-b1-Icon</name>
   <tag></tag>
   <elementGuidId>90926623-7987-4ee8-8fb7-246c173a565a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b4-b5-b17-b1-b1-Icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b4-b5-b17-b1-b1-Icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#b4-b5-b17-b1-b1-Icon</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3f340bc9-5abb-462e-93df-c538473b00c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-with-icon-content-icon center ph</value>
      <webElementGuid>f560db4e-86f3-41eb-98d0-4d5412e77cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-b5-b17-b1-b1-Icon</value>
      <webElementGuid>8c5078c3-a73b-4b36-a2fd-a6088928ad7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b5-b17-b1-b1-Icon&quot;)</value>
      <webElementGuid>8f629678-d38e-46fa-9246-e473f69332fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b4-b5-b17-b1-b1-Icon']</value>
      <webElementGuid>db837632-9cab-43ed-b2da-c6d13551b4c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b5-b17-b1-b1-InputWithIconWrapper']/div</value>
      <webElementGuid>417a5623-3c62-4fd8-a07f-406029daa369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::div[9]</value>
      <webElementGuid>4858bf0e-0c8d-4414-8c10-52f6dd98bfbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work email'])[1]/following::div[17]</value>
      <webElementGuid>931b7f89-8e6f-4e5d-9cb4-85f7277ebc57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Have at least 12 characters'])[1]/preceding::div[7]</value>
      <webElementGuid>b769a09f-52f8-4ef2-b36d-fb52e32b1f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/div/div/div/div</value>
      <webElementGuid>c9b41e71-f40d-4326-a980-239f668ce956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b4-b5-b17-b1-b1-Icon']</value>
      <webElementGuid>31a58d18-584b-4db8-8724-64a4f8fbdf52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
