<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unit_b4-b2-Input_Unit (1)</name>
   <tag></tag>
   <elementGuidId>1a9ac7b1-2f64-46ee-9087-bc79781aa2f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b4-b2-Input_Unit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b4-b2-Input_Unit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Unit&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e4d6240d-a1ec-4026-8380-7be48e0311fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>fab76bb6-f9fe-42fb-9327-60ff7781211f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a5e1f609-570e-412a-b1a1-d2b05ed6529d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>823a4c5b-6cd2-4076-bcc1-e78747a4ca1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>b4-b2-Input_Unit_DescribedBy</value>
      <webElementGuid>f1d91565-fbeb-4424-a21f-382ff9b40ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-b2-Input_Unit</value>
      <webElementGuid>c0441646-9720-4570-bd83-34a07753782b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b2-Input_Unit&quot;)</value>
      <webElementGuid>70c7c8b8-6bd0-4c99-9533-13ea3267d84a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b4-b2-Input_Unit']</value>
      <webElementGuid>474eb144-608e-4926-b09d-382a42e68869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b2-b12-UnitInput']/span/input</value>
      <webElementGuid>72006b9f-f352-4d8a-95d8-69da2d7fdd16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/div[3]/div/span/input</value>
      <webElementGuid>f496b285-d877-4026-aa42-16e6194a9b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b4-b2-Input_Unit']</value>
      <webElementGuid>f3333211-346c-4942-972c-bee54a324c4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
