<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Website URL_b4-b2-Input_Website</name>
   <tag></tag>
   <elementGuidId>0fc03e5f-6003-4f33-9cb4-b60b9b73df37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b4-b2-Input_Website']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b4-b2-Input_Website</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b810fb9-0914-47c5-8131-9de51744ce70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>2bcddcec-3410-40d0-928c-12fff00e7162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f44b4a8-f5f0-45aa-ad55-790ce6d9bd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>https://www.website.com</value>
      <webElementGuid>f32b36cf-8ad2-4a18-86d2-86e11b1481db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e185b713-bd25-4ef0-8207-36971295b06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inpURL</value>
      <webElementGuid>899c7b06-e6e5-4b54-8da0-c79ae61c50b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-b2-Input_Website</value>
      <webElementGuid>e05cd8d9-cd10-48c9-81fb-ae91942da598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b2-Input_Website&quot;)</value>
      <webElementGuid>ef513971-ae7f-4849-ad42-b6c7bc5b5bae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b4-b2-Input_Website']</value>
      <webElementGuid>00401347-2deb-4646-97b7-ca7b648cc1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b2-b11-FieldContent']/span/input</value>
      <webElementGuid>17cf7431-f0c7-4c22-8760-debcdf84aa75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/span/input</value>
      <webElementGuid>71c2c68d-0a61-4644-81de-8257e5bf8c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'https://www.website.com' and @id = 'b4-b2-Input_Website']</value>
      <webElementGuid>9762a645-d388-4aba-b7c0-e4ceac7cafdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
