<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(65)_b4-b2-Input_PublicEnquiryNumber</name>
   <tag></tag>
   <elementGuidId>5bc2ff57-bf2b-4f51-b5f8-907ed0c281da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b4-b2-Input_PublicEnquiryNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b4-b2-Input_PublicEnquiryNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Contact number&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>423946b6-ac67-40eb-93c8-863d4842409a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>e44989cc-a600-4114-b3d4-12cbf357cc2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>edb3ff20-3405-4911-bd5c-69376ebf32c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>03604d35-095b-46d8-8c00-58c0c6e95ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>b4-b2-Input_PublicEnquiryNumber_DescribedBy</value>
      <webElementGuid>b8839af9-112a-43a3-acf0-3b0a0e096696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-b2-Input_PublicEnquiryNumber</value>
      <webElementGuid>d8e9caf7-9979-4dff-a1e5-353d10ffece9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b2-Input_PublicEnquiryNumber&quot;)</value>
      <webElementGuid>7423f11f-2e2c-497a-a041-f493429625fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b4-b2-Input_PublicEnquiryNumber']</value>
      <webElementGuid>697c0b9c-3937-4e40-aa91-855fbfb6eaf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b2-b9-Input']/span/input</value>
      <webElementGuid>8be9ae34-61d0-4eba-a5e0-916638aae9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/input</value>
      <webElementGuid>4d5c9725-ee76-4af5-ac1e-2d54d63b6f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'b4-b2-Input_PublicEnquiryNumber']</value>
      <webElementGuid>ee46114a-e0f5-45dd-9ebc-eb56bd4c9d76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
