<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CAMPAIGNS</name>
   <tag></tag>
   <elementGuidId>c684f076-dac6-424d-9024-ef835ec73c42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@ktl-id='btnCampaignsTab']/div/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = '0.2pn62lv1ggj' and (text() = 'CAMPAIGNS' or . = 'CAMPAIGNS')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;0.2pn62lv1ggj&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f19f68da-5641-4540-83ce-a02a0d5038cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-tabs__header-item</value>
      <webElementGuid>760e5652-cf78-45a2-b023-d76983cd9328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>0.2pn62lv1ggj</value>
      <webElementGuid>e926ebab-9fb3-4328-860c-be15fb4f090e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3d364e29-dfe6-455d-ad62-6b0cb114ccac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>f9f9621a-c60d-4005-887c-147233aece17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8c3adde7-8a84-4036-9b14-8b50cc76dd96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7ed683ef-d82d-401b-ad59-4505bb8819d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>b2-$b8</value>
      <webElementGuid>fab800ec-64f2-4040-85eb-41a353ac6844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CAMPAIGNS</value>
      <webElementGuid>657ebea6-caa2-4bce-85cf-188f9c8c7318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-$b5&quot;)/button[@class=&quot;osui-tabs__header-item&quot;]</value>
      <webElementGuid>e2406233-1d9f-4c8c-90b3-0e39ba298c75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='0.2pn62lv1ggj']</value>
      <webElementGuid>41c500b0-6c99-4f33-a2eb-0bb51a491c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-$b5']/button</value>
      <webElementGuid>15d8ebf2-b3d8-483b-8c3c-744e0bcebfb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHARITIES'])[1]/following::button[1]</value>
      <webElementGuid>595fffd1-0e0e-4a93-a7d1-4f686408d5ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search charities or campaigns'])[1]/following::button[3]</value>
      <webElementGuid>18f3fad5-a9a7-4261-9d8f-3eb37793e552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Causes'])[1]/preceding::button[1]</value>
      <webElementGuid>bebfc6d2-15fa-4dcb-95a6-62a786f0cf73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div/div[2]/button</value>
      <webElementGuid>6175d110-cedc-472f-82fd-012195bdbec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = '0.2pn62lv1ggj' and (text() = 'CAMPAIGNS' or . = 'CAMPAIGNS')]</value>
      <webElementGuid>32021029-d133-42e6-8de9-c4f738957b82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
