<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Thank you for signing up</name>
   <tag></tag>
   <elementGuidId>b5de57fa-b82d-4864-b0de-f65087d2d055</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b4-b2-b9-Message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b4-b2-b9-Message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>228c30b4-63ea-4e40-91ae-46134d42482d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>acknowledgement-feedback-message heading1</value>
      <webElementGuid>d0a1fcc5-2281-43ae-a7e6-2bbfcbffac5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-b2-b9-Message</value>
      <webElementGuid>8ce97c36-a366-41d2-b65c-9a34f3c93e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you for signing up</value>
      <webElementGuid>35e6d44e-ee85-429e-b72c-fdb681ba1a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b2-b9-Message&quot;)</value>
      <webElementGuid>1defca0e-f646-48c5-a207-c601ceaca5c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b4-b2-b9-Message']</value>
      <webElementGuid>fd7d1306-328d-43e5-86db-53bbbe6111b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b2-$b9']/div/div</value>
      <webElementGuid>26dc2c29-688d-46f7-b432-a29198703025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exit'])[1]/following::div[24]</value>
      <webElementGuid>b3cd04d1-6183-49c7-a462-65f77af2491f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/preceding::div[3]</value>
      <webElementGuid>1afd535b-9b96-4241-a307-fc1fc07b7d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thank you for signing up']/parent::*</value>
      <webElementGuid>6fa75849-0afa-4f0d-9fe5-4aa87ce7eee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div</value>
      <webElementGuid>7b84b233-caee-4ca3-90f0-f8fd06acd677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b4-b2-b9-Message' and (text() = 'Thank you for signing up' or . = 'Thank you for signing up')]</value>
      <webElementGuid>95b86a14-b559-4045-b053-4cc2121d7249</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
