<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Exit_b4-b2-b3-b1-Wizard</name>
   <tag></tag>
   <elementGuidId>1635b5d1-355c-4852-a3f6-48899e7c6082</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b4-b2-b3-b1-Wizard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b4-b2-b3-b1-Wizard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>095705fc-c38f-43be-8e3e-057f7f5cb94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columns-item content-layout-form-wizard-section</value>
      <webElementGuid>99ebf569-9e54-41eb-8b02-b5b5e2bee14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-b2-b3-b1-Wizard</value>
      <webElementGuid>5ef937f4-7a65-4781-9d2b-7ea5f529b722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b2-b3-b1-Wizard&quot;)</value>
      <webElementGuid>40180522-f944-4e2d-894f-a5c2c0b08604</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b4-b2-b3-b1-Wizard']</value>
      <webElementGuid>6deb6d12-1e36-440e-84e7-0666ac5ca1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b2-b3-b1-MainContentWrapper']/div/div</value>
      <webElementGuid>9c5c498f-b9a9-478e-aaf0-9ea50484bb39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>7cc12d11-1052-4b7a-aa50-190da0de2b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b4-b2-b3-b1-Wizard']</value>
      <webElementGuid>c68ecb64-ac3f-4c5f-9a1b-a90b13b0c768</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
