<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Password_icon fa fa-eye fa-1x</name>
   <tag></tag>
   <elementGuidId>f051744a-1cbb-4755-a2cb-55e85452cad0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-b3-b8-b1-Icon']/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-eye.fa-1x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>dc52fd37-e054-41ac-9e34-86dfc0823923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-eye fa-1x</value>
      <webElementGuid>45df09fc-7591-45d0-b557-10b3bddff028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b3-b8-b1-Icon&quot;)/a[1]/i[@class=&quot;icon fa fa-eye fa-1x&quot;]</value>
      <webElementGuid>ad890d80-ac62-4061-ba6e-826e9206a87e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b3-b8-b1-Icon']/a/i</value>
      <webElementGuid>62097912-90bd-4961-81b0-363a50c85158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>874a85f5-99c1-4fc3-aea8-58d4b072c49a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
