<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Exit_myinfo-singpass-logo</name>
   <tag></tag>
   <elementGuidId>361aa50c-e1ef-4081-8c0a-6217d4b773d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.myinfo-singpass-logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b4-b2-b2-b1-Title']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e816332b-cb57-4383-8fc8-9a7264fc4d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>myinfo-singpass-logo</value>
      <webElementGuid>0608e549-712e-4468-a0d5-0c22857ee5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/NVPC_Resources.singpasslogo.svg?WAMIIAkUcl9i1P3NhwBzkw</value>
      <webElementGuid>57b5b33d-84f7-4c2e-be7c-48b3fa1e9777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b2-b2-b1-Title&quot;)/img[@class=&quot;myinfo-singpass-logo&quot;]</value>
      <webElementGuid>8a3a209f-f5a6-495b-9a36-f97414b8fc1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b2-b2-b1-Title']/img</value>
      <webElementGuid>884079d4-aa25-413e-89f2-b7271a30f852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>65b186de-29a1-4758-bf5f-75ddb28650cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/NVPC_Resources.singpasslogo.svg?WAMIIAkUcl9i1P3NhwBzkw']</value>
      <webElementGuid>899a3cd1-d642-4927-9dd2-33f77b4815d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
