<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_An OTP has been sent to the email add_3f4e3c</name>
   <tag></tag>
   <elementGuidId>2cad6a43-a8ed-45a2-b022-38a677297f50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b4-b2-b4-b2-b2-l1-73_5-Input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b4-b2-b4-b2-b2-l1-73_5-Input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd4d0e7d-2788-47ed-aa0e-955c3b9e3e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>08d3ca7b-1ab3-4d05-8379-1741c8d1e2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58bcd584-899c-4783-964d-1723addc90b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b41c9a6f-9d02-4a78-a658-2c7823cd0c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f271f34e-05fd-4ca0-9ede-76473f5a001b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>1b4c1779-f4c5-405c-a8f6-d06347ea853f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>86bc4475-1e30-45f4-b615-e436c059f47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inp2faInputBox6</value>
      <webElementGuid>3203b8bd-ee40-4241-8031-4e95f8bbdffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-b2-b4-b2-b2-l1-73_5-Input</value>
      <webElementGuid>69ea9483-bc1c-42b9-b10c-8a9f900ef1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b2-b4-b2-b2-l1-73_5-Input&quot;)</value>
      <webElementGuid>9ba6569b-e046-4f4b-8775-107c6a57e63e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b4-b2-b4-b2-b2-l1-73_5-Input']</value>
      <webElementGuid>d0c3023f-197d-4d2c-a53a-7fdaa5d3eace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b2-b4-b2-b2-InputList']/div[6]/span/input</value>
      <webElementGuid>94aa6b19-b8b7-48c1-93c1-a37c966464d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/span/input</value>
      <webElementGuid>52c96e14-9bd5-4d6b-8ffc-026e6f73638b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b4-b2-b4-b2-b2-l1-73_5-Input']</value>
      <webElementGuid>850e3e9b-71b9-49ae-abc4-b8946a9dd7d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
