<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm password_b5-b3-IsConsent_Checkbox</name>
   <tag></tag>
   <elementGuidId>d42e3115-2111-4d60-8ee4-8b9d8f59a613</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-b3-IsConsent_Checkbox']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'checkbox' and @ktl-id = 'chkTermsCond']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-b3-IsConsent_Checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1023a9a-d127-4036-80b2-515a4e35ef60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6817206b-24ab-4879-9b21-2d3cb235fb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f5af243b-3079-42ac-a8ac-03c651463107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b3-IsConsent_Checkbox</value>
      <webElementGuid>6680c84b-513d-4a14-a32c-bae3d42d0647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b3-IsConsent_Checkbox&quot;)</value>
      <webElementGuid>fc931dc2-52ec-4142-bc0a-b0d2835467e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>chkTermsCond</value>
      <webElementGuid>f0551ebb-ec1e-4d4d-94e4-72345e0463d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-b3-IsConsent_Checkbox']</value>
      <webElementGuid>8ac4f907-5bef-4e2e-a949-df5f424f5097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b3-b19-Control']/span/input</value>
      <webElementGuid>b97f5285-8d42-44f0-b125-c3e57e948b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/span/input</value>
      <webElementGuid>29a7f94e-0aec-484b-b76c-8aa7ca1fd9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b5-b3-IsConsent_Checkbox']</value>
      <webElementGuid>6116f8bf-5e11-4932-9a64-d4609c0631ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
