<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_An OTP has been sent to the email add_e0aaeb</name>
   <tag></tag>
   <elementGuidId>ad39a25b-6f1e-40dc-8144-6cfcb2b37d9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b5-b4-b2-b2-l1-231_5-Input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-b4-b2-b2-l1-231_5-Input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#b5-b4-b2-b2-l1-231_5-Input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fe6d25f-b18f-461d-befe-687291881803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4c3822b5-ab83-42e1-9eaf-1580a21bfb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f882b0c-fca2-4e5f-8912-448c41e7a381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>050f9d27-597f-486d-922d-a4590c6bbf9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>b5-b4-b2-b2-l1-231_5-Input_DescribedBy</value>
      <webElementGuid>6938424f-ef19-4c4b-8020-f829a53c0491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dc4ed1f7-0d69-4caf-a187-7801aa8798c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>80002b06-56e1-4feb-bf63-77870131d96b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>45d6e113-d653-432e-8a1c-6b465df6b20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-b4-b2-b2-l1-231_5-Input</value>
      <webElementGuid>ef27fc22-e9b1-41dc-9895-eac78b807e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b4-b2-b2-l1-231_5-Input&quot;)</value>
      <webElementGuid>d856c512-d21f-4a50-b6c6-d984316e65d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-b4-b2-b2-l1-231_5-Input']</value>
      <webElementGuid>ff82e5fd-64ba-4255-b713-5f1e19072ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b4-b2-b2-InputList']/div[6]/span/input</value>
      <webElementGuid>3fa1413e-922f-4324-b4fe-72b6e06d4314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/span/input</value>
      <webElementGuid>7d9c3be0-e403-4e1e-bd8a-4259c66483b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b5-b4-b2-b2-l1-231_5-Input']</value>
      <webElementGuid>ace06385-6431-43fa-ba9f-1e66accebbf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
