<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_An OTP has been sent to the email add_59bd00</name>
   <tag></tag>
   <elementGuidId>0c99126d-be87-4755-b066-b6e6cae2ea4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b4-b2-b4-b2-b2-l1-85_4-Input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b4-b2-b4-b2-b2-l1-85_4-Input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2913aeba-a508-46ce-856c-332b239081e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9a4a6859-61a3-4b01-91cb-92840e8af7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>adc07a7c-d4a4-4f8f-a626-04ca9d960519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b1c48716-17ea-487d-9b9e-4783f269b793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0b2cc8e8-2d92-4447-b840-514ac29e4b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>996a7f09-8689-4030-8fc4-c426b749e6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4ed3f3fe-ffb7-4d3a-a02f-6ccc643274ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inp2faInputBox5</value>
      <webElementGuid>1c04016e-48da-4013-b5e5-bad2c9d95541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-b2-b4-b2-b2-l1-85_4-Input</value>
      <webElementGuid>0a102b49-8ff6-4490-8bde-200f640398fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b2-b4-b2-b2-l1-85_4-Input&quot;)</value>
      <webElementGuid>477cd2c6-69dd-404f-927b-3099813cf51a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b4-b2-b4-b2-b2-l1-85_4-Input']</value>
      <webElementGuid>5b425f8c-28cc-4c4f-adfd-dcd29656c970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b2-b4-b2-b2-InputList']/div[5]/span/input</value>
      <webElementGuid>cf9b3abf-8085-4d47-af26-21d9fd7506c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span/input</value>
      <webElementGuid>b3198435-e610-4eda-b617-140368aa66b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b4-b2-b4-b2-b2-l1-85_4-Input']</value>
      <webElementGuid>e9fc7a01-4766-4cbc-b3f8-38c1cc48cd2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
