<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Donate</name>
   <tag></tag>
   <elementGuidId>6882b609-939b-4b8c-84b3-b64cc6ad9028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-menu-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@ktl-id=&quot;divGiverMenuItemList&quot;]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>495a706e-f2c5-497e-8215-587c2c9fddd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-menu-item</value>
      <webElementGuid>d1a0943a-8b3c-4fa6-8473-39ac9be2bc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/donate</value>
      <webElementGuid>f5596499-8154-47f8-91fa-957bc52dbc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Donate</value>
      <webElementGuid>8659cea2-dbf7-4c32-90fe-b6691addf606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-l1-21_6-$b2&quot;)/a[@class=&quot;nav-menu-item&quot;]</value>
      <webElementGuid>e018410b-9555-48b7-8758-d3577b84ed6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-l1-21_6-$b2']/a</value>
      <webElementGuid>a0ea54a1-53bf-489e-91df-3ddb61d5faa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact us'])[1]/following::a[4]</value>
      <webElementGuid>15951fb1-c8ca-47bc-b7af-2c32a6b1d27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APIs'])[1]/following::a[5]</value>
      <webElementGuid>b22fe5f1-c175-4581-9e71-d73bff942e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volunteer'])[1]/preceding::a[1]</value>
      <webElementGuid>3133765e-fd5f-44b8-8afc-f74c172dc18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/donate')]</value>
      <webElementGuid>641f1c32-68f4-4a49-bcd3-e8a594bb80af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/a</value>
      <webElementGuid>7e7401a2-e95d-4dc7-b174-eca7ff2e335d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/donate' and (text() = 'Donate' or . = 'Donate')]</value>
      <webElementGuid>6b635a62-f17e-4586-addb-5bc38696573b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
