<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_My activities</name>
   <tag></tag>
   <elementGuidId>25fade39-df6d-4bd1-87b4-68b92210c3b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'selActivityListing']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b1-b7-Text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-b7-Text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=menuitem[name=&quot; My activities&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2ea267ff-94e4-42ec-a8dd-7367ab5ef153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-text-pair-text-part</value>
      <webElementGuid>c8c25a83-898c-4227-82fb-18d0b93267dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b1-b7-Text</value>
      <webElementGuid>603633e4-8cd1-4151-b0d3-12e7f2803c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My activities</value>
      <webElementGuid>2847c294-95d7-4dd6-968b-65e5ee56ca8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-b7-Text&quot;)</value>
      <webElementGuid>e665a596-735a-4cfc-a469-b74b11c7b1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>selActivityListing</value>
      <webElementGuid>b9e21174-5822-4add-8e95-3899b1c611b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b1-b7-Text']</value>
      <webElementGuid>bd7581c6-7cb5-423a-bc21-baa37abc5772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-$b7']/div/div[2]</value>
      <webElementGuid>d6fb5c35-c8ed-4d8c-8b76-d80893f01dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Public profile'])[1]/following::div[5]</value>
      <webElementGuid>ae6da1db-ed90-4062-9cf3-021782dbfafd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stories'])[1]/following::div[35]</value>
      <webElementGuid>dd8bfc03-f44d-4b57-a475-8d85e68f93b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appreciation'])[1]/preceding::div[3]</value>
      <webElementGuid>6ae9f0f4-f2eb-4413-a48a-8c3f0d927594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/preceding::div[8]</value>
      <webElementGuid>810514e5-02e5-477c-92e2-802468f5bd03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My activities']/parent::*</value>
      <webElementGuid>3ee02b06-db8d-4c99-810e-41fd3a222b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div/div/div[2]</value>
      <webElementGuid>37032fe9-5701-4cf8-9beb-d7f1dc95e03c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b1-b7-Text' and (text() = 'My activities' or . = 'My activities')]</value>
      <webElementGuid>1ff68ddc-655c-4db1-8800-585c9cc5c915</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
