<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Volunteer</name>
   <tag></tag>
   <elementGuidId>b9246c07-266c-4adb-81b9-68e3886c091a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b1-l1-19_7-b2-Label > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@ktl-id=&quot;divGiverMenuItemList&quot;]/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Volunteer&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c077513c-9391-4946-bbf7-5754b6d586b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Volunteer</value>
      <webElementGuid>2d926822-a248-4be3-8ee7-fb014bc56cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-l1-19_7-b2-Label&quot;)/span[1]</value>
      <webElementGuid>59d930ed-6acc-4901-be7c-9e0d5b99b016</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-l1-19_7-b2-Label']/span</value>
      <webElementGuid>d033fba2-c1df-4b3d-ac73-05d8188bc226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donate'])[1]/following::span[1]</value>
      <webElementGuid>8e2fd0ff-53d0-4a0f-9d28-4d73d36bac5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact us'])[1]/following::span[2]</value>
      <webElementGuid>3f94fadf-8827-489e-9152-c4f83bad93db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collaborate'])[1]/preceding::span[1]</value>
      <webElementGuid>bfcc11e1-8043-40fe-8b8c-6790c59fa9d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fundraise'])[1]/preceding::span[2]</value>
      <webElementGuid>000b2b93-383d-45ff-8edc-b71a1b7a81f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Volunteer']/parent::*</value>
      <webElementGuid>4643bee5-1694-42d6-9036-576ff52d9838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/div[2]/span</value>
      <webElementGuid>5e829501-5409-4474-baa6-7383ca379b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Volunteer' or . = 'Volunteer')]</value>
      <webElementGuid>0dc939b1-afee-4c53-bb3c-f03940ded2a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
