<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Explore_b2-l5-1881_0-b30-b1-ContentImage</name>
   <tag></tag>
   <elementGuidId>801b2be7-c854-49ad-9ce8-f76bda369bf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-l5-1881_0-b30-b1-ContentImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/article/div/div/div[2]/div/div/div/div/div/div/div[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#b2-l5-1881_0-b30-b1-ContentImage</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>12e7c479-804c-4eaa-a068-dfd27ed7ba5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>giving-image</value>
      <webElementGuid>1c8d751c-1618-4841-9f2c-e0b92f602954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/NVPC_Resources.FallbackImage.svg?64pTZQdj2qaGlPqEINfFWw</value>
      <webElementGuid>06445bf6-3f60-47c0-81a2-57f706da4b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l5-1881_0-b30-b1-ContentImage</value>
      <webElementGuid>e70e81e0-6535-4584-8423-6bed4694158a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l5-1881_0-b30-b1-ContentImage&quot;)</value>
      <webElementGuid>3053dbae-87d4-478a-842e-d391cb0d975d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='b2-l5-1881_0-b30-b1-ContentImage']</value>
      <webElementGuid>d7cfbbad-6ab2-4925-8cc7-26f9e8a40c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-l5-1881_0-b30-$b1']/img</value>
      <webElementGuid>4c024104-eb07-4c57-a491-a1c301a51669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/article/div/div/div[2]/div/div/div/div/div/div/div[3]/img</value>
      <webElementGuid>e6a2df6e-e8be-414b-a729-7a0b11192211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/NVPC_Resources.FallbackImage.svg?64pTZQdj2qaGlPqEINfFWw' and @id = 'b2-l5-1881_0-b30-b1-ContentImage']</value>
      <webElementGuid>be74040f-fb07-4b92-88fb-df956c2fbb69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
