<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Explore_b2-l3-931_0-b22-b1-ContentImage</name>
   <tag></tag>
   <elementGuidId>07a19e03-0e8d-4878-8301-eaad226f14b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='b2-l3-931_0-b22-b1-ContentImage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-l3-931_0-b22-b1-ContentImage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#b2-l3-931_0-b22-b1-ContentImage</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>93688b8f-23aa-4bd2-85ec-9e4e5a201b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>giving-image</value>
      <webElementGuid>338e00de-1390-42d1-b268-cb436783043d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/NVPC_Resources.FallbackImage.svg?64pTZQdj2qaGlPqEINfFWw</value>
      <webElementGuid>5fdd1727-8798-4efb-8e7c-93381df34c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l3-931_0-b22-b1-ContentImage</value>
      <webElementGuid>f57ebaab-2ef0-4528-a8d0-98d269a1ec4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l3-931_0-b22-b1-ContentImage&quot;)</value>
      <webElementGuid>80ed56dd-c3fc-4d5f-8971-0ad070b447f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='b2-l3-931_0-b22-b1-ContentImage']</value>
      <webElementGuid>621a12fc-884a-4759-800a-ce8cd2d21d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-l3-931_0-b22-$b1']/img</value>
      <webElementGuid>520b45c3-4942-467d-a5a0-9b6967e3ca5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>e07b2129-818d-46b0-87b0-d2b9a82f5ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/NVPC_Resources.FallbackImage.svg?64pTZQdj2qaGlPqEINfFWw' and @id = 'b2-l3-931_0-b22-b1-ContentImage']</value>
      <webElementGuid>afd032c7-0ca9-4a8b-9baf-86a4540808ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
