<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nil_icon-box</name>
   <tag></tag>
   <elementGuidId>542cf233-d116-49cb-b776-5705538e8829</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-l1_0-233_0-b7-b1-Content']/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;b2-l1_0-233_0-b7-b1-Content&quot;)/div[@class=&quot;icon-box&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-l1_0-233_0-b7-b1-Content > div.icon-box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eec98cc1-e564-404c-9144-0cd846f54d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-box</value>
      <webElementGuid>ce35b82d-ac8a-4d3d-95f9-2d1fde480a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l1_0-233_0-b7-b1-Content&quot;)/div[@class=&quot;icon-box&quot;]</value>
      <webElementGuid>107f631a-d27f-49f1-bd6b-699b02e44f8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-l1_0-233_0-b7-b1-Content']/div</value>
      <webElementGuid>f3e649be-0c16-478f-a0f0-2efa05f21dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nil'])[1]/following::div[6]</value>
      <webElementGuid>95ffb2be-a8c4-4570-8ced-d383298bfa7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[1]/following::div[6]</value>
      <webElementGuid>ba5792e7-a4d5-4391-a1fe-a8e03adcede6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage roles'])[1]/preceding::div[2]</value>
      <webElementGuid>c63e3528-8559-4bd1-839b-aa237076c9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::div[7]</value>
      <webElementGuid>6f6c1c81-9924-4e0f-b1c4-99fe0d02b559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/div/div/div/div/div</value>
      <webElementGuid>2d6bde3f-a6f8-4f3a-b7fa-6e50386aca1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-l1_0-332_0-b7-b1-Content']/div</value>
      <webElementGuid>97bfb646-9fe6-4124-8d97-062c3d59e9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/following::div[6]</value>
      <webElementGuid>74896ba7-6087-4a26-86e6-e474299276b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
