<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ORG Developer_b2-b17-l1-224_2-Checkbox</name>
   <tag></tag>
   <elementGuidId>8e9f0133-d528-4437-a19d-846b65569722</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b17-l1-224_2-Checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b17-l1-224_2-Checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5b57e32-12fe-41c1-8091-275c6e195c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>202153b0-2e0c-4f65-8bb6-81037bf3ce9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f6ce763f-593e-49da-bda6-65bfc09047c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b17-l1-224_2-Checkbox</value>
      <webElementGuid>67a21624-1733-4a2d-b0b2-67732d4a6661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b17-l1-224_2-Checkbox&quot;)</value>
      <webElementGuid>454bf27e-f69e-4a32-8243-44d83ae226be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b17-l1-224_2-Checkbox']</value>
      <webElementGuid>1cb10c35-929f-45d2-9038-f8d1d7e6ee28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b17-l1-224_2-b1-Control']/span/input</value>
      <webElementGuid>2a04fdb2-2f7f-41d8-8ed3-72fd18e7bdc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span/input</value>
      <webElementGuid>357c0e71-c973-4b2e-852c-d7e4e92d44db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b17-l1-224_2-Checkbox']</value>
      <webElementGuid>fc1d90ad-1355-43a4-b5bd-046084734796</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
