<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Approve</name>
   <tag></tag>
   <elementGuidId>974b39e6-421c-4bf4-810d-114dfe1df6ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.positive.ThemeGrid_MarginGutter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b6-b6-l1_0-347_0-b5-Items']/a[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'btn btn-success' and (text() = 'Approve' or . = 'Approve')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cd27a221-9a0e-4d5a-9c98-42e41280d1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>4cb0adf5-b99a-4846-b7e3-59882450ca79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>359eb767-e0c8-4c01-b1da-416f9a5f0b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>lnkApprove</value>
      <webElementGuid>cb5d5d16-2848-4497-ad14-4e245bd142de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approve</value>
      <webElementGuid>ca0f797d-42d8-406e-874d-1a2b155ff421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b6-b6-l1_0-347_0-b5-Items&quot;)/a[@class=&quot;positive ThemeGrid_MarginGutter&quot;]</value>
      <webElementGuid>2bfa67d3-667a-414d-8dd2-93e2c185dda7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b6-b6-l1_0-347_0-b5-Items']/a[2]</value>
      <webElementGuid>d17f3914-a829-4bc2-94f9-dbbb1aa5fb9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review'])[1]/following::a[1]</value>
      <webElementGuid>f824f50e-4465-4a47-b617-5c33e4c6894d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rajeev@marriott.dk.dev'])[1]/following::a[2]</value>
      <webElementGuid>d2918f74-e18f-4703-a5fe-585feabf2619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject'])[1]/preceding::a[1]</value>
      <webElementGuid>2944972c-5227-41a0-8539-45b53ae5d79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[9]</value>
      <webElementGuid>6cacb628-0fa9-4a04-af4c-07548a3aba4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a[2]</value>
      <webElementGuid>37e8b20a-5330-4f06-a2ad-941d7cd57f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Approve' or . = 'Approve')]</value>
      <webElementGuid>cdad5526-ccf0-4ed5-a1ce-2bbf018978dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
