<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Verification</name>
   <tag></tag>
   <elementGuidId>d158a70c-b309-4e6f-b3bb-ec29979f59d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b3-b2-Title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b2-Title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8576d544-7c96-4d06-ae6a-0d56d0e7eef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading1 margin-bottom-m ph</value>
      <webElementGuid>e13d96aa-f9d2-4de5-af00-b33ca320f983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-Title</value>
      <webElementGuid>ebd9d4cc-ed3e-43fa-916e-9b2c155c24cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verification</value>
      <webElementGuid>ddc542f7-ed7c-4f65-a045-8b432738192c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b2-Title&quot;)</value>
      <webElementGuid>e2648f4c-d9da-4e2c-99cc-25b277a8874e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b3-b2-Title']</value>
      <webElementGuid>f88bbb45-d447-4643-b448-8d14468624d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b2-MainContentWrapper']/div/div[2]/div</value>
      <webElementGuid>ad724fef-b03e-420d-945d-dc07a61c0cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exit'])[1]/following::div[20]</value>
      <webElementGuid>3dec73f1-b61e-4ddc-8032-9bd0cbbf3569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter OTP'])[1]/preceding::div[1]</value>
      <webElementGuid>bde15450-01a3-40d4-80ad-1c6ad34feaec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If the account exists, you will receive a 6-digit OTP sent to your email.'])[1]/preceding::div[5]</value>
      <webElementGuid>a2b5bc13-7715-477d-bf59-c874e66a42ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verification']/parent::*</value>
      <webElementGuid>de7ce2e4-0ea3-4c6f-a350-5cb7b644ebf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div</value>
      <webElementGuid>cf4d9e2e-bfa0-44a2-939d-40fa2b8e2c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b3-b2-Title' and (text() = 'Verification' or . = 'Verification')]</value>
      <webElementGuid>210ddf15-34e3-4bd7-8002-9f19247c77fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
