<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_If the account exists, you will recei_340166</name>
   <tag></tag>
   <elementGuidId>2a5b3272-9712-4cbe-8fc7-2c8e7748a7bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'inp2faInputBox1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b6-b2-l1-21_0-Input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b3-b6-b2-l1-21_0-Input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd56f55c-5c5c-45a2-95c0-876056693134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>68547e67-d300-4b72-bdf9-f7747b9da960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>882455d8-b200-497d-aabd-4a34c42502c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f9ced2c3-f81a-4a47-bbe2-1855f08ab18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4b44e6cf-4b09-4a81-aebb-f08e851cd6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>407b6408-aca5-4807-a961-69820bf36b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ecc5bba2-1a61-497e-aed1-4944d4fdb085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inp2faInputBox1</value>
      <webElementGuid>56f5bc36-809a-41ea-8195-624e7030acb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b6-b2-l1-21_0-Input</value>
      <webElementGuid>97f767de-bb34-44f9-bf9d-8df24f718ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b6-b2-l1-21_0-Input&quot;)</value>
      <webElementGuid>d6c519b5-b7f0-4601-823b-58163f40c518</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b6-b2-l1-21_0-Input']</value>
      <webElementGuid>b1e482af-e0b5-4d60-9c8f-373df30a5c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b6-b2-InputList']/div/span/input</value>
      <webElementGuid>afba50ce-3bea-40f6-ac6a-6b3149ffb727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>173aa288-05ce-4c85-bb83-8b01cdaf951c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b3-b6-b2-l1-21_0-Input']</value>
      <webElementGuid>07b059b1-a06f-4d2b-b148-704cd9479bb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
