<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_If the account exists, you will recei_c37bcb</name>
   <tag></tag>
   <elementGuidId>2d4210d7-5acf-4073-9f16-271944337912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b3-b6-b2-l1-17_5-Input']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'inp2faInputBox6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b6-b2-l1-17_5-Input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>282c8d6a-b037-45f3-804b-2305ed02b046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0a6f7dae-40a9-4478-9e97-0b8b2ab3756f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b79f48db-3ee9-4e8e-a718-9c0c6eef4225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>29a21e09-e64d-47a9-ae8a-81101c858da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bbff49c7-6f71-4984-a204-4d3278f88c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>501171c7-4a57-46fe-974c-ddef92e12b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a1e7c4fb-852f-40c7-918c-c08148349abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inp2faInputBox6</value>
      <webElementGuid>586ceb00-b074-4d00-9645-bbb0b878c018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b6-b2-l1-17_5-Input</value>
      <webElementGuid>67654c63-d7b4-4fe1-a702-7ba1a9173e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b6-b2-l1-17_5-Input&quot;)</value>
      <webElementGuid>b503b42e-28eb-4d36-8ca3-24e3b7c79c11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b6-b2-l1-17_5-Input']</value>
      <webElementGuid>42f2dd64-0e39-4038-911f-cd62d46f7a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b6-b2-InputList']/div[6]/span/input</value>
      <webElementGuid>4b8569cc-e85b-41f7-a991-26bebaf11b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/span/input</value>
      <webElementGuid>0e6124b0-78ea-4cd3-a20a-260b3e668549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @ktl-id = 'inp2faInputBox6' and @id = 'b3-b6-b2-l1-17_5-Input']</value>
      <webElementGuid>db21c051-1ca1-4e7c-9291-8fa859158240</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
