<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create Opportunity</name>
   <tag></tag>
   <elementGuidId>ebb71351-6205-49fd-b596-9f483d63c7cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b2-b1-b9-btn_Publish']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'btnCreateOpportunity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-b9-btn_Publish</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e664372-03e0-4913-aab3-b02b964c5d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary ThemeGrid_MarginGutter</value>
      <webElementGuid>96114c58-61d2-4de8-a384-c4dfe02c1c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>eff19192-3e6d-419a-b19e-82447b3a9712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>btnCreateOpportunity</value>
      <webElementGuid>d56a5afc-db2e-4d95-8c2a-abd1e869c266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b1-b9-btn_Publish</value>
      <webElementGuid>79ee0b42-01fa-40e6-ad72-0918c59813de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Publish</value>
      <webElementGuid>03146e7c-c90f-47ac-b9bb-f3acb57f7dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-b9-btn_Publish&quot;)</value>
      <webElementGuid>7b776ba9-77ed-4e54-9a5a-775c13ec95b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b2-b1-b9-btn_Publish']</value>
      <webElementGuid>8d2ba2bc-666c-4ab8-b875-ea4a58f63276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b9-b16-Right']/button[2]</value>
      <webElementGuid>65320d87-ad9f-49f3-b3fc-382f17101717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save draft'])[1]/following::button[1]</value>
      <webElementGuid>5ab21c40-6382-4fdc-923a-9446489332b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::button[2]</value>
      <webElementGuid>74c759a5-a4ca-4402-a5b0-36ace4aeccfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft version'])[1]/preceding::button[1]</value>
      <webElementGuid>c1037c62-2f10-4794-a19b-86fccbde76a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>361d6d81-5ac5-47b2-b577-d1557931a802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'b2-b1-b9-btn_Publish' and (text() = 'Publish' or . = 'Publish')]</value>
      <webElementGuid>02e752d6-9952-41cf-8377-445188914921</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
