<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Add schedule</name>
   <tag></tag>
   <elementGuidId>dc99ff4e-f6f3-4025-b518-526a6d274593</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@ktl-id='btnAddSchedule']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa-solid.fa-ellipsis-vertical</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>17512bf8-fc31-40fa-aa7c-f4d8d840dada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-solid fa-ellipsis-vertical</value>
      <webElementGuid>45ca0e99-894c-4577-8e68-7c05f1fe71f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b40-l1_0-240_0-b13-b1-Content&quot;)/div[@class=&quot;icon-box&quot;]/i[@class=&quot;fa-solid fa-ellipsis-vertical&quot;]</value>
      <webElementGuid>078dda3e-2345-46ea-9553-5d1c4b78e9c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b40-l1_0-240_0-b13-b1-Content']/div/i</value>
      <webElementGuid>b160ff3f-f522-4589-a578-8a47e32d42fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/div/div/div/div/i</value>
      <webElementGuid>f91c680a-90b9-40a1-9aa7-af2aae51c4b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
