<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Turn on auto-approval_b2-b1-b7-AutoAp_fadfb2</name>
   <tag></tag>
   <elementGuidId>50fa6f9f-4052-4f35-bb42-46a57aaa0ea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b1-b7-AutoApproval_Switch']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'btnAutoApprovalSwitch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-b7-AutoApproval_Switch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e626278c-ed42-45d7-8390-f1a566a4c7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>9c5e6d34-bc08-469d-bd94-38085ef2132b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>27fa521e-9b4c-4b6f-896f-0e77b5957173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>btnAutoApprovalSwitch</value>
      <webElementGuid>2b0366e3-2bad-4f0e-8468-f8cc3c7b34b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b1-b7-AutoApproval_Switch</value>
      <webElementGuid>93359ba3-fef4-4a45-8d63-6c035cf5165f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-b7-AutoApproval_Switch&quot;)</value>
      <webElementGuid>d6ec2dcd-c874-4c06-8b58-632596fe0bd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b1-b7-AutoApproval_Switch']</value>
      <webElementGuid>a1b752bf-cb9a-4184-a6a6-e77adb13246a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b7-b18-Switch']/span/input</value>
      <webElementGuid>6ce13a79-c7c9-4351-ad6a-0b2a582fb632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>bbd0be52-af92-4482-8ce7-ed6936ab399a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b1-b7-AutoApproval_Switch']</value>
      <webElementGuid>8c2883e1-de38-431b-9e42-ac8859035896</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
