<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Not available_b2-b1-b8-l3-478_0-l3-47_610509</name>
   <tag></tag>
   <elementGuidId>ad5f3bc2-0289-4511-b5fd-143ab6f8d623</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b1-b8-l3-478_0-l3-479_0-l3-480_1-Checkbox1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'chkVacancyItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-b8-l3-478_0-l3-479_0-l3-480_1-Checkbox1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>712b8709-770b-456b-833b-74359c9a525f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>df7c3011-14fe-4549-9506-d12b3495a33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4dad93d0-eddd-4130-b841-5432c0b5f2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>chkVacancyItem</value>
      <webElementGuid>6f72edd3-2673-49b9-9d17-22f9a7568e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b1-b8-l3-478_0-l3-479_0-l3-480_1-Checkbox1</value>
      <webElementGuid>f8f15dac-98f8-4d01-a961-b8c24c45687e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-b8-l3-478_0-l3-479_0-l3-480_1-Checkbox1&quot;)</value>
      <webElementGuid>9788b6e7-8026-4c4f-a13a-c78c359b4576</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b1-b8-l3-478_0-l3-479_0-l3-480_1-Checkbox1']</value>
      <webElementGuid>f677e0b8-e5cf-4997-b870-cd31df0e8d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b8-l3-478_0-l3-479_0-l3-480_1-b9-Control']/span/input</value>
      <webElementGuid>eb64b2ad-ddde-49ed-b4e3-826b3c3b74c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/span/input</value>
      <webElementGuid>a5224743-fbd7-4d09-829f-7b479b5eee9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b1-b8-l3-478_0-l3-479_0-l3-480_1-Checkbox1']</value>
      <webElementGuid>1a3e1dec-2975-4591-bd71-e02b570ea2d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
