<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Let potential volunteers know what_58814e</name>
   <tag></tag>
   <elementGuidId>5e25be4a-3e89-4986-9a8a-fc079d501868</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='b2-b1-b7-TextArea_KeyResponsibilitiesImpact']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'inpKeyResponsibilitiesImpact']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-b7-TextArea_KeyResponsibilitiesImpact</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bbd6f067-de99-4ff6-9b5b-90040e68ec63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>82c9097c-1062-48a3-bf51-dd886cb7df22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4d2d48b8-3edb-4abc-a9f3-78a438f0556d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>c7abb321-bfb9-495d-afd9-df0b8eb77d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inpKeyResponsibilitiesImpact</value>
      <webElementGuid>0e921327-83aa-46b4-a055-4b792d8d2cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b1-b7-TextArea_KeyResponsibilitiesImpact</value>
      <webElementGuid>0fdd609b-d80c-4cb3-93af-96faa66ea092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-b7-TextArea_KeyResponsibilitiesImpact&quot;)</value>
      <webElementGuid>53cf2795-56f7-481c-becd-97b515cb74b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b2-b1-b7-TextArea_KeyResponsibilitiesImpact']</value>
      <webElementGuid>6e8e61d9-5306-47a5-9200-ee3c9fdcb0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b7-b12-TextArea']/span/textarea</value>
      <webElementGuid>19924054-7414-48de-800a-a914b8b05de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>02644dce-3487-42e8-800d-8e17871de525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b2-b1-b7-TextArea_KeyResponsibilitiesImpact']</value>
      <webElementGuid>ed505f58-5182-4286-af09-f825b8c1dafb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
