<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_a</name>
   <tag></tag>
   <elementGuidId>c9b53219-e404-413d-b69b-3c786ddf68dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='b2-b1-b7-TextArea_AdditionalPointsDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-b7-TextArea_AdditionalPointsDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>54fe4365-c09c-49f6-ac69-2d51d4f7fe5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>0b62d962-3754-44ba-b10b-b1bbd91e1c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>5fab7052-b0f2-460b-ab21-601d336d4f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>b8f7a7f3-930a-44bb-81f0-1c887f88ffab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inpAdditionalPointsDescription</value>
      <webElementGuid>be88f8f1-7130-446c-b202-58019eb1ce41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b1-b7-TextArea_AdditionalPointsDescription</value>
      <webElementGuid>38cd3193-3d17-435e-a97a-1134cd7445f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8dbd5a0e-0460-40a5-b161-2c4ea5971de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-b7-TextArea_AdditionalPointsDescription&quot;)</value>
      <webElementGuid>6e12dba8-6d2b-4880-a7c0-165e2268fa3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b2-b1-b7-TextArea_AdditionalPointsDescription']</value>
      <webElementGuid>a2e8c15b-4aae-4d0b-bc81-3570fc0d9e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b7-b17-TextArea']/span/textarea</value>
      <webElementGuid>9c23d926-711c-4f59-ad34-9f0b37fb0e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is there any other information volunteers need to know about this position?'])[1]/following::textarea[1]</value>
      <webElementGuid>98e7ba55-d13e-4cdf-8c53-97642eff104d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(optional)'])[3]/following::textarea[1]</value>
      <webElementGuid>d419f836-5abe-4f00-8cb9-2abb0eafe2bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Turn on auto-approval'])[1]/preceding::textarea[1]</value>
      <webElementGuid>8f85e036-8df0-4b25-8166-905951e19a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::textarea[1]</value>
      <webElementGuid>3be3697d-dbdd-403b-adeb-9bd54bf482eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='a']/parent::*</value>
      <webElementGuid>e26f36e2-0607-4ab0-beb2-847320bc18d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div/div/div/span/textarea</value>
      <webElementGuid>24bb4446-8a7a-4c04-bdd1-4e205150d0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b2-b1-b7-TextArea_AdditionalPointsDescription' and (text() = 'a' or . = 'a')]</value>
      <webElementGuid>7b4c2651-9acd-440f-8618-89c5e8a6a512</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
