<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue with Payment</name>
   <tag></tag>
   <elementGuidId>2053b3fc-3b4c-4dee-95a8-4c3cdb544355</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-btn_MakePayment</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'btnMakePayment']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b2-btn_MakePayment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5f1595dc-77c1-418d-8c71-5e08a8b4ac5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>801dc7a9-1125-4fc3-8fb1-2350d37968c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9bb58117-8d25-42a1-97e5-acec056219b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>btnMakePayment</value>
      <webElementGuid>c5b1d68d-a8fe-45bf-b546-8b7064c12971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-btn_MakePayment</value>
      <webElementGuid>968362ab-e0cd-491f-80b1-ce189fffd1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue with Payment</value>
      <webElementGuid>ab6111dc-62f8-4289-a30a-3352c5b77649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-btn_MakePayment&quot;)</value>
      <webElementGuid>ae3f0603-1286-4fe3-a8a3-16a17f2e3e5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b2-btn_MakePayment']</value>
      <webElementGuid>2452984f-ad76-45ff-91ad-724d854bc9c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b16-Button']/button</value>
      <webElementGuid>13dfbdb0-21e3-41a0-b887-c0e76a972172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save my card for future donations'])[1]/following::button[1]</value>
      <webElementGuid>962459d8-848e-4bea-a86d-7028316a5083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QR payment'])[1]/following::button[1]</value>
      <webElementGuid>601d51da-ade3-41e5-854f-d25c9fcf36a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donation summary'])[1]/preceding::button[1]</value>
      <webElementGuid>e3b43225-2553-42e2-b218-5ef29f50b0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non tax-deductible'])[1]/preceding::button[1]</value>
      <webElementGuid>b9fca1c0-b56f-48c0-9b01-d0ff760be6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue with Payment']/parent::*</value>
      <webElementGuid>81378124-dcde-464c-9adc-91974c1005f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/button</value>
      <webElementGuid>764bba1e-d726-479f-948d-e71a4e515e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b2-btn_MakePayment' and (text() = 'Continue with Payment' or . = 'Continue with Payment')]</value>
      <webElementGuid>ebefdc1d-4c46-416b-a7da-3fafe4336e81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
