<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_QR payment_b2-SaveCardFuture</name>
   <tag></tag>
   <elementGuidId>8607fe08-c480-416b-ac90-795c6f897c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-SaveCardFuture</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-SaveCardFuture']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b86df687-db92-49c4-8805-211dffd54daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>84bc01bc-2ce0-4901-85e2-f9c73ebd3ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7f5f0990-9cf8-42cf-8c3d-8ce0ed9f1e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>chkSaveCardFuture</value>
      <webElementGuid>5c3c462c-2833-4eec-969d-32d423b7f86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-SaveCardFuture</value>
      <webElementGuid>9b1d2a13-0352-427b-bb6a-54e2d79802a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-SaveCardFuture&quot;)</value>
      <webElementGuid>e36f070d-fae3-4ac2-bfbd-b4efa785a35e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-SaveCardFuture']</value>
      <webElementGuid>43c85c10-3253-4299-8210-c83b2dbb0455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-SavedCard']/div/div/span/input</value>
      <webElementGuid>d4a404f0-e525-4ffa-9dd6-ca90338cca0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>fac03caa-11f6-4855-b6e3-a90bd5a1d1e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-SaveCardFuture']</value>
      <webElementGuid>db2fbc27-1443-44b2-8f9f-6d179ff1a05f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
