<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Fundraise</name>
   <tag></tag>
   <elementGuidId>b872ebae-24b4-4d56-b23a-b9ab7e0cb3e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/donate' and (text() = 'Donate' or . = 'Donate')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.nav-menu-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@ktl-id='divGiverMenuItemList']/div[4]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ac71a42c-b0b7-4b78-842a-078356c135de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-menu-item</value>
      <webElementGuid>40be3673-e996-4d62-a765-b74c89f620ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/donate</value>
      <webElementGuid>bb9227db-bcd9-4ed2-a6ef-8400f67c6309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Donate</value>
      <webElementGuid>f19a26e4-1c0c-49c7-acfa-00c86c6770cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-l1-19_6-$b2&quot;)/a[@class=&quot;nav-menu-item&quot;]</value>
      <webElementGuid>a5c04cdc-6590-4e54-8e8d-59fa5cf54b56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-l1-19_6-$b2']/a</value>
      <webElementGuid>fe1e651e-9b72-49ee-9186-3c469cec5c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact us'])[1]/following::a[4]</value>
      <webElementGuid>f4898677-87b8-40b1-8dea-e62f3179eb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APIs'])[1]/following::a[5]</value>
      <webElementGuid>0aed237c-61bf-45c0-9b30-f3ce7a6b024a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volunteer'])[1]/preceding::a[1]</value>
      <webElementGuid>86cd0a9f-c8e1-453e-9a19-c7becf1b4418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/donate')]</value>
      <webElementGuid>cd37df50-02a4-4126-99f8-625302a60f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/a</value>
      <webElementGuid>91c67eaa-f677-477f-b7ec-6e554947f266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/donate' and (text() = 'Donate' or . = 'Donate')]</value>
      <webElementGuid>11709a00-78a5-4fc5-8fb5-9f66ca27f7d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
