<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Approve</name>
   <tag></tag>
   <elementGuidId>a7d3f992-e64d-43b8-8c2f-868cf6a29e21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'btnApprove3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.positive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b12-l1_0-349_0-b7-Items']/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>07c6b3ca-8a9e-473e-8b41-52938f076314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>positive</value>
      <webElementGuid>87d8c21e-34d1-429e-abdf-b50115041acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>38830552-6b0f-41fb-a9ba-b26bb99a161f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>btnApprove3</value>
      <webElementGuid>b5ae1b17-7a23-4880-8484-234bbce4d272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approve</value>
      <webElementGuid>d0f434ea-b2be-4db7-a230-01ef429a5540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b12-l1_0-349_0-b7-Items&quot;)/a[@class=&quot;positive&quot;]</value>
      <webElementGuid>fa36a774-3509-475d-b45f-d52a4831aed3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b12-l1_0-349_0-b7-Items']/a[2]</value>
      <webElementGuid>b1d27b82-88a9-4de0-a54a-e97f6fd3e277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View request'])[1]/following::a[1]</value>
      <webElementGuid>f7144d80-a5ac-4241-a045-93c7c4b1eb4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='seanweareone@mailto.plus'])[1]/following::a[2]</value>
      <webElementGuid>10c4d3ca-319f-4f5b-ba62-a9af0dafd6f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject'])[1]/preceding::a[1]</value>
      <webElementGuid>6372410e-1c6d-4980-bd75-e954e36f0606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[9]</value>
      <webElementGuid>a04bf08a-07e9-41db-af27-397ced646f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a[2]</value>
      <webElementGuid>cb04ee16-9b16-4425-b2e1-fe34b90a0848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Approve' or . = 'Approve')]</value>
      <webElementGuid>1b97e7a2-8937-4880-88a6-c59e3954ed5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
