<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View request</name>
   <tag></tag>
   <elementGuidId>a7ed6e6b-e0dd-4ec2-844e-d8226fcab8b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'btnApprove1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b12-l1_0-1092_0-b7-Items > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b12-l1_0-1092_0-b7-Items']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b25ca214-b001-4879-ada1-11cd9a40f53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>7fd6bd28-fdc1-4c6c-a0cd-9584652b5707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>btnApprove1</value>
      <webElementGuid>59bf5415-7d21-4f9f-9b43-b3e66acce0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View request</value>
      <webElementGuid>d7a888c6-1ec2-4b07-affd-f23b4c07952d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b12-l1_0-1092_0-b7-Items&quot;)/a[1]</value>
      <webElementGuid>254eb64a-69d0-427c-b858-9606febd3708</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b12-l1_0-1092_0-b7-Items']/a</value>
      <webElementGuid>485b08e5-fbbf-45ce-8931-eb30ca68a092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rajeev@marriott.dk.dev'])[1]/following::a[1]</value>
      <webElementGuid>eb10fb04-1bbf-4b5b-bc70-b3d8b10c2ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rajeev Menon'])[1]/following::a[1]</value>
      <webElementGuid>2e0f0957-fd8d-4f05-9ff9-ae566dcaa745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approve'])[1]/preceding::a[1]</value>
      <webElementGuid>064e7650-c21f-4346-9feb-73059aecc1a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>b73248ff-f48c-42c2-9140-7237ba44c4a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/a</value>
      <webElementGuid>cea2806c-c988-4904-8931-6dcfbf3c84a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'View request' or . = 'View request')]</value>
      <webElementGuid>c23da0d9-bf2a-4842-8a79-aa70deba43d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
