<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Actions 1st To Review</name>
   <tag></tag>
   <elementGuidId>dc864db2-e4c5-408d-825b-9b65a72f84e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@ktl-id='divToReviewTable']/tbody/tr[1]/td[7]/div/div/div/div[1]/div/I</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa-solid.fa-ellipsis-vertical</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4526cf97-be0a-4fba-a65d-c2dd69638c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-solid fa-ellipsis-vertical</value>
      <webElementGuid>ef4cbce1-7de7-4d03-84d5-404d3c19af95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b12-l1_0-349_0-b7-b1-Content&quot;)/div[@class=&quot;icon-box&quot;]/i[@class=&quot;fa-solid fa-ellipsis-vertical&quot;]</value>
      <webElementGuid>768c3693-ccbc-41e1-b2a7-a9fe5da27cba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b12-l1_0-349_0-b7-b1-Content']/div/i</value>
      <webElementGuid>bcbebcae-e935-49ce-b135-ee1c7a0c3eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/div/div/div/div/i</value>
      <webElementGuid>ee1593cd-4717-4a7a-9d17-0606ab66b196</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
