<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_rajeevmarriott.dk.dev_fa-solid fa-ellipsi_9d30d0_1</name>
   <tag></tag>
   <elementGuidId>3da7b604-ab4b-47a2-8c9d-0b3e77c33cb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b12-l1_0-1358_0-b7-b1-Content']/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa-solid.fa-ellipsis-vertical</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7ec11c07-5b3e-4bbb-a9ac-7c6285f1d0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-solid fa-ellipsis-vertical</value>
      <webElementGuid>75e6b7fc-f69a-4a15-83a9-96939e622401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b12-l1_0-1358_0-b7-b1-Content&quot;)/div[@class=&quot;icon-box&quot;]/i[@class=&quot;fa-solid fa-ellipsis-vertical&quot;]</value>
      <webElementGuid>f4b0066f-6d50-40f4-b001-3d5c4e07f1d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b12-l1_0-1358_0-b7-b1-Content']/div/i</value>
      <webElementGuid>023c5cb0-8788-484b-9eef-637ee878864c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/div/div/div/div/i</value>
      <webElementGuid>4bfe81cb-d3a8-419c-8b27-e42e770e0f88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
