<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search charities or campaigns_b2-SearchInput</name>
   <tag></tag>
   <elementGuidId>60a4d00a-9645-4c4e-b5ef-107694297f38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'inpSearchDonate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-SearchInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-SearchInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56c1f8c5-b104-4d22-a5e2-6f6c065dfbe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>e63713d2-8d3a-4f43-ab7c-1cce4207a216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>249d6eb6-3833-43f7-941d-3b7a512ff3cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by charities or campaigns name</value>
      <webElementGuid>397018b6-1e31-4bef-99bb-e9206e5b8631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dc48d2da-cc13-4f63-a0e8-77b958995b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inpSearchDonate</value>
      <webElementGuid>32ea0ee4-28fc-4097-bed8-0d065045ad87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-SearchInput</value>
      <webElementGuid>ecf5ce38-c8c1-464d-9f88-47007c6c2903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-SearchInput&quot;)</value>
      <webElementGuid>eb7e3b81-576b-4a31-8a44-fa1797bfbb13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-SearchInput']</value>
      <webElementGuid>429d1671-e34c-479f-8554-885f759f9046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b3-Input']/span/input</value>
      <webElementGuid>423cdd57-b358-4839-942d-1f0a999fa0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>13367178-8c42-437c-9f1d-7a42cbad89aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Search by charities or campaigns name' and @id = 'b2-SearchInput']</value>
      <webElementGuid>95b60e6b-4ab7-42c6-b8a7-8680022f48f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
