<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download</name>
   <tag></tag>
   <elementGuidId>c7c6b84a-e31e-460c-866d-00f2a7080f08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.text-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@ktl-id='lnkDownload']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e5fceaab-da4c-4fe3-b7b9-de008f9f552b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-link</value>
      <webElementGuid>c9e2bf38-922a-4e7d-bbb5-63546bab4970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>bba0e620-26ab-4598-a31b-fed5ac1051bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>lnkDownload</value>
      <webElementGuid>64f5c336-49ff-4305-8813-cfff05da8ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>fdca0457-2dbd-48de-b183-20ed09f2b3e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b4-Reports&quot;)/tbody[1]/tr[@class=&quot;table-row&quot;]/td[5]/a[@class=&quot;text-link&quot;]</value>
      <webElementGuid>96e108b1-64c4-40cf-8b16-eb60a0812868</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='b2-b4-Reports']/tbody/tr/td[5]/a</value>
      <webElementGuid>d133869e-1716-41c1-9c7e-a48b3c95e615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download')]</value>
      <webElementGuid>927e018d-2deb-4bbf-84cf-3b7a5b8f7238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finance Admin 00_02'])[2]/following::a[1]</value>
      <webElementGuid>39eaa623-6c52-4cbe-a776-462819b2d785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Date : 01/01/2025 End Date : 02/01/2025'])[1]/following::a[1]</value>
      <webElementGuid>7ad5cbd5-895e-4b5f-8d41-0e49827a27bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DBS IDEAL'])[1]/preceding::a[1]</value>
      <webElementGuid>a11027f9-1dca-4f52-b7a0-b03d68e9ba07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Date : 16/12/2024 End Date : 27/12/2024'])[1]/preceding::a[1]</value>
      <webElementGuid>67d3bb43-6fc2-464b-a596-689a9cfba0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download']/parent::*</value>
      <webElementGuid>347f1c20-dec3-4df8-8fef-7804a3b9991a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[6]</value>
      <webElementGuid>43a8eda4-cb7b-49f0-b7e4-4a3ec32d8e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>5873c91b-cb45-45aa-96c2-b903270efbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>fd8378fb-8777-4478-9d16-e7a9b373622d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
