<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select type</name>
   <tag></tag>
   <elementGuidId>dcfa83a7-dc1e-446f-883d-1cfc294bf325</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dropdown-display</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@ktl-id='divDropdownReportType']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e4db6069-6bcf-4fba-8e85-7fe27558a240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display</value>
      <webElementGuid>dd183394-2f8c-4d94-ba20-66689b9f907d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select type</value>
      <webElementGuid>7b7b9c1f-f2ae-4ffd-84e7-b8bd9c31aeaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b4-Dropdown_ReportType&quot;)/div[@class=&quot;dropdown-display&quot;]</value>
      <webElementGuid>abe3e610-1695-44dd-a2e7-18e1f1ca5c1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b4-Dropdown_ReportType']/div</value>
      <webElementGuid>bb8e1b91-8f80-4083-9ae0-97cdf78e3e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report type'])[1]/following::div[5]</value>
      <webElementGuid>a53ebd9f-fcd1-4cf6-a82e-b2d33db721d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[2]/following::div[17]</value>
      <webElementGuid>eff476c1-a143-4f09-8088-a7b49ee8c8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate report'])[1]/preceding::div[2]</value>
      <webElementGuid>1813d523-5fa0-4efd-b688-5138531409db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/div/div</value>
      <webElementGuid>4f65a766-f62b-4a20-9151-1ee0edc58d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select type' or . = 'Select type')]</value>
      <webElementGuid>dff169ae-5d6e-4257-8679-4b2af125a6ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
