<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Volunteer</name>
   <tag></tag>
   <elementGuidId>b77a5d08-c325-4135-aacf-f3ca113ea843</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-l1-19_7-$b2']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>09d5ba0e-e893-4c2b-874d-bb75309c8e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-menu-item</value>
      <webElementGuid>0615ad83-879a-4393-b2a1-8bbcd74e781f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/volunteer</value>
      <webElementGuid>90674118-e4a8-497b-bd18-1296a503e8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Volunteer</value>
      <webElementGuid>b68f47e8-028d-42b7-a915-2d37569ae87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-l1-19_7-$b2&quot;)/a[@class=&quot;nav-menu-item&quot;]</value>
      <webElementGuid>3d7467bc-f929-40b1-b187-3264789e2850</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-l1-19_7-$b2']/a</value>
      <webElementGuid>f1a10ab9-b08b-4440-b607-be243d6988f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donate'])[1]/following::a[1]</value>
      <webElementGuid>7568a19d-0b2b-46e5-9818-d81ff5ebb37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact us'])[1]/following::a[5]</value>
      <webElementGuid>a8a87e05-92f6-4486-b97f-d11d75407a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Collaborate'])[1]/preceding::a[1]</value>
      <webElementGuid>96182d23-4f7d-429f-a7d1-d6611697ec36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/volunteer')]</value>
      <webElementGuid>3061eb09-8e5b-42a9-9c8e-01aec6b33983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/a</value>
      <webElementGuid>6207718e-4f40-4f4b-b751-f0e6929f99cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/volunteer' and (text() = 'Volunteer' or . = 'Volunteer')]</value>
      <webElementGuid>638caf17-660f-48fd-9294-2f773a73f828</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
