<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_View members_b3-b28-Switch_Private2</name>
   <tag></tag>
   <elementGuidId>d50b6359-313a-4635-9cc0-bf4698523745</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'btnPrivateCampaign']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b28-Switch_Private2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b3-b28-Switch_Private2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23075ffc-d5d6-4cff-bcd9-8e36b63bfd93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>cb0be17a-364c-407f-a3be-ec0d6e2580fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>479067ef-3df0-46c9-abdc-287253f0c6c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>btnPrivateCampaign</value>
      <webElementGuid>ce64a789-2bc6-4b66-b12f-ff4757ddcdd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b28-Switch_Private2</value>
      <webElementGuid>a7785106-6d19-4aa7-9c7d-faa7307aba74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b28-Switch_Private2&quot;)</value>
      <webElementGuid>bff7dab5-cc42-4fd1-9b35-c32f31734714</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b28-Switch_Private2']</value>
      <webElementGuid>5d7f928e-4a48-447c-9d41-7b76b9dc6602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b28-b9-Switch']/span/input</value>
      <webElementGuid>62d0c959-8112-4a9f-ab42-1f273fa06f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>2840497f-e05d-4613-b4c0-6934f129c589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b3-b28-Switch_Private2']</value>
      <webElementGuid>43a9345a-84cb-474c-829f-cb6db8ccb6db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
