<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_If you are an NPO or a registered chari_594028</name>
   <tag></tag>
   <elementGuidId>cae95c0b-eeec-41be-be38-a3249c3743c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b4-b2-b4-Subtitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b4-b2-b4-Subtitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Registered charity If you are an NPO or a registered charity, click here to create your account. Your charity must be registered with the Commissioner of Charities before doing so.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8e28dd91-dbf6-4dce-ae09-7a78c0fa10e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>choice-card-subtitle</value>
      <webElementGuid>6f9e0b15-696a-4eb9-9531-c43f7c9b033f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-b2-b4-Subtitle</value>
      <webElementGuid>60a59923-1efc-46e4-b129-f5bf0efd85fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>If you are an NPO or a registered charity, click here to create your account. Your charity must be registered with the Commissioner of Charities before doing so.</value>
      <webElementGuid>b159c410-1663-48a2-befc-cbacbbc2cf3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b2-b4-Subtitle&quot;)</value>
      <webElementGuid>40b0d4e0-5a72-4147-9404-dfa69b255a60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b4-b2-b4-Subtitle']</value>
      <webElementGuid>74ee99c5-2e3c-4896-abbe-470656df40c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='b4-b2-b4-ChoiceCardLink']/div[3]/div[2]</value>
      <webElementGuid>39a663e6-9e4a-460a-95a6-2482c2f0b366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registered charity'])[1]/following::div[1]</value>
      <webElementGuid>74f7b338-9f46-4f76-b92c-2c2b0c7eabc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Individual giver'])[1]/following::div[10]</value>
      <webElementGuid>3a74b653-3b8e-40a4-b746-e72178ab9f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organisation'])[1]/preceding::div[5]</value>
      <webElementGuid>502f684d-5a36-4bb0-af61-861dc9cb8329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Groundup'])[1]/preceding::div[14]</value>
      <webElementGuid>5d2a2451-c4ff-4102-bb50-5f9122e74028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='If you are an NPO or a registered charity, click here to create your account. Your charity must be registered with the Commissioner of Charities before doing so.']/parent::*</value>
      <webElementGuid>d1486e57-0df0-471f-81a3-9fc168ad60f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/div[3]/div[2]</value>
      <webElementGuid>5829ba9f-8b27-4f9e-87b8-5d876711f45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b4-b2-b4-Subtitle' and (text() = 'If you are an NPO or a registered charity, click here to create your account. Your charity must be registered with the Commissioner of Charities before doing so.' or . = 'If you are an NPO or a registered charity, click here to create your account. Your charity must be registered with the Commissioner of Charities before doing so.')]</value>
      <webElementGuid>25b8ba9c-16d6-4b47-a818-dcea16ecb583</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
