<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Invite member</name>
   <tag></tag>
   <elementGuidId>3fbd3612-4cb7-4b6b-9bc9-6f1530101a9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'btnInviteMember']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.hide-if-phone.margin-right-s</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>05a7d67a-5eff-45e5-87ae-0336088a7b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary hide-if-phone margin-right-s</value>
      <webElementGuid>43e35a8a-4d14-4b3f-8916-8ae20b508caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aaa78360-0656-4b4e-8f42-7faba723a2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>btnInviteMember</value>
      <webElementGuid>16855291-6d65-4c5c-ab4c-68123cd7d6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invite member</value>
      <webElementGuid>32f3824a-3e26-43f7-8a4c-c229958f3b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-Actions&quot;)/button[@class=&quot;btn btn-primary hide-if-phone margin-right-s&quot;]</value>
      <webElementGuid>cd060b23-7270-488b-ab7e-39bbbcb2a2eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>bbf70532-9674-4cc7-9e68-531524b4528d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-Actions']/button</value>
      <webElementGuid>c27ddb0e-14eb-4077-af36-3024acfc734e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Members'])[3]/following::button[1]</value>
      <webElementGuid>70dbc2bb-625a-4291-9ed9-c134f8c9e5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Members'])[2]/following::button[1]</value>
      <webElementGuid>91ba8ed7-b229-443b-864e-70997ef07b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View batch upload'])[1]/preceding::button[2]</value>
      <webElementGuid>d5c94378-22c2-4966-8bc4-a2d8ace1f54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active (4)'])[1]/preceding::button[4]</value>
      <webElementGuid>3accc76b-a53b-4fe1-a943-179948376023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invite member']/parent::*</value>
      <webElementGuid>3f0a6aba-7907-44c7-a239-119029d47d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div[2]/button</value>
      <webElementGuid>bb90daef-e9f3-4c85-bc99-7f0b28db99f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @ktl-id = 'btnInviteMember' and (text() = 'Invite member' or . = 'Invite member')]</value>
      <webElementGuid>53ca9ded-d5ea-4c14-b862-1919537f8598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active (0)'])[1]/preceding::button[4]</value>
      <webElementGuid>4be0030a-9480-4b2a-a749-1a0f358ca2e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
