<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Members</name>
   <tag></tag>
   <elementGuidId>6bf89217-6930-4680-80c7-75bf441f3a4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b1-Title']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'b2-b1-Title' and (text() = 'Members' or . = 'Members')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-Title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9c0e9e95-44ca-47b2-987d-136c788c9083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content-layout-page-title flex3</value>
      <webElementGuid>f2b5d70c-e318-4272-ace4-f2d3bdb97a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b1-Title</value>
      <webElementGuid>09c05f48-3a56-4f43-a5bc-f8f9bc8c4120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Members</value>
      <webElementGuid>501445a1-727c-4951-9ca6-dd1fa3767828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-Title&quot;)</value>
      <webElementGuid>ad941064-19c3-4b3d-9f07-fbc3c6034f28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-Title']</value>
      <webElementGuid>4d56eb8b-ecc2-4488-ae68-fcd369196b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-$b1']/div/div[2]/div</value>
      <webElementGuid>8d488c57-faa0-463c-b540-ba4fac6e26af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Members'])[2]/following::div[3]</value>
      <webElementGuid>5fdec4e3-71af-4457-8b58-bdfa2d32e67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::div[22]</value>
      <webElementGuid>c993cf25-9825-4083-a5f2-632cea6c2d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invite member'])[1]/preceding::div[1]</value>
      <webElementGuid>95ead31b-8f26-40ab-8b4e-429e029f85c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View batch upload'])[1]/preceding::div[1]</value>
      <webElementGuid>90c1c1ee-b190-47a2-8ee3-d223a6d255cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div</value>
      <webElementGuid>824d1728-f679-4d75-9ce9-cebf384b5a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b1-Title' and (text() = 'Members' or . = 'Members')]</value>
      <webElementGuid>26d164f6-b71d-4f84-a9e9-6ca2b606171a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
