<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Monthly</name>
   <tag></tag>
   <elementGuidId>4ca6019b-ac56-4c22-bf7b-b5eedc858d01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.chips-select-item > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b15-b20-$b6']/div/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bcf34914-c07c-4931-80e1-b04866638868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monthly</value>
      <webElementGuid>f47cd4ea-f8a4-4292-91b7-f88773b6a4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b15-b20-$b6&quot;)/div[@class=&quot;chips-select single-select OSFillParent&quot;]/div[1]/a[@class=&quot;chips-select-item&quot;]/span[1]</value>
      <webElementGuid>49621bff-6615-40dc-8ba4-0632aa1020af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b15-b20-$b6']/div/div/a/span</value>
      <webElementGuid>d784de9c-620f-46b9-af49-86d4d3c8757f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your recurring donation will begin upon successful checkout.'])[1]/following::span[2]</value>
      <webElementGuid>f4df9b7a-e50b-4222-959c-8f63937bd1bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recurring donation'])[1]/following::span[2]</value>
      <webElementGuid>9a56aa43-977e-4e32-8015-7f7133eec97a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yearly'])[1]/preceding::span[2]</value>
      <webElementGuid>8ca8ac17-3c77-4387-bfa6-ef94227031dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End date'])[1]/preceding::span[4]</value>
      <webElementGuid>9145e6df-d8e5-438b-8832-9d10d22e6bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Monthly']/parent::*</value>
      <webElementGuid>46e15f61-349c-4fe4-a582-af90c17059e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/span</value>
      <webElementGuid>6a5ef2ac-4a09-45df-a1e3-3e5e0e86e56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Monthly' or . = 'Monthly')]</value>
      <webElementGuid>6b10160b-f7b2-441b-8ef3-faf581f83f69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
