<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_If the account exists, you will recei_138dc5</name>
   <tag></tag>
   <elementGuidId>96a0895e-abbe-43fd-a7f6-f501a904901f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'inp2faInputBox3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b11-b2-b2-l1-12_2-Input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b3-b11-b2-b2-l1-12_2-Input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>adbf904c-06b9-4267-9a58-319bd3239a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>49559809-9d4d-4089-a920-21fef432af7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7680172-d38d-49cb-aaa2-5496ea8eb5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cb5578d4-b353-439a-b5e3-f7cf5aebfdd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>64049034-f3ce-46f5-92b9-0e5ea5dca86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>c9af040e-c369-4419-9960-e8b42ebd997c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>319a034c-3585-4ddb-89f5-30ef1d6280da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inp2faInputBox3</value>
      <webElementGuid>22494f86-04e1-49e7-a086-8e1c20ee8ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b11-b2-b2-l1-12_2-Input</value>
      <webElementGuid>7daaa801-9942-4e28-8968-2a0a46e24139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b11-b2-b2-l1-12_2-Input&quot;)</value>
      <webElementGuid>4502b1f4-0bf5-49e4-8a8b-bd2b55043b8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b11-b2-b2-l1-12_2-Input']</value>
      <webElementGuid>33133b85-887f-45d6-8f1e-7720d0a81533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b11-b2-b2-InputList']/div[3]/span/input</value>
      <webElementGuid>45fde456-6b99-4733-9a4f-e2c308f93d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/input</value>
      <webElementGuid>e70d7841-5061-4a5f-81b7-09f485e3fa50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b3-b11-b2-b2-l1-12_2-Input']</value>
      <webElementGuid>8829c19a-803a-4f69-aac9-8a8f7721b355</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
