<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Building name_b2-b6-Input_BuildingName</name>
   <tag></tag>
   <elementGuidId>8857dd51-590b-47ee-9ecf-d4e852686939</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'inpBuildingName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b6-Input_BuildingName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b6-Input_BuildingName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d284508-f4e9-4993-b21c-fb4e526ddff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>d227836c-e273-471b-9788-abf95ed3c53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dc54f0c5-b91d-4bdc-92df-7997e14c6374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>605ac2d0-d6c6-448d-93d8-89ef334d106a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inpBuildingName</value>
      <webElementGuid>9b3971e8-682a-40b5-9c5f-7659667ca32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b6-Input_BuildingName</value>
      <webElementGuid>ab044a45-f21c-4153-a1c4-0a9f3af26b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b6-Input_BuildingName&quot;)</value>
      <webElementGuid>47304827-84c6-4e37-ac51-c83e71d8b96d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b6-Input_BuildingName']</value>
      <webElementGuid>1a825cc4-90ad-43b7-b449-ddf87fded696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b6-b27-BuildingNameInput']/span/input</value>
      <webElementGuid>edf42879-34f4-4aa3-b4dc-c0ca229d8ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/input</value>
      <webElementGuid>e6b21778-fa9a-4cdd-ae3d-80831e661873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b2-b6-Input_BuildingName']</value>
      <webElementGuid>e4c92414-155e-4ee7-9261-e9c936732ae2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
