<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search preferred skills</name>
   <tag></tag>
   <elementGuidId>f596e324-b003-4a1a-bc84-25f013b5842c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @class = 'vscomp-search-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vscomp-search-input-9366</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vscomp-search-input-9366']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6740d9f-75fd-4c84-a515-b13b2ce04e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f8bc8e14-5d45-4696-a2cd-9afe30470e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vscomp-search-input</value>
      <webElementGuid>32a39616-9e6f-40e7-8a3d-0700045ab71d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>331fcaaa-76a2-466a-808b-83f8eb4a9041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vscomp-search-input-9366</value>
      <webElementGuid>74f5281f-c084-408b-9751-8cd9652b5a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;vscomp-search-input-1026&quot;]</value>
      <webElementGuid>79d50997-61c4-4b94-863a-4aa44575ef45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vscomp-search-input-9366']</value>
      <webElementGuid>cc4f326d-7c79-4d3f-b814-8bc2bb428a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vscomp-dropbox-container-9366']/div[2]/div/div/input</value>
      <webElementGuid>e2b9e7f9-2c84-4e25-aeee-2e5c478997bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>a16c44e3-03e2-4102-93f3-c63c3be2e108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search...' and @id = 'vscomp-search-input-9366']</value>
      <webElementGuid>98d473c4-2e99-440d-a524-512f30406b4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
