<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_check box Required skills 1</name>
   <tag></tag>
   <elementGuidId>ce6e70a3-4a8a-420c-ab9f-d065bedda44f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b1-b7-b24-l1-442_0-Checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@ktl-id='divRequiredSkills']/div/div/div[3]/div/div/div[1]/div/div[1]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23ac0c13-42db-4132-b513-2061275c6ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>eaac3574-ec64-4356-a558-b32a504c3ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>73bfe672-4ea4-4a0c-a777-297b61763406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b1-b7-b24-l1-442_0-Checkbox</value>
      <webElementGuid>9f2e31de-266b-4167-bffc-0b3a4743c353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b1-b7-b24-l1-442_0-Checkbox&quot;)</value>
      <webElementGuid>d7b22675-4486-4ed1-86a4-a11ef1bf046c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b1-b7-b24-l1-442_0-Checkbox']</value>
      <webElementGuid>3484fef0-3e43-4154-9e7e-d934991feda3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b1-b7-b24-l1-442_0-b1-Control']/span/input</value>
      <webElementGuid>51560a53-6e7e-4a86-a831-73b2ecac6df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div/div/div/div/div/span/input</value>
      <webElementGuid>a618c083-d15f-411e-ad84-4d2f0cd2ec21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b1-b7-b24-l1-442_0-Checkbox']</value>
      <webElementGuid>36b58dea-c181-44b0-99c1-36d11a91f017</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
