<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_If the account exists, you will recei_8059f5</name>
   <tag></tag>
   <elementGuidId>45a0e1cf-54de-4ed9-b111-40dc5f09be89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b3-b11-b2-b2-l1-16_4-Input']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'inp2faInputBox5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b11-b2-b2-l1-16_4-Input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60ed5399-2b79-4e7e-9e50-7ddef6385d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8ac27e90-b156-4ed6-ae53-fb76550ad54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>393f78fa-7a92-4108-bf0c-d9fbfdd1eb12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0a473de1-76c6-42db-a2c8-4baf9495e0bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>637d31c3-d6ee-48ef-8dfc-49bb17575fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>7b317bae-14b2-44f6-99ab-cd56cdebcea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3add46b1-4c0f-48b0-82c0-e83a5176c157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inp2faInputBox5</value>
      <webElementGuid>1c69d381-0be4-4b17-90a8-077187ba177d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b11-b2-b2-l1-16_4-Input</value>
      <webElementGuid>2856f79c-440f-4115-bca6-1b3e26243683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b11-b2-b2-l1-16_4-Input&quot;)</value>
      <webElementGuid>7546b131-1b82-494a-b9c4-08b6853c1382</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b11-b2-b2-l1-16_4-Input']</value>
      <webElementGuid>6fd7ce39-39a0-4111-9c23-444522d701c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b11-b2-b2-InputList']/div[5]/span/input</value>
      <webElementGuid>cddb546f-9abf-407a-8d5c-03fc223bb3d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span/input</value>
      <webElementGuid>87a94ce8-ec97-43c1-b948-b3f9e4fef475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @ktl-id = 'inp2faInputBox5' and @id = 'b3-b11-b2-b2-l1-16_4-Input']</value>
      <webElementGuid>f146a3ed-076c-4d15-b7bf-312ab64b88c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
