<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_If the account exists, you will recei_a193f6</name>
   <tag></tag>
   <elementGuidId>ee140b71-743c-4744-ac66-26f06c92e54d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b3-b11-b2-b2-l1-16_3-Input']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'inp2faInputBox4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b11-b2-b2-l1-16_3-Input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f64ec7a-8650-4653-90ba-7daefdc959f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>825e5022-b10c-4039-a16c-8dfec3a733fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab9aa288-b286-43d9-868b-de2af26bf6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1169b5cd-e014-4bb3-a526-735b4f2beb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bd14454e-4350-40c4-b388-4e36fdf0442a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>10a53b5d-af9a-43b4-b90d-6c6d83cd88bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ab51f981-3171-4c1b-bb32-457b6e9bd133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inp2faInputBox4</value>
      <webElementGuid>fa4ec181-3070-4ab1-87a2-9129546300e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b11-b2-b2-l1-16_3-Input</value>
      <webElementGuid>561e958c-37fe-4f63-9f06-5cceaf6b52a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b11-b2-b2-l1-16_3-Input&quot;)</value>
      <webElementGuid>9bb267f0-acc0-454a-ac73-a307f8d263d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b11-b2-b2-l1-16_3-Input']</value>
      <webElementGuid>e088ed2c-60e3-4b64-9a86-dbeb952bccdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b11-b2-b2-InputList']/div[4]/span/input</value>
      <webElementGuid>17e0e0b7-76ff-4cd8-a8fb-5801caae2efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span/input</value>
      <webElementGuid>c7c88887-7520-409d-ad89-faa02d6f9c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @ktl-id = 'inp2faInputBox4' and @id = 'b3-b11-b2-b2-l1-16_3-Input']</value>
      <webElementGuid>72d692a0-57fd-4d82-9b08-5e3b57053704</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
