<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_If the account exists, you will recei_5a7989</name>
   <tag></tag>
   <elementGuidId>f47f5d7d-1434-4947-96ee-089b28e3c93c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b3-b11-b2-b2-l1-13_2-Input']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'inp2faInputBox3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b11-b2-b2-l1-13_2-Input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f01fd50-343d-4bb5-95d9-fa5f93444874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3a7497ec-d304-4dfb-870f-6b2e679e159e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6f5e37f4-4c46-4697-8449-57c3218a7043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6885cbb4-b6fc-4c59-a9e2-08865eb9a773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8e07c350-7ab3-4388-b359-6400cae0c0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>a05822a8-438c-469d-9ee4-872819657606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c19f7ba3-c62f-4241-a9fa-6a6581e7b7f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>inp2faInputBox3</value>
      <webElementGuid>05bd5fba-7d6d-490b-b576-4acb9f5db400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a819934e-f3ed-427f-9666-aa179c1ab156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b11-b2-b2-l1-13_2-Input</value>
      <webElementGuid>1f4a1f8f-bf56-4964-a97f-e9ea317cd62b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-field-id</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3a766c62-777e-44e1-8e5b-36b528c9f45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b11-b2-b2-l1-13_2-Input&quot;)</value>
      <webElementGuid>f972fb5f-4355-4e34-87f8-9e53c3a0cf46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b11-b2-b2-l1-13_2-Input']</value>
      <webElementGuid>247786ae-0fab-4ea1-90c9-eb88da58bd5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b11-b2-b2-InputList']/div[3]/span/input</value>
      <webElementGuid>4b9177a9-04d9-40a9-a572-bc29f70b8176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/input</value>
      <webElementGuid>288e3e6c-33d3-481b-9247-42dd18f62646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b3-b11-b2-b2-l1-13_2-Input']</value>
      <webElementGuid>7660f368-5bcc-4dc0-903f-fe15b2920b53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
