<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cancel opportunity</name>
   <tag></tag>
   <elementGuidId>bb949c20-7b29-494b-b707-0619db8323a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.negative.ThemeGrid_MarginGutter</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ktl-id = 'lnkCancelOpp']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b40-l1_0-237_0-b13-Items']/a[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6a1f5dd6-c7e5-4b44-8197-03bc976539e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>negative ThemeGrid_MarginGutter</value>
      <webElementGuid>b569bb2a-f1cc-44eb-8e3d-3347a2813b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>27794ca8-e35c-4d31-ab79-3927b4721dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancel opportunity</value>
      <webElementGuid>f24b8293-0006-4355-9880-5ebf8794000b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b40-l1_0-237_0-b13-Items&quot;)/a[@class=&quot;negative ThemeGrid_MarginGutter&quot;]</value>
      <webElementGuid>cc843d25-f9b7-4f2b-a045-30e3233a53f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ktl-id</name>
      <type>Main</type>
      <value>lnkCancelOpp</value>
      <webElementGuid>2e8c3192-bb9f-433c-8ccb-e99f19a56246</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b40-l1_0-237_0-b13-Items']/a[5]</value>
      <webElementGuid>2463556d-2a31-44c7-9f49-58a91c05f555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[1]/following::a[1]</value>
      <webElementGuid>b536ac5c-d247-4d14-b24f-aff1a63611a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Duplicate'])[1]/following::a[2]</value>
      <webElementGuid>d80896a2-d1bd-4caf-b053-c74948052902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skills0012'])[1]/preceding::a[1]</value>
      <webElementGuid>cb963579-f60d-49df-9ed2-3e86215aceff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
      <webElementGuid>0b64f6f0-654e-4fcb-97b5-c4d90f53e7bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a[5]</value>
      <webElementGuid>bde90d99-a1b8-46ec-b275-1582ac99e2d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Cancel opportunity' or . = 'Cancel opportunity')]</value>
      <webElementGuid>83beab42-27b8-4924-a780-2dad72c21555</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
