<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_History</name>
   <tag></tag>
   <elementGuidId>ee7633c5-f265-413e-bb82-279729523dad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-tab = '1' and (text() = 'History' or . = 'History')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='0.ccnpyshw2dd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;0.ccnpyshw2dd&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7086bcfa-35e8-431e-ba51-e748be63bb8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-tabs__header-item</value>
      <webElementGuid>1e1b5890-3209-4054-bae5-a9e9fdfdcb13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>0.ccnpyshw2dd</value>
      <webElementGuid>d919ecfb-1d28-42a3-8b7c-83215c195797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tab</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5661bc24-64a1-4970-80ed-9968e4bb8d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>726fbbf3-27a8-42bd-9727-57e566e9a19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d058296c-6d03-426a-8c06-610f9842acdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>394610ac-da66-4de2-a1eb-d146ce8a9666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>b2-$b41</value>
      <webElementGuid>dabba8f0-a5c3-41a2-ab52-378bafb0ba73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>History</value>
      <webElementGuid>36f64a33-7fe7-4fd5-b8b5-b6fc2a67afc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-$b38&quot;)/button[@class=&quot;osui-tabs__header-item&quot;]</value>
      <webElementGuid>1437f635-904e-401e-8bd3-2c3e45f7cfa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='0.ccnpyshw2dd']</value>
      <webElementGuid>bf7f7e8b-81e6-41a7-9d62-12ecf2eeb15a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-$b38']/button</value>
      <webElementGuid>3dcb0cda-33ab-4960-bc2e-3d062a59cb98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opportunities'])[4]/following::button[1]</value>
      <webElementGuid>4b3a62ba-4227-4744-97db-7cb5978ea421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/following::button[2]</value>
      <webElementGuid>c35b3bd2-65b5-4722-b38e-8537fd4d7be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opportunity'])[1]/preceding::button[1]</value>
      <webElementGuid>71fa5a9c-75db-47b5-acb3-5a7de63e8402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div/div[2]/button</value>
      <webElementGuid>87f861f2-71c3-4d35-a225-803a4ae4d597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = '0.ccnpyshw2dd' and (text() = 'History' or . = 'History')]</value>
      <webElementGuid>f688cc18-78a1-45e4-b410-f42d0a621d73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
