<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Linda Ming_icon-box</name>
   <tag></tag>
   <elementGuidId>bce429a8-2c57-4058-8127-c40505e44e6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b40-l1_0-217_1-b13-b1-Content > div.icon-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b40-l1_0-217_1-b13-b1-Content']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6dec9007-88ae-4b69-9473-b85e75b3ed1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-box</value>
      <webElementGuid>93a66cfe-f6f1-4153-afa1-9bfa738a2b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b40-l1_0-217_1-b13-b1-Content&quot;)/div[@class=&quot;icon-box&quot;]</value>
      <webElementGuid>0cfed5e5-0f99-40fa-b56b-e4d7fe5ba973</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b40-l1_0-217_1-b13-b1-Content']/div</value>
      <webElementGuid>1dd0b8a9-08bd-4838-a292-3c4ef95a7ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Linda Ming'])[1]/following::div[5]</value>
      <webElementGuid>34238fc0-0fb0-4462-83b6-b12c28887db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One time'])[3]/following::div[6]</value>
      <webElementGuid>16fdb2f7-01f0-4df7-8d0e-f9ce1930a678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[2]/preceding::div[2]</value>
      <webElementGuid>d0f9a6f8-2d3f-4f43-b1ec-8327aa58b703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[2]/preceding::div[7]</value>
      <webElementGuid>652a6f2d-63fd-47a9-91fd-04f7b7484e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[7]/div/div/div/div/div</value>
      <webElementGuid>9aa44007-a6d1-4b84-8aed-fd3de0d0a1c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
