<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Billy Joel_icon-box_1</name>
   <tag></tag>
   <elementGuidId>9ec8e84f-79f8-4d92-854f-88a648536e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-b40-l1_0-220_0-b13-b1-Content > div.icon-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b40-l1_0-220_0-b13-b1-Content']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7cff0710-35e2-438e-9d65-67138068c39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-box</value>
      <webElementGuid>23afaec8-12b8-4c8c-8fdf-aad6a2969e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b40-l1_0-220_0-b13-b1-Content&quot;)/div[@class=&quot;icon-box&quot;]</value>
      <webElementGuid>e1698482-ae15-4577-a947-9b9a758659ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b40-l1_0-220_0-b13-b1-Content']/div</value>
      <webElementGuid>c83159bb-8b65-4239-ae56-531b9b08bd67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billy Joel'])[1]/following::div[5]</value>
      <webElementGuid>51b69a3a-0032-4aba-bd4f-38babc28147b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project based'])[2]/following::div[6]</value>
      <webElementGuid>ec38c1ea-db8c-4b03-91db-f85bdf124c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::div[2]</value>
      <webElementGuid>807cacfb-35dd-4218-8642-f90b145847d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::div[7]</value>
      <webElementGuid>9a69fe93-b256-4493-9626-456d98598c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/div/div/div/div</value>
      <webElementGuid>c8ef10f4-5b2c-4d4e-9123-eae0fa475307</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
