<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Active_Checkbox</name>
   <tag></tag>
   <elementGuidId>a0993c06-9476-4a6e-be29-7c01c6d82dd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'checkbox' and @id = 'b2-b34-l1-159_1-Checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b34-l1-159_1-Checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@ktl-id='divStatus']/div/div/div[3]/div/div/div[4]/div/div[1]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>351e0813-b5b8-4afe-9faf-35a814175ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fb087943-b83f-4155-9899-5d1663d00e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b02b78c9-6f8d-4823-adec-512ba1491378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b34-l1-159_1-Checkbox</value>
      <webElementGuid>b1abd37b-c93a-40c7-9118-baa3c2e8e801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fafc8414-b601-4de0-832a-650bde6a7a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b34-l1-159_1-Checkbox&quot;)</value>
      <webElementGuid>d61885ff-5710-42ae-9c5a-e17c2dc359e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b34-l1-159_1-Checkbox']</value>
      <webElementGuid>69bcdd74-4299-42a5-a3a6-9ab57e6569f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b34-l1-159_1-b1-Control']/span/input</value>
      <webElementGuid>cb50897e-aa95-4cfa-9cac-6e5bee1d2564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/input</value>
      <webElementGuid>314e53ba-e937-473d-ae4c-53216780e59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b34-l1-159_1-Checkbox']</value>
      <webElementGuid>b1e6f02f-f0e8-4d28-a7dc-2685ee133815</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
