<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Draft_b2-b34-l1-159_1-Checkbox</name>
   <tag></tag>
   <elementGuidId>a7864b23-3797-4b81-83cc-fd8f11a2912c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b2-b34-l1-159_1-Checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b34-l1-159_1-Checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7071d6ae-f32b-4882-b016-7bdc0ef7351f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>770494b4-a283-459f-bcff-49fd11235dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>be7d5b1d-55ba-465c-96a1-9f019bcf4a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b34-l1-159_1-Checkbox</value>
      <webElementGuid>a04b29ad-72ba-4260-97fc-2703e43eb590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1759031d-74a5-4953-a0c1-609726c005f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b34-l1-159_1-Checkbox&quot;)</value>
      <webElementGuid>ad708a60-8d69-4b6e-ad6a-4b94b717adc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b2-b34-l1-159_1-Checkbox']</value>
      <webElementGuid>bdf4d4d8-dd53-4549-9ef0-031b7d4bb2bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b34-l1-159_1-b1-Control']/span/input</value>
      <webElementGuid>c4d56be7-844c-456d-adb1-e5298cec2c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span/input</value>
      <webElementGuid>13425886-64b9-4048-a74d-c50fbab3da89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b2-b34-l1-159_1-Checkbox']</value>
      <webElementGuid>b1b54ba1-9b56-4cf4-aebb-70db4a70e3d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
