<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NPO  NPONPO  NPO test editAnimalsArts, _c38c58</name>
   <tag></tag>
   <elementGuidId>0005449e-807a-4f59-8709-92501d429d9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b2-b8-l5-462_0-b15-Content']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b2-b8-l5-462_0-b15-Content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d2e16afe-9ee3-48c2-8e5f-5317239a3925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-card-content-wrapper</value>
      <webElementGuid>8f1dde2a-bda2-460c-a30c-4ca27386ae4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-b8-l5-462_0-b15-Content</value>
      <webElementGuid>f16ed2f9-7984-4103-a761-f069a6ba7200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NPO &amp; NPONPO &amp; NPO test editAnimalsArts, culture and heritage</value>
      <webElementGuid>78c1d623-b556-4741-9935-781a483473fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-b8-l5-462_0-b15-Content&quot;)</value>
      <webElementGuid>796e9781-498e-440c-b80d-77b0c84b5b98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b2-b8-l5-462_0-b15-Content']</value>
      <webElementGuid>c19db081-7700-481c-a9b0-118798b51dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-b8-l5-462_0-$b15']/div/div[4]</value>
      <webElementGuid>85ffc0d9-7f88-4eb8-9fd4-b77e10d4665e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Results per page'])[1]/following::div[14]</value>
      <webElementGuid>0904b01e-c3f9-4396-9511-2a1bbfcc2a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[4]</value>
      <webElementGuid>ce53075a-a4eb-4428-883b-d6109d5a411e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-b8-l5-462_0-b15-Content' and (text() = 'NPO &amp; NPONPO &amp; NPO test editAnimalsArts, culture and heritage' or . = 'NPO &amp; NPONPO &amp; NPO test editAnimalsArts, culture and heritage')]</value>
      <webElementGuid>2dc5153d-6e92-40b7-9c9a-c8d0ebb07a76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
